/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActualTrackDto
 */
export interface ActualTrackDto {
    /**
     * Track name
     * @type {string}
     * @memberof ActualTrackDto
     */
    name: string;
    /**
     * Artist name
     * @type {string}
     * @memberof ActualTrackDto
     */
    artistName: string;
    /**
     * Album art URL
     * @type {string}
     * @memberof ActualTrackDto
     */
    albumArt?: string;
}

/**
 * Check if a given object implements the ActualTrackDto interface.
 */
export function instanceOfActualTrackDto(value: object): value is ActualTrackDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('artistName' in value) || value['artistName'] === undefined) return false;
    return true;
}

export function ActualTrackDtoFromJSON(json: any): ActualTrackDto {
    return ActualTrackDtoFromJSONTyped(json, false);
}

export function ActualTrackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActualTrackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'artistName': json['artistName'],
        'albumArt': json['albumArt'] == null ? undefined : json['albumArt'],
    };
}

export function ActualTrackDtoToJSON(json: any): ActualTrackDto {
    return ActualTrackDtoToJSONTyped(json, false);
}

export function ActualTrackDtoToJSONTyped(value?: ActualTrackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'artistName': value['artistName'],
        'albumArt': value['albumArt'],
    };
}

