/* tslint:disable */
 
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthMeResponseDto
 */
export interface AuthMeResponseDto {
    /**
     * 
     * @type {string}
     * @memberof AuthMeResponseDto
     */
    spotifyUserId: string;
    /**
     * 
     * @type {string}
     * @memberof AuthMeResponseDto
     */
    displayName: string;
    /**
     * 
     * @type {boolean}
     * @memberof AuthMeResponseDto
     */
    isTrusted: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthMeResponseDto
     */
    isAdmin: boolean;
}

/**
 * Check if a given object implements the AuthMeResponseDto interface.
 */
export function instanceOfAuthMeResponseDto(value: object): value is AuthMeResponseDto {
    if (!('spotifyUserId' in value) || value['spotifyUserId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('isTrusted' in value) || value['isTrusted'] === undefined) return false;
    if (!('isAdmin' in value) || value['isAdmin'] === undefined) return false;
    return true;
}

export function AuthMeResponseDtoFromJSON(json: any): AuthMeResponseDto {
    return AuthMeResponseDtoFromJSONTyped(json, false);
}

export function AuthMeResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMeResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'spotifyUserId': json['spotifyUserId'],
        'displayName': json['displayName'],
        'isTrusted': json['isTrusted'],
        'isAdmin': json['isAdmin'],
    };
}

export function AuthMeResponseDtoToJSON(json: any): AuthMeResponseDto {
    return AuthMeResponseDtoToJSONTyped(json, false);
}

export function AuthMeResponseDtoToJSONTyped(value?: AuthMeResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spotifyUserId': value['spotifyUserId'],
        'displayName': value['displayName'],
        'isTrusted': value['isTrusted'],
        'isAdmin': value['isAdmin'],
    };
}

