/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmPasswordResetDto
 */
export interface ConfirmPasswordResetDto {
    /**
     * The token from the link in the email
     * @type {string}
     * @memberof ConfirmPasswordResetDto
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmPasswordResetDto
     */
    password: string;
}

/**
 * Check if a given object implements the ConfirmPasswordResetDto interface.
 */
export function instanceOfConfirmPasswordResetDto(value: object): value is ConfirmPasswordResetDto {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function ConfirmPasswordResetDtoFromJSON(json: any): ConfirmPasswordResetDto {
    return ConfirmPasswordResetDtoFromJSONTyped(json, false);
}

export function ConfirmPasswordResetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmPasswordResetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'password': json['password'],
    };
}

export function ConfirmPasswordResetDtoToJSON(json: any): ConfirmPasswordResetDto {
    return ConfirmPasswordResetDtoToJSONTyped(json, false);
}

export function ConfirmPasswordResetDtoToJSONTyped(value?: ConfirmPasswordResetDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'password': value['password'],
    };
}

