/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStreakQuestionDto
 */
export interface CreateStreakQuestionDto {
    /**
     * The question text
     * @type {string}
     * @memberof CreateStreakQuestionDto
     */
    question: string;
    /**
     * Answer options (4 choices)
     * @type {Array<string>}
     * @memberof CreateStreakQuestionDto
     */
    options: Array<string>;
    /**
     * Index of the correct answer (0-3)
     * @type {number}
     * @memberof CreateStreakQuestionDto
     */
    correctAnswerIndex: number;
    /**
     * Question category
     * @type {string}
     * @memberof CreateStreakQuestionDto
     */
    category: string;
    /**
     * Private context/note about the inside joke
     * @type {string}
     * @memberof CreateStreakQuestionDto
     */
    context?: string;
}

/**
 * Check if a given object implements the CreateStreakQuestionDto interface.
 */
export function instanceOfCreateStreakQuestionDto(value: object): value is CreateStreakQuestionDto {
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('correctAnswerIndex' in value) || value['correctAnswerIndex'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    return true;
}

export function CreateStreakQuestionDtoFromJSON(json: any): CreateStreakQuestionDto {
    return CreateStreakQuestionDtoFromJSONTyped(json, false);
}

export function CreateStreakQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStreakQuestionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'question': json['question'],
        'options': json['options'],
        'correctAnswerIndex': json['correctAnswerIndex'],
        'category': json['category'],
        'context': json['context'] == null ? undefined : json['context'],
    };
}

export function CreateStreakQuestionDtoToJSON(json: any): CreateStreakQuestionDto {
    return CreateStreakQuestionDtoToJSONTyped(json, false);
}

export function CreateStreakQuestionDtoToJSONTyped(value?: CreateStreakQuestionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'question': value['question'],
        'options': value['options'],
        'correctAnswerIndex': value['correctAnswerIndex'],
        'category': value['category'],
        'context': value['context'],
    };
}

