/* tslint:disable */

/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DailyStatsDto
 */
export interface DailyStatsDto {
  /**
   * Current streak (consecutive days played)
   * @type {number}
   * @memberof DailyStatsDto
   */
  currentStreak: number;
  /**
   * Best streak ever
   * @type {number}
   * @memberof DailyStatsDto
   */
  bestStreak: number;
  /**
   * Total daily games played
   * @type {number}
   * @memberof DailyStatsDto
   */
  totalGames: number;
  /**
   * Total wins
   * @type {number}
   * @memberof DailyStatsDto
   */
  totalWins: number;
  /**
   * Win rate 0-1
   * @type {number}
   * @memberof DailyStatsDto
   */
  winRate: number;
  /**
   * Average score per game
   * @type {number}
   * @memberof DailyStatsDto
   */
  averageScore: number;
  /**
   * Wins per round [round1, round2, ..., round6]
   * @type {Array<number>}
   * @memberof DailyStatsDto
   */
  scoreDistribution: Array<number>;
}

/**
 * Check if a given object implements the DailyStatsDto interface.
 */
export function instanceOfDailyStatsDto(value: object): value is DailyStatsDto {
  if (!('currentStreak' in value) || value['currentStreak'] === undefined)
    return false;
  if (!('bestStreak' in value) || value['bestStreak'] === undefined)
    return false;
  if (!('totalGames' in value) || value['totalGames'] === undefined)
    return false;
  if (!('totalWins' in value) || value['totalWins'] === undefined) return false;
  if (!('winRate' in value) || value['winRate'] === undefined) return false;
  if (!('averageScore' in value) || value['averageScore'] === undefined)
    return false;
  if (
    !('scoreDistribution' in value) ||
    value['scoreDistribution'] === undefined
  )
    return false;
  return true;
}

export function DailyStatsDtoFromJSON(json: any): DailyStatsDto {
  return DailyStatsDtoFromJSONTyped(json, false);
}

export function DailyStatsDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DailyStatsDto {
  if (json == null) {
    return json;
  }
  return {
    currentStreak: json['currentStreak'],
    bestStreak: json['bestStreak'],
    totalGames: json['totalGames'],
    totalWins: json['totalWins'],
    winRate: json['winRate'],
    averageScore: json['averageScore'],
    scoreDistribution: json['scoreDistribution'],
  };
}

export function DailyStatsDtoToJSON(json: any): DailyStatsDto {
  return DailyStatsDtoToJSONTyped(json, false);
}

export function DailyStatsDtoToJSONTyped(
  value?: DailyStatsDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentStreak: value['currentStreak'],
    bestStreak: value['bestStreak'],
    totalGames: value['totalGames'],
    totalWins: value['totalWins'],
    winRate: value['winRate'],
    averageScore: value['averageScore'],
    scoreDistribution: value['scoreDistribution'],
  };
}
