/* tslint:disable */

/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuessHistoryDto } from './GuessHistoryDto';
import {
  GuessHistoryDtoFromJSON,
  GuessHistoryDtoFromJSONTyped,
  GuessHistoryDtoToJSON,
  GuessHistoryDtoToJSONTyped,
} from './GuessHistoryDto';

/**
 *
 * @export
 * @interface DailyHistoryEntryDto
 */
export interface DailyHistoryEntryDto {
  /**
   * Daily game ID
   * @type {string}
   * @memberof DailyHistoryEntryDto
   */
  id: string;
  /**
   * Date (YYYY-MM-DD)
   * @type {string}
   * @memberof DailyHistoryEntryDto
   */
  date: string;
  /**
   * Game status: playing | won | lost
   * @type {string}
   * @memberof DailyHistoryEntryDto
   */
  status: string;
  /**
   * Score 0-6 if completed
   * @type {number}
   * @memberof DailyHistoryEntryDto
   */
  score?: number;
  /**
   * Guess history
   * @type {Array<GuessHistoryDto>}
   * @memberof DailyHistoryEntryDto
   */
  guesses: Array<GuessHistoryDto>;
  /**
   * Track name (answer)
   * @type {string}
   * @memberof DailyHistoryEntryDto
   */
  trackName: string;
  /**
   * Artist name
   * @type {string}
   * @memberof DailyHistoryEntryDto
   */
  artistName: string;
  /**
   * Album image URL
   * @type {string}
   * @memberof DailyHistoryEntryDto
   */
  albumImageUrl?: string;
  /**
   * Playlist name
   * @type {string}
   * @memberof DailyHistoryEntryDto
   */
  playlistName: string;
}

/**
 * Check if a given object implements the DailyHistoryEntryDto interface.
 */
export function instanceOfDailyHistoryEntryDto(
  value: object,
): value is DailyHistoryEntryDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('date' in value) || value['date'] === undefined) return false;
  if (!('status' in value) || value['status'] === undefined) return false;
  if (!('guesses' in value) || value['guesses'] === undefined) return false;
  if (!('trackName' in value) || value['trackName'] === undefined) return false;
  if (!('artistName' in value) || value['artistName'] === undefined)
    return false;
  if (!('playlistName' in value) || value['playlistName'] === undefined)
    return false;
  return true;
}

export function DailyHistoryEntryDtoFromJSON(json: any): DailyHistoryEntryDto {
  return DailyHistoryEntryDtoFromJSONTyped(json, false);
}

export function DailyHistoryEntryDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DailyHistoryEntryDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    date: json['date'],
    status: json['status'],
    score: json['score'] == null ? undefined : json['score'],
    guesses: (json['guesses'] as Array<any>).map(GuessHistoryDtoFromJSON),
    trackName: json['trackName'],
    artistName: json['artistName'],
    albumImageUrl:
      json['albumImageUrl'] == null ? undefined : json['albumImageUrl'],
    playlistName: json['playlistName'],
  };
}

export function DailyHistoryEntryDtoToJSON(json: any): DailyHistoryEntryDto {
  return DailyHistoryEntryDtoToJSONTyped(json, false);
}

export function DailyHistoryEntryDtoToJSONTyped(
  value?: DailyHistoryEntryDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    date: value['date'],
    status: value['status'],
    score: value['score'],
    guesses: (value['guesses'] as Array<any>).map(GuessHistoryDtoToJSON),
    trackName: value['trackName'],
    artistName: value['artistName'],
    albumImageUrl: value['albumImageUrl'],
    playlistName: value['playlistName'],
  };
}
