/* tslint:disable */
 
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuessHistoryDto } from './GuessHistoryDto';
import {
    GuessHistoryDtoFromJSON,
    GuessHistoryDtoFromJSONTyped,
    GuessHistoryDtoToJSON,
    GuessHistoryDtoToJSONTyped,
} from './GuessHistoryDto';
import type { TrackOptionDto } from './TrackOptionDto';
import {
    TrackOptionDtoFromJSON,
    TrackOptionDtoFromJSONTyped,
    TrackOptionDtoToJSON,
    TrackOptionDtoToJSONTyped,
} from './TrackOptionDto';

/**
 * 
 * @export
 * @interface DailyTodayDto
 */
export interface DailyTodayDto {
    /**
     * The ID of the game session
     * @type {string}
     * @memberof DailyTodayDto
     */
    sessionId: string;
    /**
     * The current round of the game
     * @type {number}
     * @memberof DailyTodayDto
     */
    currentRound: number;
    /**
     * The duration of the current snippet
     * @type {number}
     * @memberof DailyTodayDto
     */
    snippetDuration: number;
    /**
     * The status of the game
     * @type {string}
     * @memberof DailyTodayDto
     */
    status: DailyTodayDtoStatusEnum;
    /**
     * The guesses of the game
     * @type {Array<GuessHistoryDto>}
     * @memberof DailyTodayDto
     */
    guesses: Array<GuessHistoryDto>;
    /**
     * The preview URL of the current track
     * @type {string}
     * @memberof DailyTodayDto
     */
    previewUrl?: string;
    /**
     * The answer to the current track
     * @type {TrackOptionDto}
     * @memberof DailyTodayDto
     */
    answer?: TrackOptionDto;
    /**
     * Track options to choose from (from same playlist(s) as the daily)
     * @type {Array<TrackOptionDto>}
     * @memberof DailyTodayDto
     */
    trackOptions: Array<TrackOptionDto>;
    /**
     * Playlist name for this daily
     * @type {string}
     * @memberof DailyTodayDto
     */
    playlistName?: string;
}


/**
 * @export
 */
export const DailyTodayDtoStatusEnum = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST'
} as const;
export type DailyTodayDtoStatusEnum = typeof DailyTodayDtoStatusEnum[keyof typeof DailyTodayDtoStatusEnum];


/**
 * Check if a given object implements the DailyTodayDto interface.
 */
export function instanceOfDailyTodayDto(value: object): value is DailyTodayDto {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('currentRound' in value) || value['currentRound'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('guesses' in value) || value['guesses'] === undefined) return false;
    if (!('trackOptions' in value) || value['trackOptions'] === undefined) return false;
    return true;
}

export function DailyTodayDtoFromJSON(json: any): DailyTodayDto {
    return DailyTodayDtoFromJSONTyped(json, false);
}

export function DailyTodayDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DailyTodayDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'currentRound': json['currentRound'],
        'snippetDuration': json['snippetDuration'],
        'status': json['status'],
        'guesses': ((json['guesses'] as Array<any>).map(GuessHistoryDtoFromJSON)),
        'previewUrl': json['previewUrl'] == null ? undefined : json['previewUrl'],
        'answer': json['answer'] == null ? undefined : TrackOptionDtoFromJSON(json['answer']),
        'trackOptions': ((json['trackOptions'] as Array<any>).map(TrackOptionDtoFromJSON)),
        'playlistName': json['playlistName'] == null ? undefined : json['playlistName'],
    };
}

export function DailyTodayDtoToJSON(json: any): DailyTodayDto {
    return DailyTodayDtoToJSONTyped(json, false);
}

export function DailyTodayDtoToJSONTyped(value?: DailyTodayDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'currentRound': value['currentRound'],
        'snippetDuration': value['snippetDuration'],
        'status': value['status'],
        'guesses': ((value['guesses'] as Array<any>).map(GuessHistoryDtoToJSON)),
        'previewUrl': value['previewUrl'],
        'answer': TrackOptionDtoToJSON(value['answer']),
        'trackOptions': ((value['trackOptions'] as Array<any>).map(TrackOptionDtoToJSON)),
        'playlistName': value['playlistName'],
    };
}

