/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DemoOptionDto
 */
export interface DemoOptionDto {
    /**
     * 
     * @type {string}
     * @memberof DemoOptionDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DemoOptionDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DemoOptionDto
     */
    artistName: string;
}

/**
 * Check if a given object implements the DemoOptionDto interface.
 */
export function instanceOfDemoOptionDto(value: object): value is DemoOptionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('artistName' in value) || value['artistName'] === undefined) return false;
    return true;
}

export function DemoOptionDtoFromJSON(json: any): DemoOptionDto {
    return DemoOptionDtoFromJSONTyped(json, false);
}

export function DemoOptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DemoOptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'artistName': json['artistName'],
    };
}

export function DemoOptionDtoToJSON(json: any): DemoOptionDto {
    return DemoOptionDtoToJSONTyped(json, false);
}

export function DemoOptionDtoToJSONTyped(value?: DemoOptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'artistName': value['artistName'],
    };
}

