/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DemoOptionDto } from './DemoOptionDto';
import {
    DemoOptionDtoFromJSON,
    DemoOptionDtoFromJSONTyped,
    DemoOptionDtoToJSON,
    DemoOptionDtoToJSONTyped,
} from './DemoOptionDto';

/**
 * 
 * @export
 * @interface DemoRoundDto
 */
export interface DemoRoundDto {
    /**
     * Opaque round id. Not a session.
     * @type {string}
     * @memberof DemoRoundDto
     */
    roundId: string;
    /**
     * 
     * @type {string}
     * @memberof DemoRoundDto
     */
    previewUrl: string;
    /**
     * 1-based attempt number
     * @type {number}
     * @memberof DemoRoundDto
     */
    attempt: number;
    /**
     * 
     * @type {number}
     * @memberof DemoRoundDto
     */
    totalAttempts: number;
    /**
     * Seconds of audio unlocked so far
     * @type {number}
     * @memberof DemoRoundDto
     */
    snippetDuration: number;
    /**
     * Seconds unlocked at each attempt, so a client can mark them
     * @type {Array<number>}
     * @memberof DemoRoundDto
     */
    snippetSteps: Array<number>;
    /**
     * 
     * @type {Array<DemoOptionDto>}
     * @memberof DemoRoundDto
     */
    options: Array<DemoOptionDto>;
}

/**
 * Check if a given object implements the DemoRoundDto interface.
 */
export function instanceOfDemoRoundDto(value: object): value is DemoRoundDto {
    if (!('roundId' in value) || value['roundId'] === undefined) return false;
    if (!('previewUrl' in value) || value['previewUrl'] === undefined) return false;
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('totalAttempts' in value) || value['totalAttempts'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    if (!('snippetSteps' in value) || value['snippetSteps'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function DemoRoundDtoFromJSON(json: any): DemoRoundDto {
    return DemoRoundDtoFromJSONTyped(json, false);
}

export function DemoRoundDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DemoRoundDto {
    if (json == null) {
        return json;
    }
    return {
        
        'roundId': json['roundId'],
        'previewUrl': json['previewUrl'],
        'attempt': json['attempt'],
        'totalAttempts': json['totalAttempts'],
        'snippetDuration': json['snippetDuration'],
        'snippetSteps': json['snippetSteps'],
        'options': ((json['options'] as Array<any>).map(DemoOptionDtoFromJSON)),
    };
}

export function DemoRoundDtoToJSON(json: any): DemoRoundDto {
    return DemoRoundDtoToJSONTyped(json, false);
}

export function DemoRoundDtoToJSONTyped(value?: DemoRoundDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roundId': value['roundId'],
        'previewUrl': value['previewUrl'],
        'attempt': value['attempt'],
        'totalAttempts': value['totalAttempts'],
        'snippetDuration': value['snippetDuration'],
        'snippetSteps': value['snippetSteps'],
        'options': ((value['options'] as Array<any>).map(DemoOptionDtoToJSON)),
    };
}

