/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DemoAnswerDto
 */
export interface DemoAnswerDto {
    /**
     * 
     * @type {string}
     * @memberof DemoAnswerDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DemoAnswerDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DemoAnswerDto
     */
    artistName: string;
    /**
     * 
     * @type {string}
     * @memberof DemoAnswerDto
     */
    albumImageUrl: string;
}

/**
 * Check if a given object implements the DemoAnswerDto interface.
 */
export function instanceOfDemoAnswerDto(value: object): value is DemoAnswerDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('artistName' in value) || value['artistName'] === undefined) return false;
    if (!('albumImageUrl' in value) || value['albumImageUrl'] === undefined) return false;
    return true;
}

export function DemoAnswerDtoFromJSON(json: any): DemoAnswerDto {
    return DemoAnswerDtoFromJSONTyped(json, false);
}

export function DemoAnswerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DemoAnswerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'artistName': json['artistName'],
        'albumImageUrl': json['albumImageUrl'],
    };
}

export function DemoAnswerDtoToJSON(json: any): DemoAnswerDto {
    return DemoAnswerDtoToJSONTyped(json, false);
}

export function DemoAnswerDtoToJSONTyped(value?: DemoAnswerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'artistName': value['artistName'],
        'albumImageUrl': value['albumImageUrl'],
    };
}

