/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DemoPlaylistDto
 */
export interface DemoPlaylistDto {
    /**
     * Stable key used when starting a round
     * @type {string}
     * @memberof DemoPlaylistDto
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof DemoPlaylistDto
     */
    name: string;
    /**
     * Chart cover art; empty before the first refresh
     * @type {string}
     * @memberof DemoPlaylistDto
     */
    imageUrl: string;
    /**
     * 
     * @type {string}
     * @memberof DemoPlaylistDto
     */
    description?: string;
}

/**
 * Check if a given object implements the DemoPlaylistDto interface.
 */
export function instanceOfDemoPlaylistDto(value: object): value is DemoPlaylistDto {
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function DemoPlaylistDtoFromJSON(json: any): DemoPlaylistDto {
    return DemoPlaylistDtoFromJSONTyped(json, false);
}

export function DemoPlaylistDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DemoPlaylistDto {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'imageUrl': json['imageUrl'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function DemoPlaylistDtoToJSON(json: any): DemoPlaylistDto {
    return DemoPlaylistDtoToJSONTyped(json, false);
}

export function DemoPlaylistDtoToJSONTyped(value?: DemoPlaylistDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'imageUrl': value['imageUrl'],
        'description': value['description'],
    };
}

