/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DemoAnswerDto } from './DemoAnswerDto';
import {
    DemoAnswerDtoFromJSON,
    DemoAnswerDtoFromJSONTyped,
    DemoAnswerDtoToJSON,
    DemoAnswerDtoToJSONTyped,
} from './DemoAnswerDto';

/**
 * 
 * @export
 * @interface DemoGuessResultDto
 */
export interface DemoGuessResultDto {
    /**
     * 
     * @type {boolean}
     * @memberof DemoGuessResultDto
     */
    correct: boolean;
    /**
     * 
     * @type {string}
     * @memberof DemoGuessResultDto
     */
    status: DemoGuessResultDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof DemoGuessResultDto
     */
    attempt: number;
    /**
     * 
     * @type {number}
     * @memberof DemoGuessResultDto
     */
    totalAttempts: number;
    /**
     * 
     * @type {number}
     * @memberof DemoGuessResultDto
     */
    snippetDuration: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof DemoGuessResultDto
     */
    wrongIds: Array<string>;
    /**
     * Only present once the round is won or lost
     * @type {DemoAnswerDto}
     * @memberof DemoGuessResultDto
     */
    answer?: DemoAnswerDto;
}


/**
 * @export
 */
export const DemoGuessResultDtoStatusEnum = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST'
} as const;
export type DemoGuessResultDtoStatusEnum = typeof DemoGuessResultDtoStatusEnum[keyof typeof DemoGuessResultDtoStatusEnum];


/**
 * Check if a given object implements the DemoGuessResultDto interface.
 */
export function instanceOfDemoGuessResultDto(value: object): value is DemoGuessResultDto {
    if (!('correct' in value) || value['correct'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('totalAttempts' in value) || value['totalAttempts'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    if (!('wrongIds' in value) || value['wrongIds'] === undefined) return false;
    return true;
}

export function DemoGuessResultDtoFromJSON(json: any): DemoGuessResultDto {
    return DemoGuessResultDtoFromJSONTyped(json, false);
}

export function DemoGuessResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DemoGuessResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'correct': json['correct'],
        'status': json['status'],
        'attempt': json['attempt'],
        'totalAttempts': json['totalAttempts'],
        'snippetDuration': json['snippetDuration'],
        'wrongIds': json['wrongIds'],
        'answer': json['answer'] == null ? undefined : DemoAnswerDtoFromJSON(json['answer']),
    };
}

export function DemoGuessResultDtoToJSON(json: any): DemoGuessResultDto {
    return DemoGuessResultDtoToJSONTyped(json, false);
}

export function DemoGuessResultDtoToJSONTyped(value?: DemoGuessResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'correct': value['correct'],
        'status': value['status'],
        'attempt': value['attempt'],
        'totalAttempts': value['totalAttempts'],
        'snippetDuration': value['snippetDuration'],
        'wrongIds': value['wrongIds'],
        'answer': DemoAnswerDtoToJSON(value['answer']),
    };
}

