/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailVerificationResultDto
 */
export interface EmailVerificationResultDto {
    /**
     * Whether the link was live. False covers wrong, expired and already used alike: all three mean the same thing to whoever is holding it.
     * @type {boolean}
     * @memberof EmailVerificationResultDto
     */
    verified: boolean;
}

/**
 * Check if a given object implements the EmailVerificationResultDto interface.
 */
export function instanceOfEmailVerificationResultDto(value: object): value is EmailVerificationResultDto {
    if (!('verified' in value) || value['verified'] === undefined) return false;
    return true;
}

export function EmailVerificationResultDtoFromJSON(json: any): EmailVerificationResultDto {
    return EmailVerificationResultDtoFromJSONTyped(json, false);
}

export function EmailVerificationResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailVerificationResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'verified': json['verified'],
    };
}

export function EmailVerificationResultDtoToJSON(json: any): EmailVerificationResultDto {
    return EmailVerificationResultDtoToJSONTyped(json, false);
}

export function EmailVerificationResultDtoToJSONTyped(value?: EmailVerificationResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verified': value['verified'],
    };
}

