/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackResultDto } from './TrackResultDto';
import {
    TrackResultDtoFromJSON,
    TrackResultDtoFromJSONTyped,
    TrackResultDtoToJSON,
    TrackResultDtoToJSONTyped,
} from './TrackResultDto';
import type { GuessHistoryDto } from './GuessHistoryDto';
import {
    GuessHistoryDtoFromJSON,
    GuessHistoryDtoFromJSONTyped,
    GuessHistoryDtoToJSON,
    GuessHistoryDtoToJSONTyped,
} from './GuessHistoryDto';

/**
 * 
 * @export
 * @interface EventStateDto
 */
export interface EventStateDto {
    /**
     * Index of the current track (0-based)
     * @type {number}
     * @memberof EventStateDto
     */
    trackIndex: number;
    /**
     * Total number of tracks in the run
     * @type {number}
     * @memberof EventStateDto
     */
    totalTracks: number;
    /**
     * Current round within the current track (0-based)
     * @type {number}
     * @memberof EventStateDto
     */
    currentRound: number;
    /**
     * Max rounds per track
     * @type {number}
     * @memberof EventStateDto
     */
    maxRounds: number;
    /**
     * Snippet duration in seconds for current round
     * @type {number}
     * @memberof EventStateDto
     */
    snippetDuration: number;
    /**
     * Preview URL for the current track (null when run is complete)
     * @type {string}
     * @memberof EventStateDto
     */
    previewUrl?: string;
    /**
     * True when the entire 8-track run is finished
     * @type {boolean}
     * @memberof EventStateDto
     */
    isComplete: boolean;
    /**
     * Guess history for the current track in-progress
     * @type {Array<GuessHistoryDto>}
     * @memberof EventStateDto
     */
    currentGuesses: Array<GuessHistoryDto>;
    /**
     * Finalized results for tracks already played
     * @type {Array<TrackResultDto>}
     * @memberof EventStateDto
     */
    trackResults: Array<TrackResultDto>;
}

/**
 * Check if a given object implements the EventStateDto interface.
 */
export function instanceOfEventStateDto(value: object): value is EventStateDto {
    if (!('trackIndex' in value) || value['trackIndex'] === undefined) return false;
    if (!('totalTracks' in value) || value['totalTracks'] === undefined) return false;
    if (!('currentRound' in value) || value['currentRound'] === undefined) return false;
    if (!('maxRounds' in value) || value['maxRounds'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    if (!('isComplete' in value) || value['isComplete'] === undefined) return false;
    if (!('currentGuesses' in value) || value['currentGuesses'] === undefined) return false;
    if (!('trackResults' in value) || value['trackResults'] === undefined) return false;
    return true;
}

export function EventStateDtoFromJSON(json: any): EventStateDto {
    return EventStateDtoFromJSONTyped(json, false);
}

export function EventStateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventStateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'trackIndex': json['trackIndex'],
        'totalTracks': json['totalTracks'],
        'currentRound': json['currentRound'],
        'maxRounds': json['maxRounds'],
        'snippetDuration': json['snippetDuration'],
        'previewUrl': json['previewUrl'] == null ? undefined : json['previewUrl'],
        'isComplete': json['isComplete'],
        'currentGuesses': ((json['currentGuesses'] as Array<any>).map(GuessHistoryDtoFromJSON)),
        'trackResults': ((json['trackResults'] as Array<any>).map(TrackResultDtoFromJSON)),
    };
}

export function EventStateDtoToJSON(json: any): EventStateDto {
    return EventStateDtoToJSONTyped(json, false);
}

export function EventStateDtoToJSONTyped(value?: EventStateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trackIndex': value['trackIndex'],
        'totalTracks': value['totalTracks'],
        'currentRound': value['currentRound'],
        'maxRounds': value['maxRounds'],
        'snippetDuration': value['snippetDuration'],
        'previewUrl': value['previewUrl'],
        'isComplete': value['isComplete'],
        'currentGuesses': ((value['currentGuesses'] as Array<any>).map(GuessHistoryDtoToJSON)),
        'trackResults': ((value['trackResults'] as Array<any>).map(TrackResultDtoToJSON)),
    };
}

