/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameStatsDto
 */
export interface GameStatsDto {
    /**
     * The tally in progress: a streak or a run
     * @type {number}
     * @memberof GameStatsDto
     */
    current: number;
    /**
     * The longest this tally has ever been
     * @type {number}
     * @memberof GameStatsDto
     */
    best: number;
    /**
     * What the tally counts
     * @type {string}
     * @memberof GameStatsDto
     */
    unit: GameStatsDtoUnitEnum;
    /**
     * The total games
     * @type {number}
     * @memberof GameStatsDto
     */
    totalGames: number;
    /**
     * The total wins
     * @type {number}
     * @memberof GameStatsDto
     */
    totalWins: number;
    /**
     * The round distribution
     * @type {Array<number>}
     * @memberof GameStatsDto
     */
    roundDistribution: Array<number>;
    /**
     * The game mode
     * @type {string}
     * @memberof GameStatsDto
     */
    mode: GameStatsDtoModeEnum;
    /**
     * The win rate
     * @type {number}
     * @memberof GameStatsDto
     */
    winRate: number;
    /**
     * The average score
     * @type {number}
     * @memberof GameStatsDto
     */
    averageScore: number;
}


/**
 * @export
 */
export const GameStatsDtoUnitEnum = {
    Days: 'DAYS',
    Wins: 'WINS'
} as const;
export type GameStatsDtoUnitEnum = typeof GameStatsDtoUnitEnum[keyof typeof GameStatsDtoUnitEnum];

/**
 * @export
 */
export const GameStatsDtoModeEnum = {
    Daily: 'DAILY',
    All: 'ALL',
    Multiplayer: 'MULTIPLAYER',
    Gauntlet: 'GAUNTLET'
} as const;
export type GameStatsDtoModeEnum = typeof GameStatsDtoModeEnum[keyof typeof GameStatsDtoModeEnum];


/**
 * Check if a given object implements the GameStatsDto interface.
 */
export function instanceOfGameStatsDto(value: object): value is GameStatsDto {
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('best' in value) || value['best'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    if (!('totalGames' in value) || value['totalGames'] === undefined) return false;
    if (!('totalWins' in value) || value['totalWins'] === undefined) return false;
    if (!('roundDistribution' in value) || value['roundDistribution'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('winRate' in value) || value['winRate'] === undefined) return false;
    if (!('averageScore' in value) || value['averageScore'] === undefined) return false;
    return true;
}

export function GameStatsDtoFromJSON(json: any): GameStatsDto {
    return GameStatsDtoFromJSONTyped(json, false);
}

export function GameStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStatsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'],
        'best': json['best'],
        'unit': json['unit'],
        'totalGames': json['totalGames'],
        'totalWins': json['totalWins'],
        'roundDistribution': json['roundDistribution'],
        'mode': json['mode'],
        'winRate': json['winRate'],
        'averageScore': json['averageScore'],
    };
}

export function GameStatsDtoToJSON(json: any): GameStatsDto {
    return GameStatsDtoToJSONTyped(json, false);
}

export function GameStatsDtoToJSONTyped(value?: GameStatsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current': value['current'],
        'best': value['best'],
        'unit': value['unit'],
        'totalGames': value['totalGames'],
        'totalWins': value['totalWins'],
        'roundDistribution': value['roundDistribution'],
        'mode': value['mode'],
        'winRate': value['winRate'],
        'averageScore': value['averageScore'],
    };
}

