/* tslint:disable */
 
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameStatsEntity
 */
export interface GameStatsEntity {
    /**
     * The ID of the stats
     * @type {string}
     * @memberof GameStatsEntity
     */
    id: string;
    /**
     * The ID of the user
     * @type {string}
     * @memberof GameStatsEntity
     */
    userId: string;
    /**
     * The current streak
     * @type {number}
     * @memberof GameStatsEntity
     */
    currentStreak: number;
    /**
     * The best streak
     * @type {number}
     * @memberof GameStatsEntity
     */
    bestStreak: number;
    /**
     * The total games
     * @type {number}
     * @memberof GameStatsEntity
     */
    totalGames: number;
    /**
     * The total wins
     * @type {number}
     * @memberof GameStatsEntity
     */
    totalWins: number;
    /**
     * The total score
     * @type {number}
     * @memberof GameStatsEntity
     */
    totalScore: number;
    /**
     * The score distribution
     * @type {Array<number>}
     * @memberof GameStatsEntity
     */
    scoreDistribution: Array<number>;
    /**
     * The game mode
     * @type {string}
     * @memberof GameStatsEntity
     */
    mode: GameStatsEntityModeEnum;
}


/**
 * @export
 */
export const GameStatsEntityModeEnum = {
    Daily: 'DAILY',
    Playlist: 'PLAYLIST'
} as const;
export type GameStatsEntityModeEnum = typeof GameStatsEntityModeEnum[keyof typeof GameStatsEntityModeEnum];


/**
 * Check if a given object implements the GameStatsEntity interface.
 */
export function instanceOfGameStatsEntity(value: object): value is GameStatsEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('currentStreak' in value) || value['currentStreak'] === undefined) return false;
    if (!('bestStreak' in value) || value['bestStreak'] === undefined) return false;
    if (!('totalGames' in value) || value['totalGames'] === undefined) return false;
    if (!('totalWins' in value) || value['totalWins'] === undefined) return false;
    if (!('totalScore' in value) || value['totalScore'] === undefined) return false;
    if (!('scoreDistribution' in value) || value['scoreDistribution'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function GameStatsEntityFromJSON(json: any): GameStatsEntity {
    return GameStatsEntityFromJSONTyped(json, false);
}

export function GameStatsEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStatsEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'currentStreak': json['currentStreak'],
        'bestStreak': json['bestStreak'],
        'totalGames': json['totalGames'],
        'totalWins': json['totalWins'],
        'totalScore': json['totalScore'],
        'scoreDistribution': json['scoreDistribution'],
        'mode': json['mode'],
    };
}

export function GameStatsEntityToJSON(json: any): GameStatsEntity {
    return GameStatsEntityToJSONTyped(json, false);
}

export function GameStatsEntityToJSONTyped(value?: GameStatsEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'currentStreak': value['currentStreak'],
        'bestStreak': value['bestStreak'],
        'totalGames': value['totalGames'],
        'totalWins': value['totalWins'],
        'totalScore': value['totalScore'],
        'scoreDistribution': value['scoreDistribution'],
        'mode': value['mode'],
    };
}

