/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StreakFreezeUsageDto } from './StreakFreezeUsageDto';
import {
    StreakFreezeUsageDtoFromJSON,
    StreakFreezeUsageDtoFromJSONTyped,
    StreakFreezeUsageDtoToJSON,
    StreakFreezeUsageDtoToJSONTyped,
} from './StreakFreezeUsageDto';
import type { GameHistoryEntryDto } from './GameHistoryEntryDto';
import {
    GameHistoryEntryDtoFromJSON,
    GameHistoryEntryDtoFromJSONTyped,
    GameHistoryEntryDtoToJSON,
    GameHistoryEntryDtoToJSONTyped,
} from './GameHistoryEntryDto';

/**
 * 
 * @export
 * @interface GameHistoryDto
 */
export interface GameHistoryDto {
    /**
     * 
     * @type {Array<GameHistoryEntryDto>}
     * @memberof GameHistoryDto
     */
    items: Array<GameHistoryEntryDto>;
    /**
     * Total count
     * @type {number}
     * @memberof GameHistoryDto
     */
    total: number;
    /**
     * Streak freeze usages within the date range (only for DAILY mode)
     * @type {Array<StreakFreezeUsageDto>}
     * @memberof GameHistoryDto
     */
    streakFreezeUsages?: Array<StreakFreezeUsageDto>;
}

/**
 * Check if a given object implements the GameHistoryDto interface.
 */
export function instanceOfGameHistoryDto(value: object): value is GameHistoryDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function GameHistoryDtoFromJSON(json: any): GameHistoryDto {
    return GameHistoryDtoFromJSONTyped(json, false);
}

export function GameHistoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameHistoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GameHistoryEntryDtoFromJSON)),
        'total': json['total'],
        'streakFreezeUsages': json['streakFreezeUsages'] == null ? undefined : ((json['streakFreezeUsages'] as Array<any>).map(StreakFreezeUsageDtoFromJSON)),
    };
}

export function GameHistoryDtoToJSON(json: any): GameHistoryDto {
    return GameHistoryDtoToJSONTyped(json, false);
}

export function GameHistoryDtoToJSONTyped(value?: GameHistoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(GameHistoryEntryDtoToJSON)),
        'total': value['total'],
        'streakFreezeUsages': value['streakFreezeUsages'] == null ? undefined : ((value['streakFreezeUsages'] as Array<any>).map(StreakFreezeUsageDtoToJSON)),
    };
}

