/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuessHistoryDto } from './GuessHistoryDto';
import {
    GuessHistoryDtoFromJSON,
    GuessHistoryDtoFromJSONTyped,
    GuessHistoryDtoToJSON,
    GuessHistoryDtoToJSONTyped,
} from './GuessHistoryDto';
import type { TrackOptionDto } from './TrackOptionDto';
import {
    TrackOptionDtoFromJSON,
    TrackOptionDtoFromJSONTyped,
    TrackOptionDtoToJSON,
    TrackOptionDtoToJSONTyped,
} from './TrackOptionDto';

/**
 * 
 * @export
 * @interface GameStateDto
 */
export interface GameStateDto {
    /**
     * 
     * @type {string}
     * @memberof GameStateDto
     */
    sessionId: string;
    /**
     * 
     * @type {number}
     * @memberof GameStateDto
     */
    currentRound: number;
    /**
     * 
     * @type {number}
     * @memberof GameStateDto
     */
    snippetDuration: number;
    /**
     * 
     * @type {string}
     * @memberof GameStateDto
     */
    status: GameStateDtoStatusEnum;
    /**
     * 
     * @type {Array<GuessHistoryDto>}
     * @memberof GameStateDto
     */
    guesses: Array<GuessHistoryDto>;
    /**
     * The preview URL of the current track
     * @type {string}
     * @memberof GameStateDto
     */
    previewUrl?: string;
    /**
     * 
     * @type {Array<TrackOptionDto>}
     * @memberof GameStateDto
     */
    trackOptions: Array<TrackOptionDto>;
    /**
     * 
     * @type {TrackOptionDto}
     * @memberof GameStateDto
     */
    answer: TrackOptionDto | null;
}


/**
 * @export
 */
export const GameStateDtoStatusEnum = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST'
} as const;
export type GameStateDtoStatusEnum = typeof GameStateDtoStatusEnum[keyof typeof GameStateDtoStatusEnum];


/**
 * Check if a given object implements the GameStateDto interface.
 */
export function instanceOfGameStateDto(value: object): value is GameStateDto {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('currentRound' in value) || value['currentRound'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('guesses' in value) || value['guesses'] === undefined) return false;
    if (!('trackOptions' in value) || value['trackOptions'] === undefined) return false;
    if (!('answer' in value) || value['answer'] === undefined) return false;
    return true;
}

export function GameStateDtoFromJSON(json: any): GameStateDto {
    return GameStateDtoFromJSONTyped(json, false);
}

export function GameStateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'currentRound': json['currentRound'],
        'snippetDuration': json['snippetDuration'],
        'status': json['status'],
        'guesses': ((json['guesses'] as Array<any>).map(GuessHistoryDtoFromJSON)),
        'previewUrl': json['previewUrl'] == null ? undefined : json['previewUrl'],
        'trackOptions': ((json['trackOptions'] as Array<any>).map(TrackOptionDtoFromJSON)),
        'answer': TrackOptionDtoFromJSON(json['answer']),
    };
}

export function GameStateDtoToJSON(json: any): GameStateDto {
    return GameStateDtoToJSONTyped(json, false);
}

export function GameStateDtoToJSONTyped(value?: GameStateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'currentRound': value['currentRound'],
        'snippetDuration': value['snippetDuration'],
        'status': value['status'],
        'guesses': ((value['guesses'] as Array<any>).map(GuessHistoryDtoToJSON)),
        'previewUrl': value['previewUrl'],
        'trackOptions': ((value['trackOptions'] as Array<any>).map(TrackOptionDtoToJSON)),
        'answer': TrackOptionDtoToJSON(value['answer']),
    };
}

