/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaGameExtrasVo } from './MetaGameExtrasVo';
import {
    MetaGameExtrasVoFromJSON,
    MetaGameExtrasVoFromJSONTyped,
    MetaGameExtrasVoToJSON,
    MetaGameExtrasVoToJSONTyped,
} from './MetaGameExtrasVo';
import type { GuessHistoryDto } from './GuessHistoryDto';
import {
    GuessHistoryDtoFromJSON,
    GuessHistoryDtoFromJSONTyped,
    GuessHistoryDtoToJSON,
    GuessHistoryDtoToJSONTyped,
} from './GuessHistoryDto';
import type { TrackOptionDto } from './TrackOptionDto';
import {
    TrackOptionDtoFromJSON,
    TrackOptionDtoFromJSONTyped,
    TrackOptionDtoToJSON,
    TrackOptionDtoToJSONTyped,
} from './TrackOptionDto';

/**
 * 
 * @export
 * @interface GameStateDto
 */
export interface GameStateDto {
    /**
     * The ID of the game session
     * @type {string}
     * @memberof GameStateDto
     */
    sessionId: string;
    /**
     * The current round of the game
     * @type {number}
     * @memberof GameStateDto
     */
    currentRound: number;
    /**
     * The duration of the current snippet
     * @type {number}
     * @memberof GameStateDto
     */
    snippetDuration: number;
    /**
     * The status of the game
     * @type {string}
     * @memberof GameStateDto
     */
    status: GameStateDtoStatusEnum;
    /**
     * The guesses of the game
     * @type {Array<GuessHistoryDto>}
     * @memberof GameStateDto
     */
    guesses: Array<GuessHistoryDto>;
    /**
     * The preview URL of the current track
     * @type {string}
     * @memberof GameStateDto
     */
    previewUrl: string;
    /**
     * The answer to the current track
     * @type {TrackOptionDto}
     * @memberof GameStateDto
     */
    answer?: TrackOptionDto;
    /**
     * Optional personalized rank title (easter egg for special users)
     * @type {string}
     * @memberof GameStateDto
     */
    rankTitle?: string;
    /**
     * Optional personalized note (easter egg for special users)
     * @type {string}
     * @memberof GameStateDto
     */
    specialNote?: string;
    /**
     * Optional win easter eggs
     * @type {MetaGameExtrasVo}
     * @memberof GameStateDto
     */
    meta?: MetaGameExtrasVo;
}


/**
 * @export
 */
export const GameStateDtoStatusEnum = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST'
} as const;
export type GameStateDtoStatusEnum = typeof GameStateDtoStatusEnum[keyof typeof GameStateDtoStatusEnum];


/**
 * Check if a given object implements the GameStateDto interface.
 */
export function instanceOfGameStateDto(value: object): value is GameStateDto {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('currentRound' in value) || value['currentRound'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('guesses' in value) || value['guesses'] === undefined) return false;
    if (!('previewUrl' in value) || value['previewUrl'] === undefined) return false;
    return true;
}

export function GameStateDtoFromJSON(json: any): GameStateDto {
    return GameStateDtoFromJSONTyped(json, false);
}

export function GameStateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'currentRound': json['currentRound'],
        'snippetDuration': json['snippetDuration'],
        'status': json['status'],
        'guesses': ((json['guesses'] as Array<any>).map(GuessHistoryDtoFromJSON)),
        'previewUrl': json['previewUrl'],
        'answer': json['answer'] == null ? undefined : TrackOptionDtoFromJSON(json['answer']),
        'rankTitle': json['rankTitle'] == null ? undefined : json['rankTitle'],
        'specialNote': json['specialNote'] == null ? undefined : json['specialNote'],
        'meta': json['meta'] == null ? undefined : MetaGameExtrasVoFromJSON(json['meta']),
    };
}

export function GameStateDtoToJSON(json: any): GameStateDto {
    return GameStateDtoToJSONTyped(json, false);
}

export function GameStateDtoToJSONTyped(value?: GameStateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'currentRound': value['currentRound'],
        'snippetDuration': value['snippetDuration'],
        'status': value['status'],
        'guesses': ((value['guesses'] as Array<any>).map(GuessHistoryDtoToJSON)),
        'previewUrl': value['previewUrl'],
        'answer': TrackOptionDtoToJSON(value['answer']),
        'rankTitle': value['rankTitle'],
        'specialNote': value['specialNote'],
        'meta': MetaGameExtrasVoToJSON(value['meta']),
    };
}

