/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuessHistoryDto } from './GuessHistoryDto';
import {
    GuessHistoryDtoFromJSON,
    GuessHistoryDtoFromJSONTyped,
    GuessHistoryDtoToJSON,
    GuessHistoryDtoToJSONTyped,
} from './GuessHistoryDto';

/**
 * 
 * @export
 * @interface GameHistoryEntryDto
 */
export interface GameHistoryEntryDto {
    /**
     * Game session ID
     * @type {string}
     * @memberof GameHistoryEntryDto
     */
    id: string;
    /**
     * Date (YYYY-MM-DD) from completedAt or createdAt
     * @type {string}
     * @memberof GameHistoryEntryDto
     */
    date: string;
    /**
     * Game status
     * @type {string}
     * @memberof GameHistoryEntryDto
     */
    status: GameHistoryEntryDtoStatusEnum;
    /**
     * Score 0-6, may be null if abandoned
     * @type {number}
     * @memberof GameHistoryEntryDto
     */
    score?: number;
    /**
     * The game mode
     * @type {string}
     * @memberof GameHistoryEntryDto
     */
    mode: GameHistoryEntryDtoModeEnum;
    /**
     * Guess history
     * @type {Array<GuessHistoryDto>}
     * @memberof GameHistoryEntryDto
     */
    guesses: Array<GuessHistoryDto>;
    /**
     * Track name (answer)
     * @type {string}
     * @memberof GameHistoryEntryDto
     */
    trackName: string;
    /**
     * Artist name
     * @type {string}
     * @memberof GameHistoryEntryDto
     */
    artistName: string;
    /**
     * Album image URL
     * @type {string}
     * @memberof GameHistoryEntryDto
     */
    albumImageUrl?: string;
}


/**
 * @export
 */
export const GameHistoryEntryDtoStatusEnum = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST',
    Abandoned: 'ABANDONED'
} as const;
export type GameHistoryEntryDtoStatusEnum = typeof GameHistoryEntryDtoStatusEnum[keyof typeof GameHistoryEntryDtoStatusEnum];

/**
 * @export
 */
export const GameHistoryEntryDtoModeEnum = {
    Daily: 'DAILY',
    All: 'ALL'
} as const;
export type GameHistoryEntryDtoModeEnum = typeof GameHistoryEntryDtoModeEnum[keyof typeof GameHistoryEntryDtoModeEnum];


/**
 * Check if a given object implements the GameHistoryEntryDto interface.
 */
export function instanceOfGameHistoryEntryDto(value: object): value is GameHistoryEntryDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('guesses' in value) || value['guesses'] === undefined) return false;
    if (!('trackName' in value) || value['trackName'] === undefined) return false;
    if (!('artistName' in value) || value['artistName'] === undefined) return false;
    return true;
}

export function GameHistoryEntryDtoFromJSON(json: any): GameHistoryEntryDto {
    return GameHistoryEntryDtoFromJSONTyped(json, false);
}

export function GameHistoryEntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameHistoryEntryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'date': json['date'],
        'status': json['status'],
        'score': json['score'] == null ? undefined : json['score'],
        'mode': json['mode'],
        'guesses': ((json['guesses'] as Array<any>).map(GuessHistoryDtoFromJSON)),
        'trackName': json['trackName'],
        'artistName': json['artistName'],
        'albumImageUrl': json['albumImageUrl'] == null ? undefined : json['albumImageUrl'],
    };
}

export function GameHistoryEntryDtoToJSON(json: any): GameHistoryEntryDto {
    return GameHistoryEntryDtoToJSONTyped(json, false);
}

export function GameHistoryEntryDtoToJSONTyped(value?: GameHistoryEntryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'date': value['date'],
        'status': value['status'],
        'score': value['score'],
        'mode': value['mode'],
        'guesses': ((value['guesses'] as Array<any>).map(GuessHistoryDtoToJSON)),
        'trackName': value['trackName'],
        'artistName': value['artistName'],
        'albumImageUrl': value['albumImageUrl'],
    };
}

