/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GameStatus = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST',
    Abandoned: 'ABANDONED'
} as const;
export type GameStatus = typeof GameStatus[keyof typeof GameStatus];


export function instanceOfGameStatus(value: any): boolean {
    for (const key in GameStatus) {
        if (Object.prototype.hasOwnProperty.call(GameStatus, key)) {
            if (GameStatus[key as keyof typeof GameStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GameStatusFromJSON(json: any): GameStatus {
    return GameStatusFromJSONTyped(json, false);
}

export function GameStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStatus {
    return json as GameStatus;
}

export function GameStatusToJSON(value?: GameStatus | null): any {
    return value as any;
}

export function GameStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): GameStatus {
    return value as GameStatus;
}

