/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * The backend for the Spotify guessing game
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GameStateDtoMeta
 */
export interface GameStateDtoMeta {
    /**
     * 
     * @type {boolean}
     * @memberof GameStateDtoMeta
     */
    showHeart?: boolean;
}

/**
 * Check if a given object implements the GameStateDtoMeta interface.
 */
export function instanceOfGameStateDtoMeta(value: object): value is GameStateDtoMeta {
    return true;
}

export function GameStateDtoMetaFromJSON(json: any): GameStateDtoMeta {
    return GameStateDtoMetaFromJSONTyped(json, false);
}

export function GameStateDtoMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStateDtoMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'showHeart': json['showHeart'] == null ? undefined : json['showHeart'],
    };
}

export function GameStateDtoMetaToJSON(json: any): GameStateDtoMeta {
    return GameStateDtoMetaToJSONTyped(json, false);
}

export function GameStateDtoMetaToJSONTyped(value?: GameStateDtoMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'showHeart': value['showHeart'],
    };
}

