/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActualTrackDto } from './ActualTrackDto';
import {
    ActualTrackDtoFromJSON,
    ActualTrackDtoFromJSONTyped,
    ActualTrackDtoToJSON,
    ActualTrackDtoToJSONTyped,
} from './ActualTrackDto';

/**
 * 
 * @export
 * @interface GauntletGuessResultDto
 */
export interface GauntletGuessResultDto {
    /**
     * Whether the guess was correct
     * @type {boolean}
     * @memberof GauntletGuessResultDto
     */
    correct: boolean;
    /**
     * Whether the run is over (wrong guess or skip)
     * @type {boolean}
     * @memberof GauntletGuessResultDto
     */
    runOver: boolean;
    /**
     * Current score (consecutive correct guesses)
     * @type {number}
     * @memberof GauntletGuessResultDto
     */
    score: number;
    /**
     * Status of the run after this guess
     * @type {string}
     * @memberof GauntletGuessResultDto
     */
    status: GauntletGuessResultDtoStatusEnum;
    /**
     * The actual track that was being guessed (always revealed)
     * @type {ActualTrackDto}
     * @memberof GauntletGuessResultDto
     */
    actualTrack?: ActualTrackDto;
    /**
     * Preview URL for the next track (if run continues)
     * @type {string}
     * @memberof GauntletGuessResultDto
     */
    nextPreviewUrl?: string;
    /**
     * Snippet duration in seconds for the next track
     * @type {number}
     * @memberof GauntletGuessResultDto
     */
    nextSnippetDuration?: number;
    /**
     * Whether this score is a new all-time personal best (set when run ends)
     * @type {boolean}
     * @memberof GauntletGuessResultDto
     */
    isNewPersonalBest?: boolean;
    /**
     * Whether this score is a new daily best (set when run ends)
     * @type {boolean}
     * @memberof GauntletGuessResultDto
     */
    isNewDailyBest?: boolean;
}


/**
 * @export
 */
export const GauntletGuessResultDtoStatusEnum = {
    Playing: 'PLAYING',
    Ended: 'ENDED'
} as const;
export type GauntletGuessResultDtoStatusEnum = typeof GauntletGuessResultDtoStatusEnum[keyof typeof GauntletGuessResultDtoStatusEnum];


/**
 * Check if a given object implements the GauntletGuessResultDto interface.
 */
export function instanceOfGauntletGuessResultDto(value: object): value is GauntletGuessResultDto {
    if (!('correct' in value) || value['correct'] === undefined) return false;
    if (!('runOver' in value) || value['runOver'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function GauntletGuessResultDtoFromJSON(json: any): GauntletGuessResultDto {
    return GauntletGuessResultDtoFromJSONTyped(json, false);
}

export function GauntletGuessResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GauntletGuessResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'correct': json['correct'],
        'runOver': json['runOver'],
        'score': json['score'],
        'status': json['status'],
        'actualTrack': json['actualTrack'] == null ? undefined : ActualTrackDtoFromJSON(json['actualTrack']),
        'nextPreviewUrl': json['nextPreviewUrl'] == null ? undefined : json['nextPreviewUrl'],
        'nextSnippetDuration': json['nextSnippetDuration'] == null ? undefined : json['nextSnippetDuration'],
        'isNewPersonalBest': json['isNewPersonalBest'] == null ? undefined : json['isNewPersonalBest'],
        'isNewDailyBest': json['isNewDailyBest'] == null ? undefined : json['isNewDailyBest'],
    };
}

export function GauntletGuessResultDtoToJSON(json: any): GauntletGuessResultDto {
    return GauntletGuessResultDtoToJSONTyped(json, false);
}

export function GauntletGuessResultDtoToJSONTyped(value?: GauntletGuessResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'correct': value['correct'],
        'runOver': value['runOver'],
        'score': value['score'],
        'status': value['status'],
        'actualTrack': ActualTrackDtoToJSON(value['actualTrack']),
        'nextPreviewUrl': value['nextPreviewUrl'],
        'nextSnippetDuration': value['nextSnippetDuration'],
        'isNewPersonalBest': value['isNewPersonalBest'],
        'isNewDailyBest': value['isNewDailyBest'],
    };
}

