/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GauntletLeaderboardEntryDto } from './GauntletLeaderboardEntryDto';
import {
    GauntletLeaderboardEntryDtoFromJSON,
    GauntletLeaderboardEntryDtoFromJSONTyped,
    GauntletLeaderboardEntryDtoToJSON,
    GauntletLeaderboardEntryDtoToJSONTyped,
} from './GauntletLeaderboardEntryDto';
import type { GauntletUserLeaderboardEntryDto } from './GauntletUserLeaderboardEntryDto';
import {
    GauntletUserLeaderboardEntryDtoFromJSON,
    GauntletUserLeaderboardEntryDtoFromJSONTyped,
    GauntletUserLeaderboardEntryDtoToJSON,
    GauntletUserLeaderboardEntryDtoToJSONTyped,
} from './GauntletUserLeaderboardEntryDto';

/**
 * 
 * @export
 * @interface GauntletLeaderboardDto
 */
export interface GauntletLeaderboardDto {
    /**
     * 
     * @type {Array<GauntletLeaderboardEntryDto>}
     * @memberof GauntletLeaderboardDto
     */
    entries: Array<GauntletLeaderboardEntryDto>;
    /**
     * Requesting user's leaderboard position
     * @type {GauntletUserLeaderboardEntryDto}
     * @memberof GauntletLeaderboardDto
     */
    userEntry?: GauntletUserLeaderboardEntryDto;
    /**
     * The period this leaderboard covers
     * @type {string}
     * @memberof GauntletLeaderboardDto
     */
    period: GauntletLeaderboardDtoPeriodEnum;
}


/**
 * @export
 */
export const GauntletLeaderboardDtoPeriodEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Alltime: 'alltime'
} as const;
export type GauntletLeaderboardDtoPeriodEnum = typeof GauntletLeaderboardDtoPeriodEnum[keyof typeof GauntletLeaderboardDtoPeriodEnum];


/**
 * Check if a given object implements the GauntletLeaderboardDto interface.
 */
export function instanceOfGauntletLeaderboardDto(value: object): value is GauntletLeaderboardDto {
    if (!('entries' in value) || value['entries'] === undefined) return false;
    if (!('period' in value) || value['period'] === undefined) return false;
    return true;
}

export function GauntletLeaderboardDtoFromJSON(json: any): GauntletLeaderboardDto {
    return GauntletLeaderboardDtoFromJSONTyped(json, false);
}

export function GauntletLeaderboardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GauntletLeaderboardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'entries': ((json['entries'] as Array<any>).map(GauntletLeaderboardEntryDtoFromJSON)),
        'userEntry': json['userEntry'] == null ? undefined : GauntletUserLeaderboardEntryDtoFromJSON(json['userEntry']),
        'period': json['period'],
    };
}

export function GauntletLeaderboardDtoToJSON(json: any): GauntletLeaderboardDto {
    return GauntletLeaderboardDtoToJSONTyped(json, false);
}

export function GauntletLeaderboardDtoToJSONTyped(value?: GauntletLeaderboardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entries': ((value['entries'] as Array<any>).map(GauntletLeaderboardEntryDtoToJSON)),
        'userEntry': GauntletUserLeaderboardEntryDtoToJSON(value['userEntry']),
        'period': value['period'],
    };
}

