/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GauntletRunStateDto
 */
export interface GauntletRunStateDto {
    /**
     * The gauntlet run ID
     * @type {string}
     * @memberof GauntletRunStateDto
     */
    runId: string;
    /**
     * Current score (consecutive correct guesses)
     * @type {number}
     * @memberof GauntletRunStateDto
     */
    score: number;
    /**
     * Status of the run
     * @type {string}
     * @memberof GauntletRunStateDto
     */
    status: GauntletRunStateDtoStatusEnum;
    /**
     * Difficulty level of the run
     * @type {string}
     * @memberof GauntletRunStateDto
     */
    difficulty: GauntletRunStateDtoDifficultyEnum;
    /**
     * Preview URL for the current track
     * @type {string}
     * @memberof GauntletRunStateDto
     */
    previewUrl: string;
    /**
     * Snippet duration in seconds for the current track
     * @type {number}
     * @memberof GauntletRunStateDto
     */
    snippetDuration: number;
}


/**
 * @export
 */
export const GauntletRunStateDtoStatusEnum = {
    Playing: 'PLAYING',
    Ended: 'ENDED'
} as const;
export type GauntletRunStateDtoStatusEnum = typeof GauntletRunStateDtoStatusEnum[keyof typeof GauntletRunStateDtoStatusEnum];

/**
 * @export
 */
export const GauntletRunStateDtoDifficultyEnum = {
    Easy: 'EASY',
    Medium: 'MEDIUM',
    Hard: 'HARD',
    Expert: 'EXPERT'
} as const;
export type GauntletRunStateDtoDifficultyEnum = typeof GauntletRunStateDtoDifficultyEnum[keyof typeof GauntletRunStateDtoDifficultyEnum];


/**
 * Check if a given object implements the GauntletRunStateDto interface.
 */
export function instanceOfGauntletRunStateDto(value: object): value is GauntletRunStateDto {
    if (!('runId' in value) || value['runId'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    if (!('previewUrl' in value) || value['previewUrl'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    return true;
}

export function GauntletRunStateDtoFromJSON(json: any): GauntletRunStateDto {
    return GauntletRunStateDtoFromJSONTyped(json, false);
}

export function GauntletRunStateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GauntletRunStateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'runId': json['runId'],
        'score': json['score'],
        'status': json['status'],
        'difficulty': json['difficulty'],
        'previewUrl': json['previewUrl'],
        'snippetDuration': json['snippetDuration'],
    };
}

export function GauntletRunStateDtoToJSON(json: any): GauntletRunStateDto {
    return GauntletRunStateDtoToJSONTyped(json, false);
}

export function GauntletRunStateDtoToJSONTyped(value?: GauntletRunStateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'runId': value['runId'],
        'score': value['score'],
        'status': value['status'],
        'difficulty': value['difficulty'],
        'previewUrl': value['previewUrl'],
        'snippetDuration': value['snippetDuration'],
    };
}

