/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GauntletUserLeaderboardEntryDto
 */
export interface GauntletUserLeaderboardEntryDto {
    /**
     * Rank position (1-based)
     * @type {number}
     * @memberof GauntletUserLeaderboardEntryDto
     */
    rank: number;
    /**
     * Best score in the period
     * @type {number}
     * @memberof GauntletUserLeaderboardEntryDto
     */
    score: number;
}

/**
 * Check if a given object implements the GauntletUserLeaderboardEntryDto interface.
 */
export function instanceOfGauntletUserLeaderboardEntryDto(value: object): value is GauntletUserLeaderboardEntryDto {
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function GauntletUserLeaderboardEntryDtoFromJSON(json: any): GauntletUserLeaderboardEntryDto {
    return GauntletUserLeaderboardEntryDtoFromJSONTyped(json, false);
}

export function GauntletUserLeaderboardEntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GauntletUserLeaderboardEntryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'],
        'score': json['score'],
    };
}

export function GauntletUserLeaderboardEntryDtoToJSON(json: any): GauntletUserLeaderboardEntryDto {
    return GauntletUserLeaderboardEntryDtoToJSONTyped(json, false);
}

export function GauntletUserLeaderboardEntryDtoToJSONTyped(value?: GauntletUserLeaderboardEntryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'score': value['score'],
    };
}

