/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GauntletHistorySummaryDto } from './GauntletHistorySummaryDto';
import {
    GauntletHistorySummaryDtoFromJSON,
    GauntletHistorySummaryDtoFromJSONTyped,
    GauntletHistorySummaryDtoToJSON,
    GauntletHistorySummaryDtoToJSONTyped,
} from './GauntletHistorySummaryDto';
import type { GauntletHistoryMetaDto } from './GauntletHistoryMetaDto';
import {
    GauntletHistoryMetaDtoFromJSON,
    GauntletHistoryMetaDtoFromJSONTyped,
    GauntletHistoryMetaDtoToJSON,
    GauntletHistoryMetaDtoToJSONTyped,
} from './GauntletHistoryMetaDto';
import type { GauntletHistoryEntryDto } from './GauntletHistoryEntryDto';
import {
    GauntletHistoryEntryDtoFromJSON,
    GauntletHistoryEntryDtoFromJSONTyped,
    GauntletHistoryEntryDtoToJSON,
    GauntletHistoryEntryDtoToJSONTyped,
} from './GauntletHistoryEntryDto';

/**
 * 
 * @export
 * @interface GauntletHistoryDto
 */
export interface GauntletHistoryDto {
    /**
     * 
     * @type {Array<GauntletHistoryEntryDto>}
     * @memberof GauntletHistoryDto
     */
    items: Array<GauntletHistoryEntryDto>;
    /**
     * 
     * @type {GauntletHistoryMetaDto}
     * @memberof GauntletHistoryDto
     */
    meta: GauntletHistoryMetaDto;
    /**
     * 
     * @type {GauntletHistorySummaryDto}
     * @memberof GauntletHistoryDto
     */
    summary: GauntletHistorySummaryDto;
}

/**
 * Check if a given object implements the GauntletHistoryDto interface.
 */
export function instanceOfGauntletHistoryDto(value: object): value is GauntletHistoryDto {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    return true;
}

export function GauntletHistoryDtoFromJSON(json: any): GauntletHistoryDto {
    return GauntletHistoryDtoFromJSONTyped(json, false);
}

export function GauntletHistoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GauntletHistoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GauntletHistoryEntryDtoFromJSON)),
        'meta': GauntletHistoryMetaDtoFromJSON(json['meta']),
        'summary': GauntletHistorySummaryDtoFromJSON(json['summary']),
    };
}

export function GauntletHistoryDtoToJSON(json: any): GauntletHistoryDto {
    return GauntletHistoryDtoToJSONTyped(json, false);
}

export function GauntletHistoryDtoToJSONTyped(value?: GauntletHistoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(GauntletHistoryEntryDtoToJSON)),
        'meta': GauntletHistoryMetaDtoToJSON(value['meta']),
        'summary': GauntletHistorySummaryDtoToJSON(value['summary']),
    };
}

