/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GauntletLeaderboardEntryDto
 */
export interface GauntletLeaderboardEntryDto {
    /**
     * Rank position (1-based)
     * @type {number}
     * @memberof GauntletLeaderboardEntryDto
     */
    rank: number;
    /**
     * User ID. Opaque placeholder for a hidden entry, so the row cannot be traced back to a player.
     * @type {string}
     * @memberof GauntletLeaderboardEntryDto
     */
    userId: string;
    /**
     * User display name
     * @type {string}
     * @memberof GauntletLeaderboardEntryDto
     */
    displayName: string;
    /**
     * This player chose not to be named on the leaderboard
     * @type {boolean}
     * @memberof GauntletLeaderboardEntryDto
     */
    isHidden: boolean;
    /**
     * User avatar URL
     * @type {string}
     * @memberof GauntletLeaderboardEntryDto
     */
    avatarUrl?: string;
    /**
     * Best score achieved in the period
     * @type {number}
     * @memberof GauntletLeaderboardEntryDto
     */
    score: number;
}

/**
 * Check if a given object implements the GauntletLeaderboardEntryDto interface.
 */
export function instanceOfGauntletLeaderboardEntryDto(value: object): value is GauntletLeaderboardEntryDto {
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('isHidden' in value) || value['isHidden'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function GauntletLeaderboardEntryDtoFromJSON(json: any): GauntletLeaderboardEntryDto {
    return GauntletLeaderboardEntryDtoFromJSONTyped(json, false);
}

export function GauntletLeaderboardEntryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GauntletLeaderboardEntryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'rank': json['rank'],
        'userId': json['userId'],
        'displayName': json['displayName'],
        'isHidden': json['isHidden'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'score': json['score'],
    };
}

export function GauntletLeaderboardEntryDtoToJSON(json: any): GauntletLeaderboardEntryDto {
    return GauntletLeaderboardEntryDtoToJSONTyped(json, false);
}

export function GauntletLeaderboardEntryDtoToJSONTyped(value?: GauntletLeaderboardEntryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rank': value['rank'],
        'userId': value['userId'],
        'displayName': value['displayName'],
        'isHidden': value['isHidden'],
        'avatarUrl': value['avatarUrl'],
        'score': value['score'],
    };
}

