/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLeaderboardDto
 */
export interface GetLeaderboardDto {
    /**
     * Time period for the leaderboard
     * @type {string}
     * @memberof GetLeaderboardDto
     */
    period?: GetLeaderboardDtoPeriodEnum;
    /**
     * 
     * @type {number}
     * @memberof GetLeaderboardDto
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof GetLeaderboardDto
     */
    offset?: number;
}


/**
 * @export
 */
export const GetLeaderboardDtoPeriodEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Alltime: 'alltime'
} as const;
export type GetLeaderboardDtoPeriodEnum = typeof GetLeaderboardDtoPeriodEnum[keyof typeof GetLeaderboardDtoPeriodEnum];


/**
 * Check if a given object implements the GetLeaderboardDto interface.
 */
export function instanceOfGetLeaderboardDto(value: object): value is GetLeaderboardDto {
    return true;
}

export function GetLeaderboardDtoFromJSON(json: any): GetLeaderboardDto {
    return GetLeaderboardDtoFromJSONTyped(json, false);
}

export function GetLeaderboardDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLeaderboardDto {
    if (json == null) {
        return json;
    }
    return {
        
        'period': json['period'] == null ? undefined : json['period'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function GetLeaderboardDtoToJSON(json: any): GetLeaderboardDto {
    return GetLeaderboardDtoToJSONTyped(json, false);
}

export function GetLeaderboardDtoToJSONTyped(value?: GetLeaderboardDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'period': value['period'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

