/* tslint:disable */
 
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatsDto
 */
export interface GetStatsDto {
    /**
     * The game mode
     * @type {string}
     * @memberof GetStatsDto
     */
    mode: GetStatsDtoModeEnum;
}


/**
 * @export
 */
export const GetStatsDtoModeEnum = {
    Daily: 'DAILY',
    All: 'ALL'
} as const;
export type GetStatsDtoModeEnum = typeof GetStatsDtoModeEnum[keyof typeof GetStatsDtoModeEnum];


/**
 * Check if a given object implements the GetStatsDto interface.
 */
export function instanceOfGetStatsDto(value: object): value is GetStatsDto {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function GetStatsDtoFromJSON(json: any): GetStatsDto {
    return GetStatsDtoFromJSONTyped(json, false);
}

export function GetStatsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
    };
}

export function GetStatsDtoToJSON(json: any): GetStatsDto {
    return GetStatsDtoToJSONTyped(json, false);
}

export function GetStatsDtoToJSONTyped(value?: GetStatsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
    };
}

