/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuessResultDto
 */
export interface GuessResultDto {
    /**
     * The result of the guess
     * @type {string}
     * @memberof GuessResultDto
     */
    result: GuessResultDtoResultEnum;
    /**
     * 
     * @type {boolean}
     * @memberof GuessResultDto
     */
    gameOver: boolean;
    /**
     * 
     * @type {string}
     * @memberof GuessResultDto
     */
    status: GuessResultDtoStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof GuessResultDto
     */
    currentRound: number;
    /**
     * 
     * @type {number}
     * @memberof GuessResultDto
     */
    snippetDuration: number;
}


/**
 * @export
 */
export const GuessResultDtoResultEnum = {
    Correct: 'CORRECT',
    Artist: 'ARTIST',
    Wrong: 'WRONG',
    Skip: 'SKIP'
} as const;
export type GuessResultDtoResultEnum = typeof GuessResultDtoResultEnum[keyof typeof GuessResultDtoResultEnum];

/**
 * @export
 */
export const GuessResultDtoStatusEnum = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST'
} as const;
export type GuessResultDtoStatusEnum = typeof GuessResultDtoStatusEnum[keyof typeof GuessResultDtoStatusEnum];


/**
 * Check if a given object implements the GuessResultDto interface.
 */
export function instanceOfGuessResultDto(value: object): value is GuessResultDto {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('gameOver' in value) || value['gameOver'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('currentRound' in value) || value['currentRound'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    return true;
}

export function GuessResultDtoFromJSON(json: any): GuessResultDto {
    return GuessResultDtoFromJSONTyped(json, false);
}

export function GuessResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuessResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'],
        'gameOver': json['gameOver'],
        'status': json['status'],
        'currentRound': json['currentRound'],
        'snippetDuration': json['snippetDuration'],
    };
}

export function GuessResultDtoToJSON(json: any): GuessResultDto {
    return GuessResultDtoToJSONTyped(json, false);
}

export function GuessResultDtoToJSONTyped(value?: GuessResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': value['result'],
        'gameOver': value['gameOver'],
        'status': value['status'],
        'currentRound': value['currentRound'],
        'snippetDuration': value['snippetDuration'],
    };
}

