/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GuessResult = {
    Correct: 'CORRECT',
    Artist: 'ARTIST',
    Album: 'ALBUM',
    Wrong: 'WRONG',
    Skip: 'SKIP',
    ArtistAndAlbum: 'ARTIST_AND_ALBUM'
} as const;
export type GuessResult = typeof GuessResult[keyof typeof GuessResult];


export function instanceOfGuessResult(value: any): boolean {
    for (const key in GuessResult) {
        if (Object.prototype.hasOwnProperty.call(GuessResult, key)) {
            if (GuessResult[key as keyof typeof GuessResult] === value) {
                return true;
            }
        }
    }
    return false;
}

export function GuessResultFromJSON(json: any): GuessResult {
    return GuessResultFromJSONTyped(json, false);
}

export function GuessResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuessResult {
    return json as GuessResult;
}

export function GuessResultToJSON(value?: GuessResult | null): any {
    return value as any;
}

export function GuessResultToJSONTyped(value: any, ignoreDiscriminator: boolean): GuessResult {
    return value as GuessResult;
}

