/* tslint:disable */
 
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuessDto
 */
export interface GuessDto {
    /**
     * The ID of the track to guess
     * @type {string}
     * @memberof GuessDto
     */
    trackId?: string;
    /**
     * Whether the current guess is a skip
     * @type {boolean}
     * @memberof GuessDto
     */
    skip?: boolean;
    /**
     * Track name
     * @type {string}
     * @memberof GuessDto
     */
    trackName?: string;
    /**
     * Artist name
     * @type {string}
     * @memberof GuessDto
     */
    artistName?: string;
    /**
     * Album name
     * @type {string}
     * @memberof GuessDto
     */
    albumName?: string;
}

/**
 * Check if a given object implements the GuessDto interface.
 */
export function instanceOfGuessDto(value: object): value is GuessDto {
    return true;
}

export function GuessDtoFromJSON(json: any): GuessDto {
    return GuessDtoFromJSONTyped(json, false);
}

export function GuessDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuessDto {
    if (json == null) {
        return json;
    }
    return {
        
        'trackId': json['trackId'] == null ? undefined : json['trackId'],
        'skip': json['skip'] == null ? undefined : json['skip'],
        'trackName': json['trackName'] == null ? undefined : json['trackName'],
        'artistName': json['artistName'] == null ? undefined : json['artistName'],
        'albumName': json['albumName'] == null ? undefined : json['albumName'],
    };
}

export function GuessDtoToJSON(json: any): GuessDto {
    return GuessDtoToJSONTyped(json, false);
}

export function GuessDtoToJSONTyped(value?: GuessDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trackId': value['trackId'],
        'skip': value['skip'],
        'trackName': value['trackName'],
        'artistName': value['artistName'],
        'albumName': value['albumName'],
    };
}

