/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KickPlayerDto
 */
export interface KickPlayerDto {
    /**
     * The player to remove from the room
     * @type {string}
     * @memberof KickPlayerDto
     */
    userId: string;
}

/**
 * Check if a given object implements the KickPlayerDto interface.
 */
export function instanceOfKickPlayerDto(value: object): value is KickPlayerDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function KickPlayerDtoFromJSON(json: any): KickPlayerDto {
    return KickPlayerDtoFromJSONTyped(json, false);
}

export function KickPlayerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): KickPlayerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function KickPlayerDtoToJSON(json: any): KickPlayerDto {
    return KickPlayerDtoToJSONTyped(json, false);
}

export function KickPlayerDtoToJSONTyped(value?: KickPlayerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

