/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LastfmDataVo
 */
export interface LastfmDataVo {
    /**
     * List of tags associated with the track
     * @type {Array<string>}
     * @memberof LastfmDataVo
     */
    tags: Array<string>;
    /**
     * Number of times the track has been played
     * @type {number}
     * @memberof LastfmDataVo
     */
    playcount?: number;
    /**
     * Timestamp of when the data was fetched
     * @type {string}
     * @memberof LastfmDataVo
     */
    fetchedAt: string;
}

/**
 * Check if a given object implements the LastfmDataVo interface.
 */
export function instanceOfLastfmDataVo(value: object): value is LastfmDataVo {
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('fetchedAt' in value) || value['fetchedAt'] === undefined) return false;
    return true;
}

export function LastfmDataVoFromJSON(json: any): LastfmDataVo {
    return LastfmDataVoFromJSONTyped(json, false);
}

export function LastfmDataVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LastfmDataVo {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'],
        'playcount': json['playcount'] == null ? undefined : json['playcount'],
        'fetchedAt': json['fetchedAt'],
    };
}

export function LastfmDataVoToJSON(json: any): LastfmDataVo {
    return LastfmDataVoToJSONTyped(json, false);
}

export function LastfmDataVoToJSONTyped(value?: LastfmDataVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'],
        'playcount': value['playcount'],
        'fetchedAt': value['fetchedAt'],
    };
}

