/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface MetaGameExtrasVo
 */
export interface MetaGameExtrasVo {
  /**
   * Show this emoji on the win screen
   * @type {string}
   * @memberof MetaGameExtrasVo
   */
  winEmoji: string;
}

/**
 * Check if a given object implements the MetaGameExtrasVo interface.
 */
export function instanceOfMetaGameExtrasVo(
  value: object,
): value is MetaGameExtrasVo {
  if (!('winEmoji' in value) || value['winEmoji'] === undefined) return false;
  return true;
}

export function MetaGameExtrasVoFromJSON(json: any): MetaGameExtrasVo {
  return MetaGameExtrasVoFromJSONTyped(json, false);
}

export function MetaGameExtrasVoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): MetaGameExtrasVo {
  if (json == null) {
    return json;
  }
  return {
    winEmoji: json['winEmoji'],
  };
}

export function MetaGameExtrasVoToJSON(json: any): MetaGameExtrasVo {
  return MetaGameExtrasVoToJSONTyped(json, false);
}

export function MetaGameExtrasVoToJSONTyped(
  value?: MetaGameExtrasVo | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    winEmoji: value['winEmoji'],
  };
}
