/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuessHistoryDto } from './GuessHistoryDto';
import {
    GuessHistoryDtoFromJSON,
    GuessHistoryDtoFromJSONTyped,
    GuessHistoryDtoToJSON,
    GuessHistoryDtoToJSONTyped,
} from './GuessHistoryDto';
import type { TrackOptionDto } from './TrackOptionDto';
import {
    TrackOptionDtoFromJSON,
    TrackOptionDtoFromJSONTyped,
    TrackOptionDtoToJSON,
    TrackOptionDtoToJSONTyped,
} from './TrackOptionDto';

/**
 * 
 * @export
 * @interface MultiplayerRoundStateDto
 */
export interface MultiplayerRoundStateDto {
    /**
     * The game session ID for this round
     * @type {string}
     * @memberof MultiplayerRoundStateDto
     */
    sessionId: string;
    /**
     * Room round index (0-based)
     * @type {number}
     * @memberof MultiplayerRoundStateDto
     */
    roundIndex: number;
    /**
     * Total rounds in the room
     * @type {number}
     * @memberof MultiplayerRoundStateDto
     */
    totalRounds: number;
    /**
     * Guess count within this round
     * @type {number}
     * @memberof MultiplayerRoundStateDto
     */
    currentGuess: number;
    /**
     * Snippet duration for the current guess
     * @type {number}
     * @memberof MultiplayerRoundStateDto
     */
    snippetDuration: number;
    /**
     * 
     * @type {string}
     * @memberof MultiplayerRoundStateDto
     */
    status: MultiplayerRoundStateDtoStatusEnum;
    /**
     * 
     * @type {Array<GuessHistoryDto>}
     * @memberof MultiplayerRoundStateDto
     */
    guesses: Array<GuessHistoryDto>;
    /**
     * Track preview URL
     * @type {string}
     * @memberof MultiplayerRoundStateDto
     */
    previewUrl: string;
    /**
     * Answer (only when round is complete)
     * @type {TrackOptionDto}
     * @memberof MultiplayerRoundStateDto
     */
    answer?: TrackOptionDto;
}


/**
 * @export
 */
export const MultiplayerRoundStateDtoStatusEnum = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST',
    Abandoned: 'ABANDONED'
} as const;
export type MultiplayerRoundStateDtoStatusEnum = typeof MultiplayerRoundStateDtoStatusEnum[keyof typeof MultiplayerRoundStateDtoStatusEnum];


/**
 * Check if a given object implements the MultiplayerRoundStateDto interface.
 */
export function instanceOfMultiplayerRoundStateDto(value: object): value is MultiplayerRoundStateDto {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('roundIndex' in value) || value['roundIndex'] === undefined) return false;
    if (!('totalRounds' in value) || value['totalRounds'] === undefined) return false;
    if (!('currentGuess' in value) || value['currentGuess'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('guesses' in value) || value['guesses'] === undefined) return false;
    if (!('previewUrl' in value) || value['previewUrl'] === undefined) return false;
    return true;
}

export function MultiplayerRoundStateDtoFromJSON(json: any): MultiplayerRoundStateDto {
    return MultiplayerRoundStateDtoFromJSONTyped(json, false);
}

export function MultiplayerRoundStateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiplayerRoundStateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'roundIndex': json['roundIndex'],
        'totalRounds': json['totalRounds'],
        'currentGuess': json['currentGuess'],
        'snippetDuration': json['snippetDuration'],
        'status': json['status'],
        'guesses': ((json['guesses'] as Array<any>).map(GuessHistoryDtoFromJSON)),
        'previewUrl': json['previewUrl'],
        'answer': json['answer'] == null ? undefined : TrackOptionDtoFromJSON(json['answer']),
    };
}

export function MultiplayerRoundStateDtoToJSON(json: any): MultiplayerRoundStateDto {
    return MultiplayerRoundStateDtoToJSONTyped(json, false);
}

export function MultiplayerRoundStateDtoToJSONTyped(value?: MultiplayerRoundStateDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'roundIndex': value['roundIndex'],
        'totalRounds': value['totalRounds'],
        'currentGuess': value['currentGuess'],
        'snippetDuration': value['snippetDuration'],
        'status': value['status'],
        'guesses': ((value['guesses'] as Array<any>).map(GuessHistoryDtoToJSON)),
        'previewUrl': value['previewUrl'],
        'answer': TrackOptionDtoToJSON(value['answer']),
    };
}

