/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PasswordResetResultDto
 */
export interface PasswordResetResultDto {
    /**
     * Whether the link was live. False covers wrong, expired and already used alike.
     * @type {boolean}
     * @memberof PasswordResetResultDto
     */
    reset: boolean;
}

/**
 * Check if a given object implements the PasswordResetResultDto interface.
 */
export function instanceOfPasswordResetResultDto(value: object): value is PasswordResetResultDto {
    if (!('reset' in value) || value['reset'] === undefined) return false;
    return true;
}

export function PasswordResetResultDtoFromJSON(json: any): PasswordResetResultDto {
    return PasswordResetResultDtoFromJSONTyped(json, false);
}

export function PasswordResetResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PasswordResetResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'reset': json['reset'],
    };
}

export function PasswordResetResultDtoToJSON(json: any): PasswordResetResultDto {
    return PasswordResetResultDtoToJSONTyped(json, false);
}

export function PasswordResetResultDtoToJSONTyped(value?: PasswordResetResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reset': value['reset'],
    };
}

