/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PersonalBestDto
 */
export interface PersonalBestDto {
    /**
     * The user's personal best gauntlet score
     * @type {number}
     * @memberof PersonalBestDto
     */
    personalBest: number;
}

/**
 * Check if a given object implements the PersonalBestDto interface.
 */
export function instanceOfPersonalBestDto(value: object): value is PersonalBestDto {
    if (!('personalBest' in value) || value['personalBest'] === undefined) return false;
    return true;
}

export function PersonalBestDtoFromJSON(json: any): PersonalBestDto {
    return PersonalBestDtoFromJSONTyped(json, false);
}

export function PersonalBestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalBestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'personalBest': json['personalBest'],
    };
}

export function PersonalBestDtoToJSON(json: any): PersonalBestDto {
    return PersonalBestDtoToJSONTyped(json, false);
}

export function PersonalBestDtoToJSONTyped(value?: PersonalBestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'personalBest': value['personalBest'],
    };
}

