/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PlayedTodayDto
 */
export interface PlayedTodayDto {
  /**
   * Whether the user has played today's daily
   * @type {boolean}
   * @memberof PlayedTodayDto
   */
  playedToday: boolean;
}

/**
 * Check if a given object implements the PlayedTodayDto interface.
 */
export function instanceOfPlayedTodayDto(
  value: object,
): value is PlayedTodayDto {
  if (!('playedToday' in value) || value['playedToday'] === undefined)
    return false;
  return true;
}

export function PlayedTodayDtoFromJSON(json: any): PlayedTodayDto {
  return PlayedTodayDtoFromJSONTyped(json, false);
}

export function PlayedTodayDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlayedTodayDto {
  if (json == null) {
    return json;
  }
  return {
    playedToday: json['playedToday'],
  };
}

export function PlayedTodayDtoToJSON(json: any): PlayedTodayDto {
  return PlayedTodayDtoToJSONTyped(json, false);
}

export function PlayedTodayDtoToJSONTyped(
  value?: PlayedTodayDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    playedToday: value['playedToday'],
  };
}
