/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaylistDto } from './PlaylistDto';
import {
  PlaylistDtoFromJSON,
  PlaylistDtoFromJSONTyped,
  PlaylistDtoToJSON,
  PlaylistDtoToJSONTyped,
} from './PlaylistDto';

/**
 *
 * @export
 * @interface PlaylistsResponseDto
 */
export interface PlaylistsResponseDto {
  /**
   * The playlists
   * @type {Array<PlaylistDto>}
   * @memberof PlaylistsResponseDto
   */
  items: Array<PlaylistDto>;
  /**
   * The total number of playlists
   * @type {number}
   * @memberof PlaylistsResponseDto
   */
  total: number;
  /**
   * The limit of the playlists
   * @type {number}
   * @memberof PlaylistsResponseDto
   */
  limit: number;
  /**
   * The offset of the playlists
   * @type {number}
   * @memberof PlaylistsResponseDto
   */
  offset: number;
}

/**
 * Check if a given object implements the PlaylistsResponseDto interface.
 */
export function instanceOfPlaylistsResponseDto(
  value: object,
): value is PlaylistsResponseDto {
  if (!('items' in value) || value['items'] === undefined) return false;
  if (!('total' in value) || value['total'] === undefined) return false;
  if (!('limit' in value) || value['limit'] === undefined) return false;
  if (!('offset' in value) || value['offset'] === undefined) return false;
  return true;
}

export function PlaylistsResponseDtoFromJSON(json: any): PlaylistsResponseDto {
  return PlaylistsResponseDtoFromJSONTyped(json, false);
}

export function PlaylistsResponseDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PlaylistsResponseDto {
  if (json == null) {
    return json;
  }
  return {
    items: (json['items'] as Array<any>).map(PlaylistDtoFromJSON),
    total: json['total'],
    limit: json['limit'],
    offset: json['offset'],
  };
}

export function PlaylistsResponseDtoToJSON(json: any): PlaylistsResponseDto {
  return PlaylistsResponseDtoToJSONTyped(json, false);
}

export function PlaylistsResponseDtoToJSONTyped(
  value?: PlaylistsResponseDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    items: (value['items'] as Array<any>).map(PlaylistDtoToJSON),
    total: value['total'],
    limit: value['limit'],
    offset: value['offset'],
  };
}
