/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuizResultDto
 */
export interface QuizResultDto {
    /**
     * Whether the answer was correct
     * @type {boolean}
     * @memberof QuizResultDto
     */
    correct: boolean;
    /**
     * Whether a freeze was earned from this answer
     * @type {boolean}
     * @memberof QuizResultDto
     */
    freezeEarned: boolean;
    /**
     * Current number of freezes after this answer
     * @type {number}
     * @memberof QuizResultDto
     */
    freezesAvailable: number;
    /**
     * The correct answer index (shown after answering)
     * @type {number}
     * @memberof QuizResultDto
     */
    correctAnswerIndex: number;
}

/**
 * Check if a given object implements the QuizResultDto interface.
 */
export function instanceOfQuizResultDto(value: object): value is QuizResultDto {
    if (!('correct' in value) || value['correct'] === undefined) return false;
    if (!('freezeEarned' in value) || value['freezeEarned'] === undefined) return false;
    if (!('freezesAvailable' in value) || value['freezesAvailable'] === undefined) return false;
    if (!('correctAnswerIndex' in value) || value['correctAnswerIndex'] === undefined) return false;
    return true;
}

export function QuizResultDtoFromJSON(json: any): QuizResultDto {
    return QuizResultDtoFromJSONTyped(json, false);
}

export function QuizResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuizResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'correct': json['correct'],
        'freezeEarned': json['freezeEarned'],
        'freezesAvailable': json['freezesAvailable'],
        'correctAnswerIndex': json['correctAnswerIndex'],
    };
}

export function QuizResultDtoToJSON(json: any): QuizResultDto {
    return QuizResultDtoToJSONTyped(json, false);
}

export function QuizResultDtoToJSONTyped(value?: QuizResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'correct': value['correct'],
        'freezeEarned': value['freezeEarned'],
        'freezesAvailable': value['freezesAvailable'],
        'correctAnswerIndex': value['correctAnswerIndex'],
    };
}

