/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface QuizQuestionDto
 */
export interface QuizQuestionDto {
  /**
   * Question ID
   * @type {string}
   * @memberof QuizQuestionDto
   */
  id: string;
  /**
   * The question text
   * @type {string}
   * @memberof QuizQuestionDto
   */
  question: string;
  /**
   * Answer options
   * @type {Array<string>}
   * @memberof QuizQuestionDto
   */
  options: Array<string>;
  /**
   * Question category
   * @type {string}
   * @memberof QuizQuestionDto
   */
  category: string;
}

/**
 * Check if a given object implements the QuizQuestionDto interface.
 */
export function instanceOfQuizQuestionDto(
  value: object,
): value is QuizQuestionDto {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('question' in value) || value['question'] === undefined) return false;
  if (!('options' in value) || value['options'] === undefined) return false;
  if (!('category' in value) || value['category'] === undefined) return false;
  return true;
}

export function QuizQuestionDtoFromJSON(json: any): QuizQuestionDto {
  return QuizQuestionDtoFromJSONTyped(json, false);
}

export function QuizQuestionDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): QuizQuestionDto {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    question: json['question'],
    options: json['options'],
    category: json['category'],
  };
}

export function QuizQuestionDtoToJSON(json: any): QuizQuestionDto {
  return QuizQuestionDtoToJSONTyped(json, false);
}

export function QuizQuestionDtoToJSONTyped(
  value?: QuizQuestionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    question: value['question'],
    options: value['options'],
    category: value['category'],
  };
}
