/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestPasswordResetDto
 */
export interface RequestPasswordResetDto {
    /**
     * The address to send a reset link to
     * @type {string}
     * @memberof RequestPasswordResetDto
     */
    email: string;
}

/**
 * Check if a given object implements the RequestPasswordResetDto interface.
 */
export function instanceOfRequestPasswordResetDto(value: object): value is RequestPasswordResetDto {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RequestPasswordResetDtoFromJSON(json: any): RequestPasswordResetDto {
    return RequestPasswordResetDtoFromJSONTyped(json, false);
}

export function RequestPasswordResetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestPasswordResetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function RequestPasswordResetDtoToJSON(json: any): RequestPasswordResetDto {
    return RequestPasswordResetDtoToJSONTyped(json, false);
}

export function RequestPasswordResetDtoToJSONTyped(value?: RequestPasswordResetDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

