/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoomPlayerDto
 */
export interface RoomPlayerDto {
    /**
     * 
     * @type {string}
     * @memberof RoomPlayerDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RoomPlayerDto
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof RoomPlayerDto
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof RoomPlayerDto
     */
    avatarUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof RoomPlayerDto
     */
    isReady: boolean;
    /**
     * 
     * @type {number}
     * @memberof RoomPlayerDto
     */
    totalScore: number;
    /**
     * 
     * @type {Date}
     * @memberof RoomPlayerDto
     */
    joinedAt: Date;
}

/**
 * Check if a given object implements the RoomPlayerDto interface.
 */
export function instanceOfRoomPlayerDto(value: object): value is RoomPlayerDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('isReady' in value) || value['isReady'] === undefined) return false;
    if (!('totalScore' in value) || value['totalScore'] === undefined) return false;
    if (!('joinedAt' in value) || value['joinedAt'] === undefined) return false;
    return true;
}

export function RoomPlayerDtoFromJSON(json: any): RoomPlayerDto {
    return RoomPlayerDtoFromJSONTyped(json, false);
}

export function RoomPlayerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomPlayerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'displayName': json['displayName'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'isReady': json['isReady'],
        'totalScore': json['totalScore'],
        'joinedAt': (new Date(json['joinedAt'])),
    };
}

export function RoomPlayerDtoToJSON(json: any): RoomPlayerDto {
    return RoomPlayerDtoToJSONTyped(json, false);
}

export function RoomPlayerDtoToJSONTyped(value?: RoomPlayerDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'displayName': value['displayName'],
        'avatarUrl': value['avatarUrl'],
        'isReady': value['isReady'],
        'totalScore': value['totalScore'],
        'joinedAt': value['joinedAt'].toISOString(),
    };
}

