/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomPlayerDto } from './RoomPlayerDto';
import {
    RoomPlayerDtoFromJSON,
    RoomPlayerDtoFromJSONTyped,
    RoomPlayerDtoToJSON,
    RoomPlayerDtoToJSONTyped,
} from './RoomPlayerDto';

/**
 * 
 * @export
 * @interface RoomDto
 */
export interface RoomDto {
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    inviteCode: string;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    hostId: string;
    /**
     * 
     * @type {number}
     * @memberof RoomDto
     */
    roundCount: number;
    /**
     * 
     * @type {string}
     * @memberof RoomDto
     */
    status: RoomDtoStatusEnum;
    /**
     * Where this room draws its songs from
     * @type {string}
     * @memberof RoomDto
     */
    trackSource: RoomDtoTrackSourceEnum;
    /**
     * 
     * @type {Array<RoomPlayerDto>}
     * @memberof RoomDto
     */
    players: Array<RoomPlayerDto>;
    /**
     * 
     * @type {Date}
     * @memberof RoomDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof RoomDto
     */
    startedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RoomDto
     */
    completedAt?: Date;
}


/**
 * @export
 */
export const RoomDtoStatusEnum = {
    Waiting: 'WAITING',
    Playing: 'PLAYING',
    Completed: 'COMPLETED',
    Expired: 'EXPIRED'
} as const;
export type RoomDtoStatusEnum = typeof RoomDtoStatusEnum[keyof typeof RoomDtoStatusEnum];

/**
 * @export
 */
export const RoomDtoTrackSourceEnum = {
    Pool: 'POOL',
    Libraries: 'LIBRARIES'
} as const;
export type RoomDtoTrackSourceEnum = typeof RoomDtoTrackSourceEnum[keyof typeof RoomDtoTrackSourceEnum];


/**
 * Check if a given object implements the RoomDto interface.
 */
export function instanceOfRoomDto(value: object): value is RoomDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('inviteCode' in value) || value['inviteCode'] === undefined) return false;
    if (!('hostId' in value) || value['hostId'] === undefined) return false;
    if (!('roundCount' in value) || value['roundCount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('trackSource' in value) || value['trackSource'] === undefined) return false;
    if (!('players' in value) || value['players'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RoomDtoFromJSON(json: any): RoomDto {
    return RoomDtoFromJSONTyped(json, false);
}

export function RoomDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'inviteCode': json['inviteCode'],
        'hostId': json['hostId'],
        'roundCount': json['roundCount'],
        'status': json['status'],
        'trackSource': json['trackSource'],
        'players': ((json['players'] as Array<any>).map(RoomPlayerDtoFromJSON)),
        'createdAt': (new Date(json['createdAt'])),
        'startedAt': json['startedAt'] == null ? undefined : (new Date(json['startedAt'])),
        'completedAt': json['completedAt'] == null ? undefined : (new Date(json['completedAt'])),
    };
}

export function RoomDtoToJSON(json: any): RoomDto {
    return RoomDtoToJSONTyped(json, false);
}

export function RoomDtoToJSONTyped(value?: RoomDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'inviteCode': value['inviteCode'],
        'hostId': value['hostId'],
        'roundCount': value['roundCount'],
        'status': value['status'],
        'trackSource': value['trackSource'],
        'players': ((value['players'] as Array<any>).map(RoomPlayerDtoToJSON)),
        'createdAt': value['createdAt'].toISOString(),
        'startedAt': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
    };
}

