/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoreboardPlayerRoundDto
 */
export interface ScoreboardPlayerRoundDto {
    /**
     * 
     * @type {string}
     * @memberof ScoreboardPlayerRoundDto
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ScoreboardPlayerRoundDto
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof ScoreboardPlayerRoundDto
     */
    avatarUrl?: string;
    /**
     * Score for this round (0-6)
     * @type {number}
     * @memberof ScoreboardPlayerRoundDto
     */
    score: number;
    /**
     * Number of guesses used
     * @type {number}
     * @memberof ScoreboardPlayerRoundDto
     */
    guessCount: number;
    /**
     * Whether the player won this round
     * @type {boolean}
     * @memberof ScoreboardPlayerRoundDto
     */
    won: boolean;
}

/**
 * Check if a given object implements the ScoreboardPlayerRoundDto interface.
 */
export function instanceOfScoreboardPlayerRoundDto(value: object): value is ScoreboardPlayerRoundDto {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('guessCount' in value) || value['guessCount'] === undefined) return false;
    if (!('won' in value) || value['won'] === undefined) return false;
    return true;
}

export function ScoreboardPlayerRoundDtoFromJSON(json: any): ScoreboardPlayerRoundDto {
    return ScoreboardPlayerRoundDtoFromJSONTyped(json, false);
}

export function ScoreboardPlayerRoundDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreboardPlayerRoundDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'displayName': json['displayName'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'score': json['score'],
        'guessCount': json['guessCount'],
        'won': json['won'],
    };
}

export function ScoreboardPlayerRoundDtoToJSON(json: any): ScoreboardPlayerRoundDto {
    return ScoreboardPlayerRoundDtoToJSONTyped(json, false);
}

export function ScoreboardPlayerRoundDtoToJSONTyped(value?: ScoreboardPlayerRoundDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'displayName': value['displayName'],
        'avatarUrl': value['avatarUrl'],
        'score': value['score'],
        'guessCount': value['guessCount'],
        'won': value['won'],
    };
}

