/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetTrackSourceDto
 */
export interface SetTrackSourceDto {
    /**
     * Where the room should draw its songs from
     * @type {string}
     * @memberof SetTrackSourceDto
     */
    trackSource: SetTrackSourceDtoTrackSourceEnum;
}


/**
 * @export
 */
export const SetTrackSourceDtoTrackSourceEnum = {
    Pool: 'POOL',
    Libraries: 'LIBRARIES'
} as const;
export type SetTrackSourceDtoTrackSourceEnum = typeof SetTrackSourceDtoTrackSourceEnum[keyof typeof SetTrackSourceDtoTrackSourceEnum];


/**
 * Check if a given object implements the SetTrackSourceDto interface.
 */
export function instanceOfSetTrackSourceDto(value: object): value is SetTrackSourceDto {
    if (!('trackSource' in value) || value['trackSource'] === undefined) return false;
    return true;
}

export function SetTrackSourceDtoFromJSON(json: any): SetTrackSourceDto {
    return SetTrackSourceDtoFromJSONTyped(json, false);
}

export function SetTrackSourceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetTrackSourceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'trackSource': json['trackSource'],
    };
}

export function SetTrackSourceDtoToJSON(json: any): SetTrackSourceDto {
    return SetTrackSourceDtoToJSONTyped(json, false);
}

export function SetTrackSourceDtoToJSONTyped(value?: SetTrackSourceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trackSource': value['trackSource'],
    };
}

