/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ShareResultDto
 */
export interface ShareResultDto {
  /**
   * Date (YYYY-MM-DD)
   * @type {string}
   * @memberof ShareResultDto
   */
  date: string;
  /**
   * Score 0-6
   * @type {number}
   * @memberof ShareResultDto
   */
  score: number;
  /**
   * Guess pattern e.g. 🟥🟨🟩
   * @type {string}
   * @memberof ShareResultDto
   */
  guessPattern: string;
  /**
   * Track name
   * @type {string}
   * @memberof ShareResultDto
   */
  trackName: string;
  /**
   * Artist name
   * @type {string}
   * @memberof ShareResultDto
   */
  artistName: string;
  /**
   * Pre-formatted share text
   * @type {string}
   * @memberof ShareResultDto
   */
  shareText: string;
  /**
   * Game number (days since epoch or similar)
   * @type {number}
   * @memberof ShareResultDto
   */
  gameNumber: number;
}

/**
 * Check if a given object implements the ShareResultDto interface.
 */
export function instanceOfShareResultDto(
  value: object,
): value is ShareResultDto {
  if (!('date' in value) || value['date'] === undefined) return false;
  if (!('score' in value) || value['score'] === undefined) return false;
  if (!('guessPattern' in value) || value['guessPattern'] === undefined)
    return false;
  if (!('trackName' in value) || value['trackName'] === undefined) return false;
  if (!('artistName' in value) || value['artistName'] === undefined)
    return false;
  if (!('shareText' in value) || value['shareText'] === undefined) return false;
  if (!('gameNumber' in value) || value['gameNumber'] === undefined)
    return false;
  return true;
}

export function ShareResultDtoFromJSON(json: any): ShareResultDto {
  return ShareResultDtoFromJSONTyped(json, false);
}

export function ShareResultDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ShareResultDto {
  if (json == null) {
    return json;
  }
  return {
    date: json['date'],
    score: json['score'],
    guessPattern: json['guessPattern'],
    trackName: json['trackName'],
    artistName: json['artistName'],
    shareText: json['shareText'],
    gameNumber: json['gameNumber'],
  };
}

export function ShareResultDtoToJSON(json: any): ShareResultDto {
  return ShareResultDtoToJSONTyped(json, false);
}

export function ShareResultDtoToJSONTyped(
  value?: ShareResultDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    date: value['date'],
    score: value['score'],
    guessPattern: value['guessPattern'],
    trackName: value['trackName'],
    artistName: value['artistName'],
    shareText: value['shareText'],
    gameNumber: value['gameNumber'],
  };
}
