/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuessResult } from './GuessResult';
import {
    GuessResultFromJSON,
    GuessResultFromJSONTyped,
    GuessResultToJSON,
    GuessResultToJSONTyped,
} from './GuessResult';
import type { TrackRevealDto } from './TrackRevealDto';
import {
    TrackRevealDtoFromJSON,
    TrackRevealDtoFromJSONTyped,
    TrackRevealDtoToJSON,
    TrackRevealDtoToJSONTyped,
} from './TrackRevealDto';
import type { GuessHistoryDto } from './GuessHistoryDto';
import {
    GuessHistoryDtoFromJSON,
    GuessHistoryDtoFromJSONTyped,
    GuessHistoryDtoToJSON,
    GuessHistoryDtoToJSONTyped,
} from './GuessHistoryDto';

/**
 * 
 * @export
 * @interface SpecialEventGuessResultDto
 */
export interface SpecialEventGuessResultDto {
    /**
     * Evaluation result for this guess
     * @type {GuessResult}
     * @memberof SpecialEventGuessResultDto
     */
    result: GuessResult;
    /**
     * True if this track is over (won or out of rounds)
     * @type {boolean}
     * @memberof SpecialEventGuessResultDto
     */
    trackOver: boolean;
    /**
     * True if the whole 8-track run is now complete
     * @type {boolean}
     * @memberof SpecialEventGuessResultDto
     */
    runComplete: boolean;
    /**
     * New current-round index for this track
     * @type {number}
     * @memberof SpecialEventGuessResultDto
     */
    currentRound: number;
    /**
     * Snippet duration in seconds for the new round
     * @type {number}
     * @memberof SpecialEventGuessResultDto
     */
    snippetDuration: number;
    /**
     * Updated guess history for the current track
     * @type {Array<GuessHistoryDto>}
     * @memberof SpecialEventGuessResultDto
     */
    currentGuesses: Array<GuessHistoryDto>;
    /**
     * Reveal block — present only when the track is over
     * @type {TrackRevealDto}
     * @memberof SpecialEventGuessResultDto
     */
    reveal?: TrackRevealDto;
}



/**
 * Check if a given object implements the SpecialEventGuessResultDto interface.
 */
export function instanceOfSpecialEventGuessResultDto(value: object): value is SpecialEventGuessResultDto {
    if (!('result' in value) || value['result'] === undefined) return false;
    if (!('trackOver' in value) || value['trackOver'] === undefined) return false;
    if (!('runComplete' in value) || value['runComplete'] === undefined) return false;
    if (!('currentRound' in value) || value['currentRound'] === undefined) return false;
    if (!('snippetDuration' in value) || value['snippetDuration'] === undefined) return false;
    if (!('currentGuesses' in value) || value['currentGuesses'] === undefined) return false;
    return true;
}

export function SpecialEventGuessResultDtoFromJSON(json: any): SpecialEventGuessResultDto {
    return SpecialEventGuessResultDtoFromJSONTyped(json, false);
}

export function SpecialEventGuessResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpecialEventGuessResultDto {
    if (json == null) {
        return json;
    }
    return {
        
        'result': GuessResultFromJSON(json['result']),
        'trackOver': json['trackOver'],
        'runComplete': json['runComplete'],
        'currentRound': json['currentRound'],
        'snippetDuration': json['snippetDuration'],
        'currentGuesses': ((json['currentGuesses'] as Array<any>).map(GuessHistoryDtoFromJSON)),
        'reveal': json['reveal'] == null ? undefined : TrackRevealDtoFromJSON(json['reveal']),
    };
}

export function SpecialEventGuessResultDtoToJSON(json: any): SpecialEventGuessResultDto {
    return SpecialEventGuessResultDtoToJSONTyped(json, false);
}

export function SpecialEventGuessResultDtoToJSONTyped(value?: SpecialEventGuessResultDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': GuessResultToJSON(value['result']),
        'trackOver': value['trackOver'],
        'runComplete': value['runComplete'],
        'currentRound': value['currentRound'],
        'snippetDuration': value['snippetDuration'],
        'currentGuesses': ((value['currentGuesses'] as Array<any>).map(GuessHistoryDtoToJSON)),
        'reveal': TrackRevealDtoToJSON(value['reveal']),
    };
}

