/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartGameDto
 */
export interface StartGameDto {
    /**
     * The ID of the playlist to start the game with
     * @type {string}
     * @memberof StartGameDto
     */
    playlistId?: string;
    /**
     * The game mode to start (all or daily)
     * @type {string}
     * @memberof StartGameDto
     */
    mode: StartGameDtoModeEnum;
}


/**
 * @export
 */
export const StartGameDtoModeEnum = {
    Daily: 'DAILY',
    All: 'ALL'
} as const;
export type StartGameDtoModeEnum = typeof StartGameDtoModeEnum[keyof typeof StartGameDtoModeEnum];


/**
 * Check if a given object implements the StartGameDto interface.
 */
export function instanceOfStartGameDto(value: object): value is StartGameDto {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    return true;
}

export function StartGameDtoFromJSON(json: any): StartGameDto {
    return StartGameDtoFromJSONTyped(json, false);
}

export function StartGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartGameDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playlistId': json['playlistId'] == null ? undefined : json['playlistId'],
        'mode': json['mode'],
    };
}

export function StartGameDtoToJSON(json: any): StartGameDto {
    return StartGameDtoToJSONTyped(json, false);
}

export function StartGameDtoToJSONTyped(value?: StartGameDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playlistId': value['playlistId'],
        'mode': value['mode'],
    };
}

