/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartRunDto
 */
export interface StartRunDto {
    /**
     * The playlist ID to pick tracks from
     * @type {string}
     * @memberof StartRunDto
     */
    playlistId: string;
    /**
     * Difficulty level (controls snippet duration)
     * @type {string}
     * @memberof StartRunDto
     */
    difficulty: StartRunDtoDifficultyEnum;
}


/**
 * @export
 */
export const StartRunDtoDifficultyEnum = {
    Easy: 'EASY',
    Medium: 'MEDIUM',
    Hard: 'HARD',
    Expert: 'EXPERT'
} as const;
export type StartRunDtoDifficultyEnum = typeof StartRunDtoDifficultyEnum[keyof typeof StartRunDtoDifficultyEnum];


/**
 * Check if a given object implements the StartRunDto interface.
 */
export function instanceOfStartRunDto(value: object): value is StartRunDto {
    if (!('playlistId' in value) || value['playlistId'] === undefined) return false;
    if (!('difficulty' in value) || value['difficulty'] === undefined) return false;
    return true;
}

export function StartRunDtoFromJSON(json: any): StartRunDto {
    return StartRunDtoFromJSONTyped(json, false);
}

export function StartRunDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartRunDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playlistId': json['playlistId'],
        'difficulty': json['difficulty'],
    };
}

export function StartRunDtoToJSON(json: any): StartRunDto {
    return StartRunDtoToJSONTyped(json, false);
}

export function StartRunDtoToJSONTyped(value?: StartRunDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playlistId': value['playlistId'],
        'difficulty': value['difficulty'],
    };
}

