/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartGameDto
 */
export interface StartGameDto {
    /**
     * 
     * @type {string}
     * @memberof StartGameDto
     */
    playlistId: string;
}

/**
 * Check if a given object implements the StartGameDto interface.
 */
export function instanceOfStartGameDto(value: object): value is StartGameDto {
    if (!('playlistId' in value) || value['playlistId'] === undefined) return false;
    return true;
}

export function StartGameDtoFromJSON(json: any): StartGameDto {
    return StartGameDtoFromJSONTyped(json, false);
}

export function StartGameDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartGameDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playlistId': json['playlistId'],
    };
}

export function StartGameDtoToJSON(json: any): StartGameDto {
    return StartGameDtoToJSONTyped(json, false);
}

export function StartGameDtoToJSONTyped(value?: StartGameDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playlistId': value['playlistId'],
    };
}

