/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StreakStatusDto
 */
export interface StreakStatusDto {
  /**
   * Current daily streak (consecutive win days)
   * @type {number}
   * @memberof StreakStatusDto
   */
  currentStreak: number;
  /**
   * Best daily streak ever
   * @type {number}
   * @memberof StreakStatusDto
   */
  bestStreak: number;
  /**
   * Whether the user has won today
   * @type {boolean}
   * @memberof StreakStatusDto
   */
  playedToday: boolean;
  /**
   * Whether a gap exists and streak could be lost
   * @type {boolean}
   * @memberof StreakStatusDto
   */
  streakAtRisk: boolean;
  /**
   * Whether the user can save their streak with freezes
   * @type {boolean}
   * @memberof StreakStatusDto
   */
  canSaveStreak: boolean;
  /**
   * Number of missed days in the gap
   * @type {number}
   * @memberof StreakStatusDto
   */
  gapDays: number;
  /**
   * Number of freezes available
   * @type {number}
   * @memberof StreakStatusDto
   */
  freezesAvailable: number;
  /**
   * Number of freezes needed to bridge the gap
   * @type {number}
   * @memberof StreakStatusDto
   */
  freezeCost: number;
  /**
   * Whether the user is trusted (can earn freezes)
   * @type {boolean}
   * @memberof StreakStatusDto
   */
  isTrusted: boolean;
}

/**
 * Check if a given object implements the StreakStatusDto interface.
 */
export function instanceOfStreakStatusDto(
  value: object,
): value is StreakStatusDto {
  if (!('currentStreak' in value) || value['currentStreak'] === undefined)
    return false;
  if (!('bestStreak' in value) || value['bestStreak'] === undefined)
    return false;
  if (!('playedToday' in value) || value['playedToday'] === undefined)
    return false;
  if (!('streakAtRisk' in value) || value['streakAtRisk'] === undefined)
    return false;
  if (!('canSaveStreak' in value) || value['canSaveStreak'] === undefined)
    return false;
  if (!('gapDays' in value) || value['gapDays'] === undefined) return false;
  if (!('freezesAvailable' in value) || value['freezesAvailable'] === undefined)
    return false;
  if (!('freezeCost' in value) || value['freezeCost'] === undefined)
    return false;
  if (!('isTrusted' in value) || value['isTrusted'] === undefined) return false;
  return true;
}

export function StreakStatusDtoFromJSON(json: any): StreakStatusDto {
  return StreakStatusDtoFromJSONTyped(json, false);
}

export function StreakStatusDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): StreakStatusDto {
  if (json == null) {
    return json;
  }
  return {
    currentStreak: json['currentStreak'],
    bestStreak: json['bestStreak'],
    playedToday: json['playedToday'],
    streakAtRisk: json['streakAtRisk'],
    canSaveStreak: json['canSaveStreak'],
    gapDays: json['gapDays'],
    freezesAvailable: json['freezesAvailable'],
    freezeCost: json['freezeCost'],
    isTrusted: json['isTrusted'],
  };
}

export function StreakStatusDtoToJSON(json: any): StreakStatusDto {
  return StreakStatusDtoToJSONTyped(json, false);
}

export function StreakStatusDtoToJSONTyped(
  value?: StreakStatusDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    currentStreak: value['currentStreak'],
    bestStreak: value['bestStreak'],
    playedToday: value['playedToday'],
    streakAtRisk: value['streakAtRisk'],
    canSaveStreak: value['canSaveStreak'],
    gapDays: value['gapDays'],
    freezesAvailable: value['freezesAvailable'],
    freezeCost: value['freezeCost'],
    isTrusted: value['isTrusted'],
  };
}
