/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreakFreezeUsageDto
 */
export interface StreakFreezeUsageDto {
    /**
     * Freeze usage ID
     * @type {string}
     * @memberof StreakFreezeUsageDto
     */
    id: string;
    /**
     * First covered day (YYYY-MM-DD)
     * @type {string}
     * @memberof StreakFreezeUsageDto
     */
    coveredFrom: string;
    /**
     * Last covered day (YYYY-MM-DD)
     * @type {string}
     * @memberof StreakFreezeUsageDto
     */
    coveredTo: string;
    /**
     * Number of freezes consumed
     * @type {number}
     * @memberof StreakFreezeUsageDto
     */
    freezesUsed: number;
    /**
     * Number of gap days bridged
     * @type {number}
     * @memberof StreakFreezeUsageDto
     */
    gapDays: number;
    /**
     * Streak count at the time of freeze usage
     * @type {number}
     * @memberof StreakFreezeUsageDto
     */
    streakAtTime: number;
}

/**
 * Check if a given object implements the StreakFreezeUsageDto interface.
 */
export function instanceOfStreakFreezeUsageDto(value: object): value is StreakFreezeUsageDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('coveredFrom' in value) || value['coveredFrom'] === undefined) return false;
    if (!('coveredTo' in value) || value['coveredTo'] === undefined) return false;
    if (!('freezesUsed' in value) || value['freezesUsed'] === undefined) return false;
    if (!('gapDays' in value) || value['gapDays'] === undefined) return false;
    if (!('streakAtTime' in value) || value['streakAtTime'] === undefined) return false;
    return true;
}

export function StreakFreezeUsageDtoFromJSON(json: any): StreakFreezeUsageDto {
    return StreakFreezeUsageDtoFromJSONTyped(json, false);
}

export function StreakFreezeUsageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreakFreezeUsageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'coveredFrom': json['coveredFrom'],
        'coveredTo': json['coveredTo'],
        'freezesUsed': json['freezesUsed'],
        'gapDays': json['gapDays'],
        'streakAtTime': json['streakAtTime'],
    };
}

export function StreakFreezeUsageDtoToJSON(json: any): StreakFreezeUsageDto {
    return StreakFreezeUsageDtoToJSONTyped(json, false);
}

export function StreakFreezeUsageDtoToJSONTyped(value?: StreakFreezeUsageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'coveredFrom': value['coveredFrom'],
        'coveredTo': value['coveredTo'],
        'freezesUsed': value['freezesUsed'],
        'gapDays': value['gapDays'],
        'streakAtTime': value['streakAtTime'],
    };
}

