/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StreakQuestionDto
 */
export interface StreakQuestionDto {
    /**
     * 
     * @type {string}
     * @memberof StreakQuestionDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof StreakQuestionDto
     */
    question: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StreakQuestionDto
     */
    options: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof StreakQuestionDto
     */
    correctAnswerIndex: number;
    /**
     * 
     * @type {string}
     * @memberof StreakQuestionDto
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof StreakQuestionDto
     */
    context?: string;
    /**
     * 
     * @type {boolean}
     * @memberof StreakQuestionDto
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof StreakQuestionDto
     */
    addedBy: string;
    /**
     * 
     * @type {Date}
     * @memberof StreakQuestionDto
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof StreakQuestionDto
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the StreakQuestionDto interface.
 */
export function instanceOfStreakQuestionDto(value: object): value is StreakQuestionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('question' in value) || value['question'] === undefined) return false;
    if (!('options' in value) || value['options'] === undefined) return false;
    if (!('correctAnswerIndex' in value) || value['correctAnswerIndex'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('addedBy' in value) || value['addedBy'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function StreakQuestionDtoFromJSON(json: any): StreakQuestionDto {
    return StreakQuestionDtoFromJSONTyped(json, false);
}

export function StreakQuestionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StreakQuestionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'question': json['question'],
        'options': json['options'],
        'correctAnswerIndex': json['correctAnswerIndex'],
        'category': json['category'],
        'context': json['context'] == null ? undefined : json['context'],
        'isActive': json['isActive'],
        'addedBy': json['addedBy'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function StreakQuestionDtoToJSON(json: any): StreakQuestionDto {
    return StreakQuestionDtoToJSONTyped(json, false);
}

export function StreakQuestionDtoToJSONTyped(value?: StreakQuestionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'question': value['question'],
        'options': value['options'],
        'correctAnswerIndex': value['correctAnswerIndex'],
        'category': value['category'],
        'context': value['context'],
        'isActive': value['isActive'],
        'addedBy': value['addedBy'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

