/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubmitGauntletGuessDto
 */
export interface SubmitGauntletGuessDto {
    /**
     * The playlist ID (needed to pick the next track)
     * @type {string}
     * @memberof SubmitGauntletGuessDto
     */
    playlistId: string;
    /**
     * The ID of the track to guess
     * @type {string}
     * @memberof SubmitGauntletGuessDto
     */
    trackId?: string;
    /**
     * Whether the current guess is a skip (ends the run)
     * @type {boolean}
     * @memberof SubmitGauntletGuessDto
     */
    skip?: boolean;
    /**
     * Track name
     * @type {string}
     * @memberof SubmitGauntletGuessDto
     */
    trackName?: string;
    /**
     * Artist name
     * @type {string}
     * @memberof SubmitGauntletGuessDto
     */
    artistName?: string;
    /**
     * ISRC of the guessed recording, when the catalogue supplies one
     * @type {string}
     * @memberof SubmitGauntletGuessDto
     */
    isrc?: string;
    /**
     * Album name
     * @type {string}
     * @memberof SubmitGauntletGuessDto
     */
    albumName?: string;
}

/**
 * Check if a given object implements the SubmitGauntletGuessDto interface.
 */
export function instanceOfSubmitGauntletGuessDto(value: object): value is SubmitGauntletGuessDto {
    if (!('playlistId' in value) || value['playlistId'] === undefined) return false;
    return true;
}

export function SubmitGauntletGuessDtoFromJSON(json: any): SubmitGauntletGuessDto {
    return SubmitGauntletGuessDtoFromJSONTyped(json, false);
}

export function SubmitGauntletGuessDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubmitGauntletGuessDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playlistId': json['playlistId'],
        'trackId': json['trackId'] == null ? undefined : json['trackId'],
        'skip': json['skip'] == null ? undefined : json['skip'],
        'trackName': json['trackName'] == null ? undefined : json['trackName'],
        'artistName': json['artistName'] == null ? undefined : json['artistName'],
        'isrc': json['isrc'] == null ? undefined : json['isrc'],
        'albumName': json['albumName'] == null ? undefined : json['albumName'],
    };
}

export function SubmitGauntletGuessDtoToJSON(json: any): SubmitGauntletGuessDto {
    return SubmitGauntletGuessDtoToJSONTyped(json, false);
}

export function SubmitGauntletGuessDtoToJSONTyped(value?: SubmitGauntletGuessDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playlistId': value['playlistId'],
        'trackId': value['trackId'],
        'skip': value['skip'],
        'trackName': value['trackName'],
        'artistName': value['artistName'],
        'isrc': value['isrc'],
        'albumName': value['albumName'],
    };
}

