/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubmitQuizAnswerDto
 */
export interface SubmitQuizAnswerDto {
  /**
   * The question ID
   * @type {string}
   * @memberof SubmitQuizAnswerDto
   */
  questionId: string;
  /**
   * The selected answer index (0-3)
   * @type {number}
   * @memberof SubmitQuizAnswerDto
   */
  answerIndex: number;
}

/**
 * Check if a given object implements the SubmitQuizAnswerDto interface.
 */
export function instanceOfSubmitQuizAnswerDto(
  value: object,
): value is SubmitQuizAnswerDto {
  if (!('questionId' in value) || value['questionId'] === undefined)
    return false;
  if (!('answerIndex' in value) || value['answerIndex'] === undefined)
    return false;
  return true;
}

export function SubmitQuizAnswerDtoFromJSON(json: any): SubmitQuizAnswerDto {
  return SubmitQuizAnswerDtoFromJSONTyped(json, false);
}

export function SubmitQuizAnswerDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SubmitQuizAnswerDto {
  if (json == null) {
    return json;
  }
  return {
    questionId: json['questionId'],
    answerIndex: json['answerIndex'],
  };
}

export function SubmitQuizAnswerDtoToJSON(json: any): SubmitQuizAnswerDto {
  return SubmitQuizAnswerDtoToJSONTyped(json, false);
}

export function SubmitQuizAnswerDtoToJSONTyped(
  value?: SubmitQuizAnswerDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    questionId: value['questionId'],
    answerIndex: value['answerIndex'],
  };
}
