/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackMetadataVo } from './TrackMetadataVo';
import {
    TrackMetadataVoFromJSON,
    TrackMetadataVoFromJSONTyped,
    TrackMetadataVoToJSON,
    TrackMetadataVoToJSONTyped,
} from './TrackMetadataVo';

/**
 * 
 * @export
 * @interface TrackEntity
 */
export interface TrackEntity {
    /**
     * The unique identifier for the track
     * @type {string}
     * @memberof TrackEntity
     */
    id: string;
    /**
     * The name of the track
     * @type {string}
     * @memberof TrackEntity
     */
    name: string;
    /**
     * The name of the artist
     * @type {string}
     * @memberof TrackEntity
     */
    artistName: string;
    /**
     * The URL of the album image
     * @type {string}
     * @memberof TrackEntity
     */
    albumImageUrl?: string;
    /**
     * The name of the album
     * @type {string}
     * @memberof TrackEntity
     */
    albumName?: string;
    /**
     * The URL of the album
     * @type {string}
     * @memberof TrackEntity
     */
    albumUrl?: string;
    /**
     * The year the track was released
     * @type {number}
     * @memberof TrackEntity
     */
    releaseYear?: number;
    /**
     * International Standard Recording Code
     * @type {string}
     * @memberof TrackEntity
     */
    isrc?: string;
    /**
     * The URL of the track preview
     * @type {string}
     * @memberof TrackEntity
     */
    previewUrl?: string;
    /**
     * Timestamp of when the track was last scraped
     * @type {Date}
     * @memberof TrackEntity
     */
    lastScrapedAt: Date;
    /**
     * Timestamp of when the track was created
     * @type {Date}
     * @memberof TrackEntity
     */
    createdAt: Date;
    /**
     * Timestamp of when the track was last updated
     * @type {Date}
     * @memberof TrackEntity
     */
    updatedAt: Date;
    /**
     * Metadata for the track
     * @type {TrackMetadataVo}
     * @memberof TrackEntity
     */
    metadata?: TrackMetadataVo;
    /**
     * All artist names for the track
     * @type {Array<string>}
     * @memberof TrackEntity
     */
    allArtists: Array<string>;
}

/**
 * Check if a given object implements the TrackEntity interface.
 */
export function instanceOfTrackEntity(value: object): value is TrackEntity {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('artistName' in value) || value['artistName'] === undefined) return false;
    if (!('lastScrapedAt' in value) || value['lastScrapedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('allArtists' in value) || value['allArtists'] === undefined) return false;
    return true;
}

export function TrackEntityFromJSON(json: any): TrackEntity {
    return TrackEntityFromJSONTyped(json, false);
}

export function TrackEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackEntity {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'artistName': json['artistName'],
        'albumImageUrl': json['albumImageUrl'] == null ? undefined : json['albumImageUrl'],
        'albumName': json['albumName'] == null ? undefined : json['albumName'],
        'albumUrl': json['albumUrl'] == null ? undefined : json['albumUrl'],
        'releaseYear': json['releaseYear'] == null ? undefined : json['releaseYear'],
        'isrc': json['isrc'] == null ? undefined : json['isrc'],
        'previewUrl': json['previewUrl'] == null ? undefined : json['previewUrl'],
        'lastScrapedAt': (new Date(json['lastScrapedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'metadata': json['metadata'] == null ? undefined : TrackMetadataVoFromJSON(json['metadata']),
        'allArtists': json['allArtists'],
    };
}

export function TrackEntityToJSON(json: any): TrackEntity {
    return TrackEntityToJSONTyped(json, false);
}

export function TrackEntityToJSONTyped(value?: TrackEntity | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'artistName': value['artistName'],
        'albumImageUrl': value['albumImageUrl'],
        'albumName': value['albumName'],
        'albumUrl': value['albumUrl'],
        'releaseYear': value['releaseYear'],
        'isrc': value['isrc'],
        'previewUrl': value['previewUrl'],
        'lastScrapedAt': value['lastScrapedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'metadata': TrackMetadataVoToJSON(value['metadata']),
        'allArtists': value['allArtists'],
    };
}

