/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackOptionDto
 */
export interface TrackOptionDto {
    /**
     * 
     * @type {string}
     * @memberof TrackOptionDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrackOptionDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TrackOptionDto
     */
    artist: string;
    /**
     * 
     * @type {string}
     * @memberof TrackOptionDto
     */
    albumImageUrl?: string;
}

/**
 * Check if a given object implements the TrackOptionDto interface.
 */
export function instanceOfTrackOptionDto(value: object): value is TrackOptionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('artist' in value) || value['artist'] === undefined) return false;
    return true;
}

export function TrackOptionDtoFromJSON(json: any): TrackOptionDto {
    return TrackOptionDtoFromJSONTyped(json, false);
}

export function TrackOptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackOptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'artist': json['artist'],
        'albumImageUrl': json['albumImageUrl'] == null ? undefined : json['albumImageUrl'],
    };
}

export function TrackOptionDtoToJSON(json: any): TrackOptionDto {
    return TrackOptionDtoToJSONTyped(json, false);
}

export function TrackOptionDtoToJSONTyped(value?: TrackOptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'artist': value['artist'],
        'albumImageUrl': value['albumImageUrl'],
    };
}

