/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackDossierDto
 */
export interface TrackDossierDto {
    /**
     * Journalistic context about the song/album
     * @type {string}
     * @memberof TrackDossierDto
     */
    context: string;
    /**
     * 1996-specific anchor fact
     * @type {string}
     * @memberof TrackDossierDto
     */
    fact1996: string;
    /**
     * One-line tonal landing (joke / observation)
     * @type {string}
     * @memberof TrackDossierDto
     */
    stinger: string;
}

/**
 * Check if a given object implements the TrackDossierDto interface.
 */
export function instanceOfTrackDossierDto(value: object): value is TrackDossierDto {
    if (!('context' in value) || value['context'] === undefined) return false;
    if (!('fact1996' in value) || value['fact1996'] === undefined) return false;
    if (!('stinger' in value) || value['stinger'] === undefined) return false;
    return true;
}

export function TrackDossierDtoFromJSON(json: any): TrackDossierDto {
    return TrackDossierDtoFromJSONTyped(json, false);
}

export function TrackDossierDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackDossierDto {
    if (json == null) {
        return json;
    }
    return {
        
        'context': json['context'],
        'fact1996': json['fact1996'],
        'stinger': json['stinger'],
    };
}

export function TrackDossierDtoToJSON(json: any): TrackDossierDto {
    return TrackDossierDtoToJSONTyped(json, false);
}

export function TrackDossierDtoToJSONTyped(value?: TrackDossierDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'context': value['context'],
        'fact1996': value['fact1996'],
        'stinger': value['stinger'],
    };
}

