/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LastfmDataVo } from './LastfmDataVo';
import {
    LastfmDataVoFromJSON,
    LastfmDataVoFromJSONTyped,
    LastfmDataVoToJSON,
    LastfmDataVoToJSONTyped,
} from './LastfmDataVo';

/**
 * 
 * @export
 * @interface TrackMetadataVo
 */
export interface TrackMetadataVo {
    /**
     * Last.fm data for the track
     * @type {LastfmDataVo}
     * @memberof TrackMetadataVo
     */
    lastfm?: LastfmDataVo;
}

/**
 * Check if a given object implements the TrackMetadataVo interface.
 */
export function instanceOfTrackMetadataVo(value: object): value is TrackMetadataVo {
    return true;
}

export function TrackMetadataVoFromJSON(json: any): TrackMetadataVo {
    return TrackMetadataVoFromJSONTyped(json, false);
}

export function TrackMetadataVoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackMetadataVo {
    if (json == null) {
        return json;
    }
    return {
        
        'lastfm': json['lastfm'] == null ? undefined : LastfmDataVoFromJSON(json['lastfm']),
    };
}

export function TrackMetadataVoToJSON(json: any): TrackMetadataVo {
    return TrackMetadataVoToJSONTyped(json, false);
}

export function TrackMetadataVoToJSONTyped(value?: TrackMetadataVo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lastfm': LastfmDataVoToJSON(value['lastfm']),
    };
}

