/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackDto
 */
export interface TrackDto {
    /**
     * 
     * @type {string}
     * @memberof TrackDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TrackDto
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TrackDto
     */
    artists: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TrackDto
     */
    albumName: string;
    /**
     * 
     * @type {string}
     * @memberof TrackDto
     */
    imageUrl: string;
    /**
     * 
     * @type {number}
     * @memberof TrackDto
     */
    durationMs: number;
    /**
     * 
     * @type {string}
     * @memberof TrackDto
     */
    externalUrl: string;
    /**
     * 
     * @type {string}
     * @memberof TrackDto
     */
    previewUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TrackDto
     */
    isPlayable: boolean;
    /**
     * The primary artist for easier comparison
     * @type {string}
     * @memberof TrackDto
     */
    primaryArtist: string;
    /**
     * Popularity score 0-100 for game balancing
     * @type {number}
     * @memberof TrackDto
     */
    popularity?: number;
    /**
     * Is the track explicit
     * @type {boolean}
     * @memberof TrackDto
     */
    isExplicit: boolean;
}

/**
 * Check if a given object implements the TrackDto interface.
 */
export function instanceOfTrackDto(value: object): value is TrackDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('artists' in value) || value['artists'] === undefined) return false;
    if (!('albumName' in value) || value['albumName'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('durationMs' in value) || value['durationMs'] === undefined) return false;
    if (!('externalUrl' in value) || value['externalUrl'] === undefined) return false;
    if (!('isPlayable' in value) || value['isPlayable'] === undefined) return false;
    if (!('primaryArtist' in value) || value['primaryArtist'] === undefined) return false;
    if (!('isExplicit' in value) || value['isExplicit'] === undefined) return false;
    return true;
}

export function TrackDtoFromJSON(json: any): TrackDto {
    return TrackDtoFromJSONTyped(json, false);
}

export function TrackDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'artists': json['artists'],
        'albumName': json['albumName'],
        'imageUrl': json['imageUrl'],
        'durationMs': json['durationMs'],
        'externalUrl': json['externalUrl'],
        'previewUrl': json['previewUrl'] == null ? undefined : json['previewUrl'],
        'isPlayable': json['isPlayable'],
        'primaryArtist': json['primaryArtist'],
        'popularity': json['popularity'] == null ? undefined : json['popularity'],
        'isExplicit': json['isExplicit'],
    };
}

export function TrackDtoToJSON(json: any): TrackDto {
    return TrackDtoToJSONTyped(json, false);
}

export function TrackDtoToJSONTyped(value?: TrackDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'artists': value['artists'],
        'albumName': value['albumName'],
        'imageUrl': value['imageUrl'],
        'durationMs': value['durationMs'],
        'externalUrl': value['externalUrl'],
        'previewUrl': value['previewUrl'],
        'isPlayable': value['isPlayable'],
        'primaryArtist': value['primaryArtist'],
        'popularity': value['popularity'],
        'isExplicit': value['isExplicit'],
    };
}

