/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TrackDossierDto } from './TrackDossierDto';
import {
    TrackDossierDtoFromJSON,
    TrackDossierDtoFromJSONTyped,
    TrackDossierDtoToJSON,
    TrackDossierDtoToJSONTyped,
} from './TrackDossierDto';

/**
 * 
 * @export
 * @interface TrackRevealDto
 */
export interface TrackRevealDto {
    /**
     * Spotify track ID
     * @type {string}
     * @memberof TrackRevealDto
     */
    trackId: string;
    /**
     * Track name
     * @type {string}
     * @memberof TrackRevealDto
     */
    trackName: string;
    /**
     * Primary artist name
     * @type {string}
     * @memberof TrackRevealDto
     */
    artistName: string;
    /**
     * Album cover URL
     * @type {string}
     * @memberof TrackRevealDto
     */
    albumImageUrl?: string;
    /**
     * Album name
     * @type {string}
     * @memberof TrackRevealDto
     */
    albumName?: string;
    /**
     * Dossier copy for this track
     * @type {TrackDossierDto}
     * @memberof TrackRevealDto
     */
    dossier: TrackDossierDto;
}

/**
 * Check if a given object implements the TrackRevealDto interface.
 */
export function instanceOfTrackRevealDto(value: object): value is TrackRevealDto {
    if (!('trackId' in value) || value['trackId'] === undefined) return false;
    if (!('trackName' in value) || value['trackName'] === undefined) return false;
    if (!('artistName' in value) || value['artistName'] === undefined) return false;
    if (!('dossier' in value) || value['dossier'] === undefined) return false;
    return true;
}

export function TrackRevealDtoFromJSON(json: any): TrackRevealDto {
    return TrackRevealDtoFromJSONTyped(json, false);
}

export function TrackRevealDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackRevealDto {
    if (json == null) {
        return json;
    }
    return {
        
        'trackId': json['trackId'],
        'trackName': json['trackName'],
        'artistName': json['artistName'],
        'albumImageUrl': json['albumImageUrl'] == null ? undefined : json['albumImageUrl'],
        'albumName': json['albumName'] == null ? undefined : json['albumName'],
        'dossier': TrackDossierDtoFromJSON(json['dossier']),
    };
}

export function TrackRevealDtoToJSON(json: any): TrackRevealDto {
    return TrackRevealDtoToJSONTyped(json, false);
}

export function TrackRevealDtoToJSONTyped(value?: TrackRevealDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'trackId': value['trackId'],
        'trackName': value['trackName'],
        'artistName': value['artistName'],
        'albumImageUrl': value['albumImageUrl'],
        'albumName': value['albumName'],
        'dossier': TrackDossierDtoToJSON(value['dossier']),
    };
}

