/* tslint:disable */
 
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrackOptionDto
 */
export interface TrackOptionDto {
    /**
     * The ID of the track
     * @type {string}
     * @memberof TrackOptionDto
     */
    id: string;
    /**
     * The name of the track
     * @type {string}
     * @memberof TrackOptionDto
     */
    name: string;
    /**
     * Normalized name for search/matching
     * @type {string}
     * @memberof TrackOptionDto
     */
    normalizedName: string;
    /**
     * The artist of the track
     * @type {string}
     * @memberof TrackOptionDto
     */
    artist: string;
    /**
     * Normalized artist for search/matching
     * @type {string}
     * @memberof TrackOptionDto
     */
    normalizedArtist: string;
    /**
     * The album image URL of the track
     * @type {string}
     * @memberof TrackOptionDto
     */
    albumImageUrl?: string;
    /**
     * The album name of the track
     * @type {string}
     * @memberof TrackOptionDto
     */
    albumName?: string;
    /**
     * The album URL of the track
     * @type {string}
     * @memberof TrackOptionDto
     */
    albumUrl?: string;
    /**
     * The release year of the track
     * @type {number}
     * @memberof TrackOptionDto
     */
    releaseYear?: number;
}

/**
 * Check if a given object implements the TrackOptionDto interface.
 */
export function instanceOfTrackOptionDto(value: object): value is TrackOptionDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('normalizedName' in value) || value['normalizedName'] === undefined) return false;
    if (!('artist' in value) || value['artist'] === undefined) return false;
    if (!('normalizedArtist' in value) || value['normalizedArtist'] === undefined) return false;
    return true;
}

export function TrackOptionDtoFromJSON(json: any): TrackOptionDto {
    return TrackOptionDtoFromJSONTyped(json, false);
}

export function TrackOptionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrackOptionDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'normalizedName': json['normalizedName'],
        'artist': json['artist'],
        'normalizedArtist': json['normalizedArtist'],
        'albumImageUrl': json['albumImageUrl'] == null ? undefined : json['albumImageUrl'],
        'albumName': json['albumName'] == null ? undefined : json['albumName'],
        'albumUrl': json['albumUrl'] == null ? undefined : json['albumUrl'],
        'releaseYear': json['releaseYear'] == null ? undefined : json['releaseYear'],
    };
}

export function TrackOptionDtoToJSON(json: any): TrackOptionDto {
    return TrackOptionDtoToJSONTyped(json, false);
}

export function TrackOptionDtoToJSONTyped(value?: TrackOptionDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'normalizedName': value['normalizedName'],
        'artist': value['artist'],
        'normalizedArtist': value['normalizedArtist'],
        'albumImageUrl': value['albumImageUrl'],
        'albumName': value['albumName'],
        'albumUrl': value['albumUrl'],
        'releaseYear': value['releaseYear'],
    };
}

