/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserPreferenceDto
 */
export interface UpdateUserPreferenceDto {
    /**
     * Show progressively blurred album art hint
     * @type {boolean}
     * @memberof UpdateUserPreferenceDto
     */
    showAlbumHint?: boolean;
    /**
     * Show genre, decade, and other text hints
     * @type {boolean}
     * @memberof UpdateUserPreferenceDto
     */
    showTextHints?: boolean;
    /**
     * Reduce motion and animations
     * @type {boolean}
     * @memberof UpdateUserPreferenceDto
     */
    reducedMotion?: boolean;
    /**
     * Show guess history during gameplay
     * @type {boolean}
     * @memberof UpdateUserPreferenceDto
     */
    showGuessHistory?: boolean;
    /**
     * Show this player by name on public leaderboards
     * @type {boolean}
     * @memberof UpdateUserPreferenceDto
     */
    showStatsToOthers?: boolean;
    /**
     * IANA timezone string (e.g. America/New_York)
     * @type {string}
     * @memberof UpdateUserPreferenceDto
     */
    timezone?: string;
}

/**
 * Check if a given object implements the UpdateUserPreferenceDto interface.
 */
export function instanceOfUpdateUserPreferenceDto(value: object): value is UpdateUserPreferenceDto {
    return true;
}

export function UpdateUserPreferenceDtoFromJSON(json: any): UpdateUserPreferenceDto {
    return UpdateUserPreferenceDtoFromJSONTyped(json, false);
}

export function UpdateUserPreferenceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserPreferenceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'showAlbumHint': json['showAlbumHint'] == null ? undefined : json['showAlbumHint'],
        'showTextHints': json['showTextHints'] == null ? undefined : json['showTextHints'],
        'reducedMotion': json['reducedMotion'] == null ? undefined : json['reducedMotion'],
        'showGuessHistory': json['showGuessHistory'] == null ? undefined : json['showGuessHistory'],
        'showStatsToOthers': json['showStatsToOthers'] == null ? undefined : json['showStatsToOthers'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
    };
}

export function UpdateUserPreferenceDtoToJSON(json: any): UpdateUserPreferenceDto {
    return UpdateUserPreferenceDtoToJSONTyped(json, false);
}

export function UpdateUserPreferenceDtoToJSONTyped(value?: UpdateUserPreferenceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'showAlbumHint': value['showAlbumHint'],
        'showTextHints': value['showTextHints'],
        'reducedMotion': value['reducedMotion'],
        'showGuessHistory': value['showGuessHistory'],
        'showStatsToOthers': value['showStatsToOthers'],
        'timezone': value['timezone'],
    };
}

