/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateStreakQuestionDto
 */
export interface UpdateStreakQuestionDto {
  /**
   *
   * @type {string}
   * @memberof UpdateStreakQuestionDto
   */
  question?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UpdateStreakQuestionDto
   */
  options?: Array<string>;
  /**
   *
   * @type {number}
   * @memberof UpdateStreakQuestionDto
   */
  correctAnswerIndex?: number;
  /**
   *
   * @type {string}
   * @memberof UpdateStreakQuestionDto
   */
  category?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateStreakQuestionDto
   */
  context?: string;
  /**
   *
   * @type {boolean}
   * @memberof UpdateStreakQuestionDto
   */
  isActive?: boolean;
}

/**
 * Check if a given object implements the UpdateStreakQuestionDto interface.
 */
export function instanceOfUpdateStreakQuestionDto(
  value: object,
): value is UpdateStreakQuestionDto {
  return true;
}

export function UpdateStreakQuestionDtoFromJSON(
  json: any,
): UpdateStreakQuestionDto {
  return UpdateStreakQuestionDtoFromJSONTyped(json, false);
}

export function UpdateStreakQuestionDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UpdateStreakQuestionDto {
  if (json == null) {
    return json;
  }
  return {
    question: json['question'] == null ? undefined : json['question'],
    options: json['options'] == null ? undefined : json['options'],
    correctAnswerIndex:
      json['correctAnswerIndex'] == null
        ? undefined
        : json['correctAnswerIndex'],
    category: json['category'] == null ? undefined : json['category'],
    context: json['context'] == null ? undefined : json['context'],
    isActive: json['isActive'] == null ? undefined : json['isActive'],
  };
}

export function UpdateStreakQuestionDtoToJSON(
  json: any,
): UpdateStreakQuestionDto {
  return UpdateStreakQuestionDtoToJSONTyped(json, false);
}

export function UpdateStreakQuestionDtoToJSONTyped(
  value?: UpdateStreakQuestionDto | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    question: value['question'],
    options: value['options'],
    correctAnswerIndex: value['correctAnswerIndex'],
    category: value['category'],
    context: value['context'],
    isActive: value['isActive'],
  };
}
