/* tslint:disable */
 
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDailySettingsDto
 */
export interface UpdateDailySettingsDto {
    /**
     * Playlist IDs to use for daily challenge (empty = use first playlists)
     * @type {Array<string>}
     * @memberof UpdateDailySettingsDto
     */
    playlistIds: Array<string>;
}

/**
 * Check if a given object implements the UpdateDailySettingsDto interface.
 */
export function instanceOfUpdateDailySettingsDto(value: object): value is UpdateDailySettingsDto {
    if (!('playlistIds' in value) || value['playlistIds'] === undefined) return false;
    return true;
}

export function UpdateDailySettingsDtoFromJSON(json: any): UpdateDailySettingsDto {
    return UpdateDailySettingsDtoFromJSONTyped(json, false);
}

export function UpdateDailySettingsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDailySettingsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'playlistIds': json['playlistIds'],
    };
}

export function UpdateDailySettingsDtoToJSON(json: any): UpdateDailySettingsDto {
    return UpdateDailySettingsDtoToJSONTyped(json, false);
}

export function UpdateDailySettingsDtoToJSONTyped(value?: UpdateDailySettingsDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'playlistIds': value['playlistIds'],
    };
}

