/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadAvatarResponseDto
 */
export interface UploadAvatarResponseDto {
    /**
     * The Cloudinary URL of the uploaded avatar
     * @type {string}
     * @memberof UploadAvatarResponseDto
     */
    customAvatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadAvatarResponseDto
     */
    avatarSource: UploadAvatarResponseDtoAvatarSourceEnum;
    /**
     * Effective avatar URL for display
     * @type {string}
     * @memberof UploadAvatarResponseDto
     */
    avatarUrl?: string;
}


/**
 * @export
 */
export const UploadAvatarResponseDtoAvatarSourceEnum = {
    Spotify: 'SPOTIFY',
    Custom: 'CUSTOM'
} as const;
export type UploadAvatarResponseDtoAvatarSourceEnum = typeof UploadAvatarResponseDtoAvatarSourceEnum[keyof typeof UploadAvatarResponseDtoAvatarSourceEnum];


/**
 * Check if a given object implements the UploadAvatarResponseDto interface.
 */
export function instanceOfUploadAvatarResponseDto(value: object): value is UploadAvatarResponseDto {
    if (!('avatarSource' in value) || value['avatarSource'] === undefined) return false;
    return true;
}

export function UploadAvatarResponseDtoFromJSON(json: any): UploadAvatarResponseDto {
    return UploadAvatarResponseDtoFromJSONTyped(json, false);
}

export function UploadAvatarResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadAvatarResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'customAvatarUrl': json['customAvatarUrl'] == null ? undefined : json['customAvatarUrl'],
        'avatarSource': json['avatarSource'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
    };
}

export function UploadAvatarResponseDtoToJSON(json: any): UploadAvatarResponseDto {
    return UploadAvatarResponseDtoToJSONTyped(json, false);
}

export function UploadAvatarResponseDtoToJSONTyped(value?: UploadAvatarResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customAvatarUrl': value['customAvatarUrl'],
        'avatarSource': value['avatarSource'],
        'avatarUrl': value['avatarUrl'],
    };
}

