/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPreferenceDto
 */
export interface UserPreferenceDto {
    /**
     * Show progressively blurred album art hint
     * @type {boolean}
     * @memberof UserPreferenceDto
     */
    showAlbumHint: boolean;
    /**
     * Show genre, decade, and other text hints
     * @type {boolean}
     * @memberof UserPreferenceDto
     */
    showTextHints: boolean;
    /**
     * Reduce motion and animations
     * @type {boolean}
     * @memberof UserPreferenceDto
     */
    reducedMotion: boolean;
    /**
     * Show guess history during gameplay
     * @type {boolean}
     * @memberof UserPreferenceDto
     */
    showGuessHistory: boolean;
    /**
     * IANA timezone string (e.g. America/New_York)
     * @type {string}
     * @memberof UserPreferenceDto
     */
    timezone: string;
}

/**
 * Check if a given object implements the UserPreferenceDto interface.
 */
export function instanceOfUserPreferenceDto(value: object): value is UserPreferenceDto {
    if (!('showAlbumHint' in value) || value['showAlbumHint'] === undefined) return false;
    if (!('showTextHints' in value) || value['showTextHints'] === undefined) return false;
    if (!('reducedMotion' in value) || value['reducedMotion'] === undefined) return false;
    if (!('showGuessHistory' in value) || value['showGuessHistory'] === undefined) return false;
    if (!('timezone' in value) || value['timezone'] === undefined) return false;
    return true;
}

export function UserPreferenceDtoFromJSON(json: any): UserPreferenceDto {
    return UserPreferenceDtoFromJSONTyped(json, false);
}

export function UserPreferenceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPreferenceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'showAlbumHint': json['showAlbumHint'],
        'showTextHints': json['showTextHints'],
        'reducedMotion': json['reducedMotion'],
        'showGuessHistory': json['showGuessHistory'],
        'timezone': json['timezone'],
    };
}

export function UserPreferenceDtoToJSON(json: any): UserPreferenceDto {
    return UserPreferenceDtoToJSONTyped(json, false);
}

export function UserPreferenceDtoToJSONTyped(value?: UserPreferenceDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'showAlbumHint': value['showAlbumHint'],
        'showTextHints': value['showTextHints'],
        'reducedMotion': value['reducedMotion'],
        'showGuessHistory': value['showGuessHistory'],
        'timezone': value['timezone'],
    };
}

