/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminUserDto,
  AuthMeResponseDto,
  ChangePasswordDto,
  ConfirmEmailDto,
  ConfirmPasswordResetDto,
  CreateRoomDto,
  CreateStreakQuestionDto,
  EmailVerificationResultDto,
  GameHistoryDto,
  GameStateDto,
  GameStatsDto,
  GauntletGuessResultDto,
  GauntletHistoryDto,
  GauntletLeaderboardDto,
  GauntletRunStateDto,
  GuessDto,
  GuessResultDto,
  KickPlayerDto,
  LoginDto,
  MultiplayerRoundStateDto,
  PasswordResetResultDto,
  PatchUserDto,
  PersonalBestDto,
  PlayedTodayDto,
  PlaylistDto,
  PlaylistsResponseDto,
  QuizNextResponseDto,
  QuizResultDto,
  RequestPasswordResetDto,
  RoomDto,
  ScoreboardDto,
  SetTrackSourceDto,
  ShareResultDto,
  SignupDto,
  StartGameDto,
  StartRunDto,
  StreakQuestionDto,
  StreakStatusDto,
  SubmitGauntletGuessDto,
  SubmitQuizAnswerDto,
  TrackOptionDto,
  UpdateAvatarSourceDto,
  UpdateStreakQuestionDto,
  UpdateUserPreferenceDto,
  UpdateUserRoleDto,
  UploadAvatarResponseDto,
  UserPreferenceDto,
} from '../models/index';
import {
    AdminUserDtoFromJSON,
    AdminUserDtoToJSON,
    AuthMeResponseDtoFromJSON,
    AuthMeResponseDtoToJSON,
    ChangePasswordDtoFromJSON,
    ChangePasswordDtoToJSON,
    ConfirmEmailDtoFromJSON,
    ConfirmEmailDtoToJSON,
    ConfirmPasswordResetDtoFromJSON,
    ConfirmPasswordResetDtoToJSON,
    CreateRoomDtoFromJSON,
    CreateRoomDtoToJSON,
    CreateStreakQuestionDtoFromJSON,
    CreateStreakQuestionDtoToJSON,
    EmailVerificationResultDtoFromJSON,
    EmailVerificationResultDtoToJSON,
    GameHistoryDtoFromJSON,
    GameHistoryDtoToJSON,
    GameStateDtoFromJSON,
    GameStateDtoToJSON,
    GameStatsDtoFromJSON,
    GameStatsDtoToJSON,
    GauntletGuessResultDtoFromJSON,
    GauntletGuessResultDtoToJSON,
    GauntletHistoryDtoFromJSON,
    GauntletHistoryDtoToJSON,
    GauntletLeaderboardDtoFromJSON,
    GauntletLeaderboardDtoToJSON,
    GauntletRunStateDtoFromJSON,
    GauntletRunStateDtoToJSON,
    GuessDtoFromJSON,
    GuessDtoToJSON,
    GuessResultDtoFromJSON,
    GuessResultDtoToJSON,
    KickPlayerDtoFromJSON,
    KickPlayerDtoToJSON,
    LoginDtoFromJSON,
    LoginDtoToJSON,
    MultiplayerRoundStateDtoFromJSON,
    MultiplayerRoundStateDtoToJSON,
    PasswordResetResultDtoFromJSON,
    PasswordResetResultDtoToJSON,
    PatchUserDtoFromJSON,
    PatchUserDtoToJSON,
    PersonalBestDtoFromJSON,
    PersonalBestDtoToJSON,
    PlayedTodayDtoFromJSON,
    PlayedTodayDtoToJSON,
    PlaylistDtoFromJSON,
    PlaylistDtoToJSON,
    PlaylistsResponseDtoFromJSON,
    PlaylistsResponseDtoToJSON,
    QuizNextResponseDtoFromJSON,
    QuizNextResponseDtoToJSON,
    QuizResultDtoFromJSON,
    QuizResultDtoToJSON,
    RequestPasswordResetDtoFromJSON,
    RequestPasswordResetDtoToJSON,
    RoomDtoFromJSON,
    RoomDtoToJSON,
    ScoreboardDtoFromJSON,
    ScoreboardDtoToJSON,
    SetTrackSourceDtoFromJSON,
    SetTrackSourceDtoToJSON,
    ShareResultDtoFromJSON,
    ShareResultDtoToJSON,
    SignupDtoFromJSON,
    SignupDtoToJSON,
    StartGameDtoFromJSON,
    StartGameDtoToJSON,
    StartRunDtoFromJSON,
    StartRunDtoToJSON,
    StreakQuestionDtoFromJSON,
    StreakQuestionDtoToJSON,
    StreakStatusDtoFromJSON,
    StreakStatusDtoToJSON,
    SubmitGauntletGuessDtoFromJSON,
    SubmitGauntletGuessDtoToJSON,
    SubmitQuizAnswerDtoFromJSON,
    SubmitQuizAnswerDtoToJSON,
    TrackOptionDtoFromJSON,
    TrackOptionDtoToJSON,
    UpdateAvatarSourceDtoFromJSON,
    UpdateAvatarSourceDtoToJSON,
    UpdateStreakQuestionDtoFromJSON,
    UpdateStreakQuestionDtoToJSON,
    UpdateUserPreferenceDtoFromJSON,
    UpdateUserPreferenceDtoToJSON,
    UpdateUserRoleDtoFromJSON,
    UpdateUserRoleDtoToJSON,
    UploadAvatarResponseDtoFromJSON,
    UploadAvatarResponseDtoToJSON,
    UserPreferenceDtoFromJSON,
    UserPreferenceDtoToJSON,
} from '../models/index';

export interface AdminControllerCreateStreakQuestionRequest {
    createStreakQuestionDto: CreateStreakQuestionDto;
}

export interface AdminControllerDeleteStreakQuestionRequest {
    id: string;
}

export interface AdminControllerUpdateStreakQuestionRequest {
    id: string;
    updateStreakQuestionDto: UpdateStreakQuestionDto;
}

export interface AdminControllerUpdateUserRoleRequest {
    id: string;
    updateUserRoleDto: UpdateUserRoleDto;
}

export interface AuthControllerCallbackRequest {
    code: string;
    state: string;
    error?: object;
    ubi?: object;
}

export interface AuthControllerChangePasswordRequest {
    changePasswordDto: ChangePasswordDto;
}

export interface AuthControllerConfirmEmailRequest {
    confirmEmailDto: ConfirmEmailDto;
}

export interface AuthControllerConfirmPasswordResetRequest {
    confirmPasswordResetDto: ConfirmPasswordResetDto;
}

export interface AuthControllerLoginWithPasswordRequest {
    loginDto: LoginDto;
}

export interface AuthControllerRequestPasswordResetRequest {
    requestPasswordResetDto: RequestPasswordResetDto;
}

export interface AuthControllerSignupRequest {
    signupDto: SignupDto;
}

export interface AuthControllerUpdateMeRequest {
    patchUserDto: PatchUserDto;
}

export interface GameControllerGetGameStateRequest {
    id: string;
}

export interface GameControllerGetHistoryRequest {
    mode?: GameControllerGetHistoryModeEnum;
    page?: number;
    limit?: number;
    search?: string;
    status?: Array<GameControllerGetHistoryStatusEnum>;
    from?: Date;
    to?: Date;
}

export interface GameControllerGetShareRequest {
    id: string;
}

export interface GameControllerGetStatsRequest {
    mode: GameControllerGetStatsModeEnum;
}

export interface GameControllerStartGameRequest {
    startGameDto: StartGameDto;
}

export interface GameControllerSubmitGuessRequest {
    id: string;
    guessDto: GuessDto;
}

export interface GauntletControllerEndRunRequest {
    id: string;
}

export interface GauntletControllerGetHistoryRequest {
    page?: number;
    limit?: number;
    difficulty?: GauntletControllerGetHistoryDifficultyEnum;
}

export interface GauntletControllerGetLeaderboardRequest {
    period?: GauntletControllerGetLeaderboardPeriodEnum;
    limit?: number;
    offset?: number;
}

export interface GauntletControllerGetRunStateRequest {
    id: string;
}

export interface GauntletControllerStartRunRequest {
    startRunDto: StartRunDto;
}

export interface GauntletControllerSubmitGuessRequest {
    id: string;
    submitGauntletGuessDto: SubmitGauntletGuessDto;
}

export interface MultiplayerControllerCreateRoomRequest {
    createRoomDto: CreateRoomDto;
}

export interface MultiplayerControllerGetRoomStateRequest {
    id: string;
}

export interface MultiplayerControllerGetRoundStateRequest {
    id: string;
}

export interface MultiplayerControllerGetScoreboardRequest {
    id: string;
}

export interface MultiplayerControllerJoinRoomRequest {
    code: string;
}

export interface MultiplayerControllerKickPlayerRequest {
    id: string;
    kickPlayerDto: KickPlayerDto;
}

export interface MultiplayerControllerLeaveRoomRequest {
    id: string;
}

export interface MultiplayerControllerSetTrackSourceRequest {
    id: string;
    setTrackSourceDto: SetTrackSourceDto;
}

export interface MultiplayerControllerStartGameRequest {
    id: string;
}

export interface MultiplayerControllerSubmitGuessRequest {
    id: string;
    guessDto: GuessDto;
}

export interface MultiplayerControllerToggleReadyRequest {
    id: string;
}

export interface PlaylistControllerGetMyPlaylistsRequest {
    limit?: number;
    offset?: number;
    onlyPublic?: boolean;
    onlyPrivate?: boolean;
    sortBy?: PlaylistControllerGetMyPlaylistsSortByEnum;
}

export interface PlaylistControllerGetPlaylistByIdRequest {
    id: string;
}

export interface SearchControllerSearchTracksRequest {
    q: string;
}

export interface StreakControllerSubmitAnswerRequest {
    submitQuizAnswerDto: SubmitQuizAnswerDto;
}

export interface UserAvatarControllerUpdateSourceRequest {
    updateAvatarSourceDto: UpdateAvatarSourceDto;
}

export interface UserAvatarControllerUploadRequest {
    file: Blob;
}

export interface UserPreferencesControllerUpdateRequest {
    updateUserPreferenceDto: UpdateUserPreferenceDto;
}

/**
 * 
 */
export class ApiApi extends runtime.BaseAPI {

    /**
     * Create a streak quiz question
     */
    async adminControllerCreateStreakQuestionRaw(requestParameters: AdminControllerCreateStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakQuestionDto>> {
        if (requestParameters['createStreakQuestionDto'] == null) {
            throw new runtime.RequiredError(
                'createStreakQuestionDto',
                'Required parameter "createStreakQuestionDto" was null or undefined when calling adminControllerCreateStreakQuestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/admin/streak-questions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStreakQuestionDtoToJSON(requestParameters['createStreakQuestionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakQuestionDtoFromJSON(jsonValue));
    }

    /**
     * Create a streak quiz question
     */
    async adminControllerCreateStreakQuestion(requestParameters: AdminControllerCreateStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakQuestionDto> {
        const response = await this.adminControllerCreateStreakQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft-delete a streak quiz question
     */
    async adminControllerDeleteStreakQuestionRaw(requestParameters: AdminControllerDeleteStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminControllerDeleteStreakQuestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/streak-questions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft-delete a streak quiz question
     */
    async adminControllerDeleteStreakQuestion(requestParameters: AdminControllerDeleteStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerDeleteStreakQuestionRaw(requestParameters, initOverrides);
    }

    /**
     * List all streak quiz questions
     */
    async adminControllerListStreakQuestionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StreakQuestionDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/streak-questions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StreakQuestionDtoFromJSON));
    }

    /**
     * List all streak quiz questions
     */
    async adminControllerListStreakQuestions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StreakQuestionDto>> {
        const response = await this.adminControllerListStreakQuestionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * List all users
     */
    async adminControllerListUsersRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminUserDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/users`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdminUserDtoFromJSON));
    }

    /**
     * List all users
     */
    async adminControllerListUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminUserDto>> {
        const response = await this.adminControllerListUsersRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update a streak quiz question
     */
    async adminControllerUpdateStreakQuestionRaw(requestParameters: AdminControllerUpdateStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakQuestionDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminControllerUpdateStreakQuestion().'
            );
        }

        if (requestParameters['updateStreakQuestionDto'] == null) {
            throw new runtime.RequiredError(
                'updateStreakQuestionDto',
                'Required parameter "updateStreakQuestionDto" was null or undefined when calling adminControllerUpdateStreakQuestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/admin/streak-questions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateStreakQuestionDtoToJSON(requestParameters['updateStreakQuestionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakQuestionDtoFromJSON(jsonValue));
    }

    /**
     * Update a streak quiz question
     */
    async adminControllerUpdateStreakQuestion(requestParameters: AdminControllerUpdateStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakQuestionDto> {
        const response = await this.adminControllerUpdateStreakQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update user role flags
     */
    async adminControllerUpdateUserRoleRaw(requestParameters: AdminControllerUpdateUserRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminUserDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminControllerUpdateUserRole().'
            );
        }

        if (requestParameters['updateUserRoleDto'] == null) {
            throw new runtime.RequiredError(
                'updateUserRoleDto',
                'Required parameter "updateUserRoleDto" was null or undefined when calling adminControllerUpdateUserRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/admin/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserRoleDtoToJSON(requestParameters['updateUserRoleDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminUserDtoFromJSON(jsonValue));
    }

    /**
     * Update user role flags
     */
    async adminControllerUpdateUserRole(requestParameters: AdminControllerUpdateUserRoleRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminUserDto> {
        const response = await this.adminControllerUpdateUserRoleRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handle Spotify OAuth callback
     */
    async authControllerCallbackRaw(requestParameters: AuthControllerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling authControllerCallback().'
            );
        }

        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling authControllerCallback().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['error'] != null) {
            queryParameters['error'] = requestParameters['error'];
        }

        if (requestParameters['ubi'] != null) {
            queryParameters['ubi'] = requestParameters['ubi'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Handle Spotify OAuth callback
     */
    async authControllerCallback(requestParameters: AuthControllerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Change the password of the signed in account
     */
    async authControllerChangePasswordRaw(requestParameters: AuthControllerChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['changePasswordDto'] == null) {
            throw new runtime.RequiredError(
                'changePasswordDto',
                'Required parameter "changePasswordDto" was null or undefined when calling authControllerChangePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePasswordDtoToJSON(requestParameters['changePasswordDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Change the password of the signed in account
     */
    async authControllerChangePassword(requestParameters: AuthControllerChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerChangePasswordRaw(requestParameters, initOverrides);
    }

    /**
     * Spend a verification link
     */
    async authControllerConfirmEmailRaw(requestParameters: AuthControllerConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmailVerificationResultDto>> {
        if (requestParameters['confirmEmailDto'] == null) {
            throw new runtime.RequiredError(
                'confirmEmailDto',
                'Required parameter "confirmEmailDto" was null or undefined when calling authControllerConfirmEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/verify-email/confirm`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmEmailDtoToJSON(requestParameters['confirmEmailDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmailVerificationResultDtoFromJSON(jsonValue));
    }

    /**
     * Spend a verification link
     */
    async authControllerConfirmEmail(requestParameters: AuthControllerConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmailVerificationResultDto> {
        const response = await this.authControllerConfirmEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Spend a reset link and set a new password
     */
    async authControllerConfirmPasswordResetRaw(requestParameters: AuthControllerConfirmPasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PasswordResetResultDto>> {
        if (requestParameters['confirmPasswordResetDto'] == null) {
            throw new runtime.RequiredError(
                'confirmPasswordResetDto',
                'Required parameter "confirmPasswordResetDto" was null or undefined when calling authControllerConfirmPasswordReset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/password-reset/confirm`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmPasswordResetDtoToJSON(requestParameters['confirmPasswordResetDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PasswordResetResultDtoFromJSON(jsonValue));
    }

    /**
     * Spend a reset link and set a new password
     */
    async authControllerConfirmPasswordReset(requestParameters: AuthControllerConfirmPasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PasswordResetResultDto> {
        const response = await this.authControllerConfirmPasswordResetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Ensure the caller has an identity, minting one if they have none
     */
    async authControllerEnsureSessionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMeResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/session`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthMeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Ensure the caller has an identity, minting one if they have none
     */
    async authControllerEnsureSession(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMeResponseDto> {
        const response = await this.authControllerEnsureSessionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Start Spotify OAuth flow
     */
    async authControllerLoginRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start Spotify OAuth flow
     */
    async authControllerLogin(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLoginRaw(initOverrides);
    }

    /**
     * Sign in with an email and password
     */
    async authControllerLoginWithPasswordRaw(requestParameters: AuthControllerLoginWithPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMeResponseDto>> {
        if (requestParameters['loginDto'] == null) {
            throw new runtime.RequiredError(
                'loginDto',
                'Required parameter "loginDto" was null or undefined when calling authControllerLoginWithPassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/signin`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginDtoToJSON(requestParameters['loginDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthMeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Sign in with an email and password
     */
    async authControllerLoginWithPassword(requestParameters: AuthControllerLoginWithPasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMeResponseDto> {
        const response = await this.authControllerLoginWithPasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Logout and clear session
     */
    async authControllerLogoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logout and clear session
     */
    async authControllerLogout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLogoutRaw(initOverrides);
    }

    /**
     * Get current authenticated user
     */
    async authControllerMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMeResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthMeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get current authenticated user
     */
    async authControllerMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMeResponseDto> {
        const response = await this.authControllerMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Ask for a link to choose a new password
     */
    async authControllerRequestPasswordResetRaw(requestParameters: AuthControllerRequestPasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['requestPasswordResetDto'] == null) {
            throw new runtime.RequiredError(
                'requestPasswordResetDto',
                'Required parameter "requestPasswordResetDto" was null or undefined when calling authControllerRequestPasswordReset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/password-reset`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RequestPasswordResetDtoToJSON(requestParameters['requestPasswordResetDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Ask for a link to choose a new password
     */
    async authControllerRequestPasswordReset(requestParameters: AuthControllerRequestPasswordResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerRequestPasswordResetRaw(requestParameters, initOverrides);
    }

    /**
     * Send the verification link again
     */
    async authControllerResendVerificationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/verify-email/resend`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Send the verification link again
     */
    async authControllerResendVerification(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerResendVerificationRaw(initOverrides);
    }

    /**
     * Create an account, keeping any guest progress
     */
    async authControllerSignupRaw(requestParameters: AuthControllerSignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMeResponseDto>> {
        if (requestParameters['signupDto'] == null) {
            throw new runtime.RequiredError(
                'signupDto',
                'Required parameter "signupDto" was null or undefined when calling authControllerSignup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/signup`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignupDtoToJSON(requestParameters['signupDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthMeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Create an account, keeping any guest progress
     */
    async authControllerSignup(requestParameters: AuthControllerSignupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMeResponseDto> {
        const response = await this.authControllerSignupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update current user profile
     */
    async authControllerUpdateMeRaw(requestParameters: AuthControllerUpdateMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMeResponseDto>> {
        if (requestParameters['patchUserDto'] == null) {
            throw new runtime.RequiredError(
                'patchUserDto',
                'Required parameter "patchUserDto" was null or undefined when calling authControllerUpdateMe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchUserDtoToJSON(requestParameters['patchUserDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthMeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Update current user profile
     */
    async authControllerUpdateMe(requestParameters: AuthControllerUpdateMeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMeResponseDto> {
        const response = await this.authControllerUpdateMeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current game state
     */
    async gameControllerGetGameStateRaw(requestParameters: GameControllerGetGameStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStateDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerGetGameState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStateDtoFromJSON(jsonValue));
    }

    /**
     * Get current game state
     */
    async gameControllerGetGameState(requestParameters: GameControllerGetGameStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStateDto> {
        const response = await this.gameControllerGetGameStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s game session history (paginated)
     */
    async gameControllerGetHistoryRaw(requestParameters: GameControllerGetHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameHistoryDto>> {
        const queryParameters: any = {};

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/history`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameHistoryDtoFromJSON(jsonValue));
    }

    /**
     * Get user\'s game session history (paginated)
     */
    async gameControllerGetHistory(requestParameters: GameControllerGetHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameHistoryDto> {
        const response = await this.gameControllerGetHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Whether the user has played today\'s daily
     */
    async gameControllerGetPlayedTodayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlayedTodayDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/daily/played-today`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayedTodayDtoFromJSON(jsonValue));
    }

    /**
     * Whether the user has played today\'s daily
     */
    async gameControllerGetPlayedToday(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlayedTodayDto> {
        const response = await this.gameControllerGetPlayedTodayRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get shareable result for a game session
     */
    async gameControllerGetShareRaw(requestParameters: GameControllerGetShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShareResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerGetShare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/share/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShareResultDtoFromJSON(jsonValue));
    }

    /**
     * Get shareable result for a game session
     */
    async gameControllerGetShare(requestParameters: GameControllerGetShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShareResultDto> {
        const response = await this.gameControllerGetShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s daily stats
     */
    async gameControllerGetStatsRaw(requestParameters: GameControllerGetStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStatsDto>> {
        if (requestParameters['mode'] == null) {
            throw new runtime.RequiredError(
                'mode',
                'Required parameter "mode" was null or undefined when calling gameControllerGetStats().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStatsDtoFromJSON(jsonValue));
    }

    /**
     * Get user\'s daily stats
     */
    async gameControllerGetStats(requestParameters: GameControllerGetStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStatsDto> {
        const response = await this.gameControllerGetStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a new game from a playlist or daily
     */
    async gameControllerStartGameRaw(requestParameters: GameControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStateDto>> {
        if (requestParameters['startGameDto'] == null) {
            throw new runtime.RequiredError(
                'startGameDto',
                'Required parameter "startGameDto" was null or undefined when calling gameControllerStartGame().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/game/start`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartGameDtoToJSON(requestParameters['startGameDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStateDtoFromJSON(jsonValue));
    }

    /**
     * Start a new game from a playlist or daily
     */
    async gameControllerStartGame(requestParameters: GameControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStateDto> {
        const response = await this.gameControllerStartGameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit a guess for a specific session
     */
    async gameControllerSubmitGuessRaw(requestParameters: GameControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuessResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerSubmitGuess().'
            );
        }

        if (requestParameters['guessDto'] == null) {
            throw new runtime.RequiredError(
                'guessDto',
                'Required parameter "guessDto" was null or undefined when calling gameControllerSubmitGuess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/game/{id}/guess`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuessDtoToJSON(requestParameters['guessDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuessResultDtoFromJSON(jsonValue));
    }

    /**
     * Submit a guess for a specific session
     */
    async gameControllerSubmitGuess(requestParameters: GameControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuessResultDto> {
        const response = await this.gameControllerSubmitGuessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Voluntarily end a gauntlet run (quit)
     */
    async gauntletControllerEndRunRaw(requestParameters: GauntletControllerEndRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletRunStateDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gauntletControllerEndRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gauntlet/{id}/end`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletRunStateDtoFromJSON(jsonValue));
    }

    /**
     * Voluntarily end a gauntlet run (quit)
     */
    async gauntletControllerEndRun(requestParameters: GauntletControllerEndRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletRunStateDto> {
        const response = await this.gauntletControllerEndRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s gauntlet run history (paginated)
     */
    async gauntletControllerGetHistoryRaw(requestParameters: GauntletControllerGetHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletHistoryDto>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['difficulty'] != null) {
            queryParameters['difficulty'] = requestParameters['difficulty'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gauntlet/history`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletHistoryDtoFromJSON(jsonValue));
    }

    /**
     * Get user\'s gauntlet run history (paginated)
     */
    async gauntletControllerGetHistory(requestParameters: GauntletControllerGetHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletHistoryDto> {
        const response = await this.gauntletControllerGetHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get gauntlet leaderboard
     */
    async gauntletControllerGetLeaderboardRaw(requestParameters: GauntletControllerGetLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletLeaderboardDto>> {
        const queryParameters: any = {};

        if (requestParameters['period'] != null) {
            queryParameters['period'] = requestParameters['period'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gauntlet/leaderboard`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletLeaderboardDtoFromJSON(jsonValue));
    }

    /**
     * Get gauntlet leaderboard
     */
    async gauntletControllerGetLeaderboard(requestParameters: GauntletControllerGetLeaderboardRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletLeaderboardDto> {
        const response = await this.gauntletControllerGetLeaderboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s gauntlet personal best
     */
    async gauntletControllerGetPersonalBestRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonalBestDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gauntlet/personal-best`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonalBestDtoFromJSON(jsonValue));
    }

    /**
     * Get user\'s gauntlet personal best
     */
    async gauntletControllerGetPersonalBest(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonalBestDto> {
        const response = await this.gauntletControllerGetPersonalBestRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get current gauntlet run state
     */
    async gauntletControllerGetRunStateRaw(requestParameters: GauntletControllerGetRunStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletRunStateDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gauntletControllerGetRunState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gauntlet/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletRunStateDtoFromJSON(jsonValue));
    }

    /**
     * Get current gauntlet run state
     */
    async gauntletControllerGetRunState(requestParameters: GauntletControllerGetRunStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletRunStateDto> {
        const response = await this.gauntletControllerGetRunStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a new gauntlet run
     */
    async gauntletControllerStartRunRaw(requestParameters: GauntletControllerStartRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletRunStateDto>> {
        if (requestParameters['startRunDto'] == null) {
            throw new runtime.RequiredError(
                'startRunDto',
                'Required parameter "startRunDto" was null or undefined when calling gauntletControllerStartRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/gauntlet/start`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartRunDtoToJSON(requestParameters['startRunDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletRunStateDtoFromJSON(jsonValue));
    }

    /**
     * Start a new gauntlet run
     */
    async gauntletControllerStartRun(requestParameters: GauntletControllerStartRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletRunStateDto> {
        const response = await this.gauntletControllerStartRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit a guess for the current gauntlet track
     */
    async gauntletControllerSubmitGuessRaw(requestParameters: GauntletControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletGuessResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gauntletControllerSubmitGuess().'
            );
        }

        if (requestParameters['submitGauntletGuessDto'] == null) {
            throw new runtime.RequiredError(
                'submitGauntletGuessDto',
                'Required parameter "submitGauntletGuessDto" was null or undefined when calling gauntletControllerSubmitGuess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/gauntlet/{id}/guess`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitGauntletGuessDtoToJSON(requestParameters['submitGauntletGuessDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletGuessResultDtoFromJSON(jsonValue));
    }

    /**
     * Submit a guess for the current gauntlet track
     */
    async gauntletControllerSubmitGuess(requestParameters: GauntletControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletGuessResultDto> {
        const response = await this.gauntletControllerSubmitGuessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new multiplayer room
     */
    async multiplayerControllerCreateRoomRaw(requestParameters: MultiplayerControllerCreateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomDto>> {
        if (requestParameters['createRoomDto'] == null) {
            throw new runtime.RequiredError(
                'createRoomDto',
                'Required parameter "createRoomDto" was null or undefined when calling multiplayerControllerCreateRoom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/multiplayer/rooms`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateRoomDtoToJSON(requestParameters['createRoomDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomDtoFromJSON(jsonValue));
    }

    /**
     * Create a new multiplayer room
     */
    async multiplayerControllerCreateRoom(requestParameters: MultiplayerControllerCreateRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomDto> {
        const response = await this.multiplayerControllerCreateRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get room state with players
     */
    async multiplayerControllerGetRoomStateRaw(requestParameters: MultiplayerControllerGetRoomStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling multiplayerControllerGetRoomState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/multiplayer/rooms/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomDtoFromJSON(jsonValue));
    }

    /**
     * Get room state with players
     */
    async multiplayerControllerGetRoomState(requestParameters: MultiplayerControllerGetRoomStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomDto> {
        const response = await this.multiplayerControllerGetRoomStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current round state for the player
     */
    async multiplayerControllerGetRoundStateRaw(requestParameters: MultiplayerControllerGetRoundStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MultiplayerRoundStateDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling multiplayerControllerGetRoundState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/multiplayer/rooms/{id}/round`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MultiplayerRoundStateDtoFromJSON(jsonValue));
    }

    /**
     * Get current round state for the player
     */
    async multiplayerControllerGetRoundState(requestParameters: MultiplayerControllerGetRoundStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MultiplayerRoundStateDto> {
        const response = await this.multiplayerControllerGetRoundStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get scoreboard (only completed rounds visible)
     */
    async multiplayerControllerGetScoreboardRaw(requestParameters: MultiplayerControllerGetScoreboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScoreboardDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling multiplayerControllerGetScoreboard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/multiplayer/rooms/{id}/scoreboard`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScoreboardDtoFromJSON(jsonValue));
    }

    /**
     * Get scoreboard (only completed rounds visible)
     */
    async multiplayerControllerGetScoreboard(requestParameters: MultiplayerControllerGetScoreboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScoreboardDto> {
        const response = await this.multiplayerControllerGetScoreboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Join a room by invite code
     */
    async multiplayerControllerJoinRoomRaw(requestParameters: MultiplayerControllerJoinRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomDto>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling multiplayerControllerJoinRoom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/multiplayer/rooms/{code}/join`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomDtoFromJSON(jsonValue));
    }

    /**
     * Join a room by invite code
     */
    async multiplayerControllerJoinRoom(requestParameters: MultiplayerControllerJoinRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomDto> {
        const response = await this.multiplayerControllerJoinRoomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a player from the room (host only)
     */
    async multiplayerControllerKickPlayerRaw(requestParameters: MultiplayerControllerKickPlayerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling multiplayerControllerKickPlayer().'
            );
        }

        if (requestParameters['kickPlayerDto'] == null) {
            throw new runtime.RequiredError(
                'kickPlayerDto',
                'Required parameter "kickPlayerDto" was null or undefined when calling multiplayerControllerKickPlayer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/multiplayer/rooms/{id}/kick`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KickPlayerDtoToJSON(requestParameters['kickPlayerDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomDtoFromJSON(jsonValue));
    }

    /**
     * Remove a player from the room (host only)
     */
    async multiplayerControllerKickPlayer(requestParameters: MultiplayerControllerKickPlayerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomDto> {
        const response = await this.multiplayerControllerKickPlayerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Leave a room (host leaving expires it)
     */
    async multiplayerControllerLeaveRoomRaw(requestParameters: MultiplayerControllerLeaveRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling multiplayerControllerLeaveRoom().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/multiplayer/rooms/{id}/leave`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Leave a room (host leaving expires it)
     */
    async multiplayerControllerLeaveRoom(requestParameters: MultiplayerControllerLeaveRoomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.multiplayerControllerLeaveRoomRaw(requestParameters, initOverrides);
    }

    /**
     * Choose where the room draws its songs from
     */
    async multiplayerControllerSetTrackSourceRaw(requestParameters: MultiplayerControllerSetTrackSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling multiplayerControllerSetTrackSource().'
            );
        }

        if (requestParameters['setTrackSourceDto'] == null) {
            throw new runtime.RequiredError(
                'setTrackSourceDto',
                'Required parameter "setTrackSourceDto" was null or undefined when calling multiplayerControllerSetTrackSource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/multiplayer/rooms/{id}/track-source`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SetTrackSourceDtoToJSON(requestParameters['setTrackSourceDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomDtoFromJSON(jsonValue));
    }

    /**
     * Choose where the room draws its songs from
     */
    async multiplayerControllerSetTrackSource(requestParameters: MultiplayerControllerSetTrackSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomDto> {
        const response = await this.multiplayerControllerSetTrackSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start the game (host only)
     */
    async multiplayerControllerStartGameRaw(requestParameters: MultiplayerControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling multiplayerControllerStartGame().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/multiplayer/rooms/{id}/start`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomDtoFromJSON(jsonValue));
    }

    /**
     * Start the game (host only)
     */
    async multiplayerControllerStartGame(requestParameters: MultiplayerControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomDto> {
        const response = await this.multiplayerControllerStartGameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit a guess for the current round
     */
    async multiplayerControllerSubmitGuessRaw(requestParameters: MultiplayerControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuessResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling multiplayerControllerSubmitGuess().'
            );
        }

        if (requestParameters['guessDto'] == null) {
            throw new runtime.RequiredError(
                'guessDto',
                'Required parameter "guessDto" was null or undefined when calling multiplayerControllerSubmitGuess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/multiplayer/rooms/{id}/guess`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuessDtoToJSON(requestParameters['guessDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuessResultDtoFromJSON(jsonValue));
    }

    /**
     * Submit a guess for the current round
     */
    async multiplayerControllerSubmitGuess(requestParameters: MultiplayerControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuessResultDto> {
        const response = await this.multiplayerControllerSubmitGuessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Toggle ready status for current player
     */
    async multiplayerControllerToggleReadyRaw(requestParameters: MultiplayerControllerToggleReadyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RoomDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling multiplayerControllerToggleReady().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/multiplayer/rooms/{id}/ready`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RoomDtoFromJSON(jsonValue));
    }

    /**
     * Toggle ready status for current player
     */
    async multiplayerControllerToggleReady(requestParameters: MultiplayerControllerToggleReadyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RoomDto> {
        const response = await this.multiplayerControllerToggleReadyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current user\'s playlists
     */
    async playlistControllerGetMyPlaylistsRaw(requestParameters: PlaylistControllerGetMyPlaylistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistsResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['onlyPublic'] != null) {
            queryParameters['onlyPublic'] = requestParameters['onlyPublic'];
        }

        if (requestParameters['onlyPrivate'] != null) {
            queryParameters['onlyPrivate'] = requestParameters['onlyPrivate'];
        }

        if (requestParameters['sortBy'] != null) {
            queryParameters['sortBy'] = requestParameters['sortBy'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/playlists/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get current user\'s playlists
     */
    async playlistControllerGetMyPlaylists(requestParameters: PlaylistControllerGetMyPlaylistsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistsResponseDto> {
        const response = await this.playlistControllerGetMyPlaylistsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get playlist by ID
     */
    async playlistControllerGetPlaylistByIdRaw(requestParameters: PlaylistControllerGetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling playlistControllerGetPlaylistById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/playlists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistDtoFromJSON(jsonValue));
    }

    /**
     * Get playlist by ID
     */
    async playlistControllerGetPlaylistById(requestParameters: PlaylistControllerGetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistDto> {
        const response = await this.playlistControllerGetPlaylistByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search tracks (for game guess options)
     */
    async searchControllerSearchTracksRaw(requestParameters: SearchControllerSearchTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrackOptionDto>>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchControllerSearchTracks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/tracks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrackOptionDtoFromJSON));
    }

    /**
     * Search tracks (for game guess options)
     */
    async searchControllerSearchTracks(requestParameters: SearchControllerSearchTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrackOptionDto>> {
        const response = await this.searchControllerSearchTracksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the next unanswered quiz question
     */
    async streakControllerGetNextQuestionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuizNextResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/streak/quiz/next`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuizNextResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get the next unanswered quiz question
     */
    async streakControllerGetNextQuestion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuizNextResponseDto> {
        const response = await this.streakControllerGetNextQuestionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get streak status including freeze info
     */
    async streakControllerGetStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakStatusDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/streak/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakStatusDtoFromJSON(jsonValue));
    }

    /**
     * Get streak status including freeze info
     */
    async streakControllerGetStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakStatusDto> {
        const response = await this.streakControllerGetStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Submit a quiz answer to earn a streak freeze
     */
    async streakControllerSubmitAnswerRaw(requestParameters: StreakControllerSubmitAnswerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuizResultDto>> {
        if (requestParameters['submitQuizAnswerDto'] == null) {
            throw new runtime.RequiredError(
                'submitQuizAnswerDto',
                'Required parameter "submitQuizAnswerDto" was null or undefined when calling streakControllerSubmitAnswer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/streak/quiz/answer`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitQuizAnswerDtoToJSON(requestParameters['submitQuizAnswerDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuizResultDtoFromJSON(jsonValue));
    }

    /**
     * Submit a quiz answer to earn a streak freeze
     */
    async streakControllerSubmitAnswer(requestParameters: StreakControllerSubmitAnswerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuizResultDto> {
        const response = await this.streakControllerSubmitAnswerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Apply streak freezes to bridge a gap
     */
    async streakControllerUseFreezeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakStatusDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/streak/use-freeze`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakStatusDtoFromJSON(jsonValue));
    }

    /**
     * Apply streak freezes to bridge a gap
     */
    async streakControllerUseFreeze(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakStatusDto> {
        const response = await this.streakControllerUseFreezeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Switch between Spotify and custom avatar
     */
    async userAvatarControllerUpdateSourceRaw(requestParameters: UserAvatarControllerUpdateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadAvatarResponseDto>> {
        if (requestParameters['updateAvatarSourceDto'] == null) {
            throw new runtime.RequiredError(
                'updateAvatarSourceDto',
                'Required parameter "updateAvatarSourceDto" was null or undefined when calling userAvatarControllerUpdateSource().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user-avatar/source`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAvatarSourceDtoToJSON(requestParameters['updateAvatarSourceDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadAvatarResponseDtoFromJSON(jsonValue));
    }

    /**
     * Switch between Spotify and custom avatar
     */
    async userAvatarControllerUpdateSource(requestParameters: UserAvatarControllerUpdateSourceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadAvatarResponseDto> {
        const response = await this.userAvatarControllerUpdateSourceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a custom avatar image
     */
    async userAvatarControllerUploadRaw(requestParameters: UserAvatarControllerUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UploadAvatarResponseDto>> {
        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling userAvatarControllerUpload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/user-avatar/upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UploadAvatarResponseDtoFromJSON(jsonValue));
    }

    /**
     * Upload a custom avatar image
     */
    async userAvatarControllerUpload(requestParameters: UserAvatarControllerUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UploadAvatarResponseDto> {
        const response = await this.userAvatarControllerUploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user preferences
     */
    async userPreferencesControllerGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPreferenceDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user-preferences`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPreferenceDtoFromJSON(jsonValue));
    }

    /**
     * Get user preferences
     */
    async userPreferencesControllerGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPreferenceDto> {
        const response = await this.userPreferencesControllerGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update user preferences
     */
    async userPreferencesControllerUpdateRaw(requestParameters: UserPreferencesControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserPreferenceDto>> {
        if (requestParameters['updateUserPreferenceDto'] == null) {
            throw new runtime.RequiredError(
                'updateUserPreferenceDto',
                'Required parameter "updateUserPreferenceDto" was null or undefined when calling userPreferencesControllerUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user-preferences`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUserPreferenceDtoToJSON(requestParameters['updateUserPreferenceDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserPreferenceDtoFromJSON(jsonValue));
    }

    /**
     * Update user preferences
     */
    async userPreferencesControllerUpdate(requestParameters: UserPreferencesControllerUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserPreferenceDto> {
        const response = await this.userPreferencesControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GameControllerGetHistoryModeEnum = {
    Daily: 'DAILY',
    All: 'ALL',
    Multiplayer: 'MULTIPLAYER',
    Gauntlet: 'GAUNTLET'
} as const;
export type GameControllerGetHistoryModeEnum = typeof GameControllerGetHistoryModeEnum[keyof typeof GameControllerGetHistoryModeEnum];
/**
 * @export
 */
export const GameControllerGetHistoryStatusEnum = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST',
    Abandoned: 'ABANDONED'
} as const;
export type GameControllerGetHistoryStatusEnum = typeof GameControllerGetHistoryStatusEnum[keyof typeof GameControllerGetHistoryStatusEnum];
/**
 * @export
 */
export const GameControllerGetStatsModeEnum = {
    Daily: 'DAILY',
    All: 'ALL',
    Multiplayer: 'MULTIPLAYER',
    Gauntlet: 'GAUNTLET'
} as const;
export type GameControllerGetStatsModeEnum = typeof GameControllerGetStatsModeEnum[keyof typeof GameControllerGetStatsModeEnum];
/**
 * @export
 */
export const GauntletControllerGetHistoryDifficultyEnum = {
    Easy: 'EASY',
    Medium: 'MEDIUM',
    Hard: 'HARD',
    Expert: 'EXPERT'
} as const;
export type GauntletControllerGetHistoryDifficultyEnum = typeof GauntletControllerGetHistoryDifficultyEnum[keyof typeof GauntletControllerGetHistoryDifficultyEnum];
/**
 * @export
 */
export const GauntletControllerGetLeaderboardPeriodEnum = {
    Daily: 'daily',
    Weekly: 'weekly',
    Alltime: 'alltime'
} as const;
export type GauntletControllerGetLeaderboardPeriodEnum = typeof GauntletControllerGetLeaderboardPeriodEnum[keyof typeof GauntletControllerGetLeaderboardPeriodEnum];
/**
 * @export
 */
export const PlaylistControllerGetMyPlaylistsSortByEnum = {
    Default: 'default',
    Name: 'name',
    Tracks: 'tracks'
} as const;
export type PlaylistControllerGetMyPlaylistsSortByEnum = typeof PlaylistControllerGetMyPlaylistsSortByEnum[keyof typeof PlaylistControllerGetMyPlaylistsSortByEnum];
