/* tslint:disable */
 
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthMeResponseDto,
  CreateMessageDto,
  GameHistoryDto,
  GameStateDto,
  GameStatsDto,
  GuessDto,
  GuessResultDto,
  MessageDto,
  PlayedTodayDto,
  PlaylistDto,
  PlaylistsResponseDto,
  ShareResultDto,
  StartGameDto,
  TokenLoginDto,
  TrackOptionDto,
  UpdateMessageDto,
} from '../models/index';
import {
    AuthMeResponseDtoFromJSON,
    AuthMeResponseDtoToJSON,
    CreateMessageDtoFromJSON,
    CreateMessageDtoToJSON,
    GameHistoryDtoFromJSON,
    GameHistoryDtoToJSON,
    GameStateDtoFromJSON,
    GameStateDtoToJSON,
    GameStatsDtoFromJSON,
    GameStatsDtoToJSON,
    GuessDtoFromJSON,
    GuessDtoToJSON,
    GuessResultDtoFromJSON,
    GuessResultDtoToJSON,
    MessageDtoFromJSON,
    MessageDtoToJSON,
    PlayedTodayDtoFromJSON,
    PlayedTodayDtoToJSON,
    PlaylistDtoFromJSON,
    PlaylistDtoToJSON,
    PlaylistsResponseDtoFromJSON,
    PlaylistsResponseDtoToJSON,
    ShareResultDtoFromJSON,
    ShareResultDtoToJSON,
    StartGameDtoFromJSON,
    StartGameDtoToJSON,
    TokenLoginDtoFromJSON,
    TokenLoginDtoToJSON,
    TrackOptionDtoFromJSON,
    TrackOptionDtoToJSON,
    UpdateMessageDtoFromJSON,
    UpdateMessageDtoToJSON,
} from '../models/index';

export interface AdminControllerCreateMessageRequest {
    createMessageDto: CreateMessageDto;
}

export interface AdminControllerDeleteMessageRequest {
    id: string;
}

export interface AdminControllerUpdateMessageRequest {
    id: string;
    updateMessageDto: UpdateMessageDto;
}

export interface AuthControllerCallbackRequest {
    code: string;
    state: string;
    error: string;
}

export interface AuthControllerTokenLoginRequest {
    tokenLoginDto: TokenLoginDto;
}

export interface GameControllerGetGameStateRequest {
    id: string;
}

export interface GameControllerGetHistoryRequest {
    isDaily?: boolean;
    limit?: number;
    offset?: number;
}

export interface GameControllerGetShareRequest {
    id: string;
}

export interface GameControllerGetStatsRequest {
    mode: GameControllerGetStatsModeEnum;
}

export interface GameControllerStartGameRequest {
    startGameDto: StartGameDto;
}

export interface GameControllerSubmitGuessRequest {
    id: string;
    guessDto: GuessDto;
}

export interface PlaylistControllerGetMyPlaylistsRequest {
    limit?: number;
    offset?: number;
    includePrivate?: boolean;
    onlyUserOwned?: boolean;
}

export interface PlaylistControllerGetPlaylistByIdRequest {
    id: string;
}

export interface SearchControllerSearchTracksRequest {
    q: string;
}

/**
 * 
 */
export class ApiApi extends runtime.BaseAPI {

    /**
     * Create a new message (admin only)
     */
    async adminControllerCreateMessageRaw(requestParameters: AdminControllerCreateMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageDto>> {
        if (requestParameters['createMessageDto'] == null) {
            throw new runtime.RequiredError(
                'createMessageDto',
                'Required parameter "createMessageDto" was null or undefined when calling adminControllerCreateMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/admin/messages`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateMessageDtoToJSON(requestParameters['createMessageDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageDtoFromJSON(jsonValue));
    }

    /**
     * Create a new message (admin only)
     */
    async adminControllerCreateMessage(requestParameters: AdminControllerCreateMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageDto> {
        const response = await this.adminControllerCreateMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a message (admin only)
     */
    async adminControllerDeleteMessageRaw(requestParameters: AdminControllerDeleteMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminControllerDeleteMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/messages/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a message (admin only)
     */
    async adminControllerDeleteMessage(requestParameters: AdminControllerDeleteMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerDeleteMessageRaw(requestParameters, initOverrides);
    }

    /**
     * Get all messages (admin only)
     */
    async adminControllerGetAllMessagesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MessageDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/messages`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MessageDtoFromJSON));
    }

    /**
     * Get all messages (admin only)
     */
    async adminControllerGetAllMessages(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MessageDto>> {
        const response = await this.adminControllerGetAllMessagesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update a message (admin only)
     */
    async adminControllerUpdateMessageRaw(requestParameters: AdminControllerUpdateMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MessageDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminControllerUpdateMessage().'
            );
        }

        if (requestParameters['updateMessageDto'] == null) {
            throw new runtime.RequiredError(
                'updateMessageDto',
                'Required parameter "updateMessageDto" was null or undefined when calling adminControllerUpdateMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/admin/messages/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateMessageDtoToJSON(requestParameters['updateMessageDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MessageDtoFromJSON(jsonValue));
    }

    /**
     * Update a message (admin only)
     */
    async adminControllerUpdateMessage(requestParameters: AdminControllerUpdateMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MessageDto> {
        const response = await this.adminControllerUpdateMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handle Spotify OAuth callback
     */
    async authControllerCallbackRaw(requestParameters: AuthControllerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling authControllerCallback().'
            );
        }

        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling authControllerCallback().'
            );
        }

        if (requestParameters['error'] == null) {
            throw new runtime.RequiredError(
                'error',
                'Required parameter "error" was null or undefined when calling authControllerCallback().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['error'] != null) {
            queryParameters['error'] = requestParameters['error'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Handle Spotify OAuth callback
     */
    async authControllerCallback(requestParameters: AuthControllerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Start Spotify OAuth flow
     */
    async authControllerLoginRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start Spotify OAuth flow
     */
    async authControllerLogin(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLoginRaw(initOverrides);
    }

    /**
     * Logout and clear session
     */
    async authControllerLogoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logout and clear session
     */
    async authControllerLogout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLogoutRaw(initOverrides);
    }

    /**
     * Get current authenticated user
     */
    async authControllerMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMeResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthMeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get current authenticated user
     */
    async authControllerMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMeResponseDto> {
        const response = await this.authControllerMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Use this when you have a Spotify access token but can\'t use OAuth flow. The token is validated by fetching your Spotify profile.
     * Dev-only: Login with a manually obtained Spotify token
     */
    async authControllerTokenLoginRaw(requestParameters: AuthControllerTokenLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['tokenLoginDto'] == null) {
            throw new runtime.RequiredError(
                'tokenLoginDto',
                'Required parameter "tokenLoginDto" was null or undefined when calling authControllerTokenLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/token-login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenLoginDtoToJSON(requestParameters['tokenLoginDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this when you have a Spotify access token but can\'t use OAuth flow. The token is validated by fetching your Spotify profile.
     * Dev-only: Login with a manually obtained Spotify token
     */
    async authControllerTokenLogin(requestParameters: AuthControllerTokenLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerTokenLoginRaw(requestParameters, initOverrides);
    }

    /**
     * Get current game state
     */
    async gameControllerGetGameStateRaw(requestParameters: GameControllerGetGameStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStateDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerGetGameState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStateDtoFromJSON(jsonValue));
    }

    /**
     * Get current game state
     */
    async gameControllerGetGameState(requestParameters: GameControllerGetGameStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStateDto> {
        const response = await this.gameControllerGetGameStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s game session history (paginated)
     */
    async gameControllerGetHistoryRaw(requestParameters: GameControllerGetHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameHistoryDto>> {
        const queryParameters: any = {};

        if (requestParameters['isDaily'] != null) {
            queryParameters['isDaily'] = requestParameters['isDaily'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/history`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameHistoryDtoFromJSON(jsonValue));
    }

    /**
     * Get user\'s game session history (paginated)
     */
    async gameControllerGetHistory(requestParameters: GameControllerGetHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameHistoryDto> {
        const response = await this.gameControllerGetHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Whether the user has played today\'s daily
     */
    async gameControllerGetPlayedTodayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlayedTodayDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/daily/played-today`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayedTodayDtoFromJSON(jsonValue));
    }

    /**
     * Whether the user has played today\'s daily
     */
    async gameControllerGetPlayedToday(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlayedTodayDto> {
        const response = await this.gameControllerGetPlayedTodayRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get shareable result for a game session
     */
    async gameControllerGetShareRaw(requestParameters: GameControllerGetShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShareResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerGetShare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/share/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShareResultDtoFromJSON(jsonValue));
    }

    /**
     * Get shareable result for a game session
     */
    async gameControllerGetShare(requestParameters: GameControllerGetShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShareResultDto> {
        const response = await this.gameControllerGetShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s daily stats
     */
    async gameControllerGetStatsRaw(requestParameters: GameControllerGetStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStatsDto>> {
        if (requestParameters['mode'] == null) {
            throw new runtime.RequiredError(
                'mode',
                'Required parameter "mode" was null or undefined when calling gameControllerGetStats().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStatsDtoFromJSON(jsonValue));
    }

    /**
     * Get user\'s daily stats
     */
    async gameControllerGetStats(requestParameters: GameControllerGetStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStatsDto> {
        const response = await this.gameControllerGetStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a new game from a playlist or daily
     */
    async gameControllerStartGameRaw(requestParameters: GameControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStateDto>> {
        if (requestParameters['startGameDto'] == null) {
            throw new runtime.RequiredError(
                'startGameDto',
                'Required parameter "startGameDto" was null or undefined when calling gameControllerStartGame().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/game/start`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartGameDtoToJSON(requestParameters['startGameDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStateDtoFromJSON(jsonValue));
    }

    /**
     * Start a new game from a playlist or daily
     */
    async gameControllerStartGame(requestParameters: GameControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStateDto> {
        const response = await this.gameControllerStartGameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit a guess for a specific session
     */
    async gameControllerSubmitGuessRaw(requestParameters: GameControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuessResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerSubmitGuess().'
            );
        }

        if (requestParameters['guessDto'] == null) {
            throw new runtime.RequiredError(
                'guessDto',
                'Required parameter "guessDto" was null or undefined when calling gameControllerSubmitGuess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/game/{id}/guess`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuessDtoToJSON(requestParameters['guessDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuessResultDtoFromJSON(jsonValue));
    }

    /**
     * Submit a guess for a specific session
     */
    async gameControllerSubmitGuess(requestParameters: GameControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuessResultDto> {
        const response = await this.gameControllerSubmitGuessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current user\'s playlists
     */
    async playlistControllerGetMyPlaylistsRaw(requestParameters: PlaylistControllerGetMyPlaylistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistsResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['includePrivate'] != null) {
            queryParameters['includePrivate'] = requestParameters['includePrivate'];
        }

        if (requestParameters['onlyUserOwned'] != null) {
            queryParameters['onlyUserOwned'] = requestParameters['onlyUserOwned'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/playlists/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get current user\'s playlists
     */
    async playlistControllerGetMyPlaylists(requestParameters: PlaylistControllerGetMyPlaylistsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistsResponseDto> {
        const response = await this.playlistControllerGetMyPlaylistsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get playlist by ID
     */
    async playlistControllerGetPlaylistByIdRaw(requestParameters: PlaylistControllerGetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling playlistControllerGetPlaylistById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/playlists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistDtoFromJSON(jsonValue));
    }

    /**
     * Get playlist by ID
     */
    async playlistControllerGetPlaylistById(requestParameters: PlaylistControllerGetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistDto> {
        const response = await this.playlistControllerGetPlaylistByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search Spotify tracks (for game guess options)
     */
    async searchControllerSearchTracksRaw(requestParameters: SearchControllerSearchTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrackOptionDto>>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchControllerSearchTracks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/tracks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrackOptionDtoFromJSON));
    }

    /**
     * Search Spotify tracks (for game guess options)
     */
    async searchControllerSearchTracks(requestParameters: SearchControllerSearchTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrackOptionDto>> {
        const response = await this.searchControllerSearchTracksRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GameControllerGetStatsModeEnum = {
    Daily: 'DAILY',
    All: 'ALL'
} as const;
export type GameControllerGetStatsModeEnum = typeof GameControllerGetStatsModeEnum[keyof typeof GameControllerGetStatsModeEnum];
