/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthMeResponseDto,
  CreateStreakQuestionDto,
  GameHistoryDto,
  GameStateDto,
  GameStatsDto,
  GuessDto,
  GuessResultDto,
  PlayedTodayDto,
  PlaylistDto,
  PlaylistsResponseDto,
  QuizNextResponseDto,
  QuizResultDto,
  ShareResultDto,
  StartGameDto,
  StreakQuestionDto,
  StreakStatusDto,
  SubmitQuizAnswerDto,
  TokenLoginDto,
  TrackOptionDto,
  UpdateStreakQuestionDto,
} from '../models/index';
import {
    AuthMeResponseDtoFromJSON,
    AuthMeResponseDtoToJSON,
    CreateStreakQuestionDtoFromJSON,
    CreateStreakQuestionDtoToJSON,
    GameHistoryDtoFromJSON,
    GameHistoryDtoToJSON,
    GameStateDtoFromJSON,
    GameStateDtoToJSON,
    GameStatsDtoFromJSON,
    GameStatsDtoToJSON,
    GuessDtoFromJSON,
    GuessDtoToJSON,
    GuessResultDtoFromJSON,
    GuessResultDtoToJSON,
    PlayedTodayDtoFromJSON,
    PlayedTodayDtoToJSON,
    PlaylistDtoFromJSON,
    PlaylistDtoToJSON,
    PlaylistsResponseDtoFromJSON,
    PlaylistsResponseDtoToJSON,
    QuizNextResponseDtoFromJSON,
    QuizNextResponseDtoToJSON,
    QuizResultDtoFromJSON,
    QuizResultDtoToJSON,
    ShareResultDtoFromJSON,
    ShareResultDtoToJSON,
    StartGameDtoFromJSON,
    StartGameDtoToJSON,
    StreakQuestionDtoFromJSON,
    StreakQuestionDtoToJSON,
    StreakStatusDtoFromJSON,
    StreakStatusDtoToJSON,
    SubmitQuizAnswerDtoFromJSON,
    SubmitQuizAnswerDtoToJSON,
    TokenLoginDtoFromJSON,
    TokenLoginDtoToJSON,
    TrackOptionDtoFromJSON,
    TrackOptionDtoToJSON,
    UpdateStreakQuestionDtoFromJSON,
    UpdateStreakQuestionDtoToJSON,
} from '../models/index';

export interface AdminControllerCreateStreakQuestionRequest {
    createStreakQuestionDto: CreateStreakQuestionDto;
}

export interface AdminControllerDeleteStreakQuestionRequest {
    id: string;
}

export interface AdminControllerUpdateStreakQuestionRequest {
    id: string;
    updateStreakQuestionDto: UpdateStreakQuestionDto;
}

export interface AuthControllerCallbackRequest {
    code: string;
    state: string;
    error?: object;
}

export interface AuthControllerTokenLoginRequest {
    tokenLoginDto: TokenLoginDto;
}

export interface GameControllerGetGameStateRequest {
    id: string;
}

export interface GameControllerGetHistoryRequest {
    mode?: GameControllerGetHistoryModeEnum;
    page?: number;
    limit?: number;
    search?: string;
    status?: GameControllerGetHistoryStatusEnum;
    from?: Date;
    to?: Date;
}

export interface GameControllerGetShareRequest {
    id: string;
}

export interface GameControllerGetStatsRequest {
    mode: GameControllerGetStatsModeEnum;
}

export interface GameControllerStartGameRequest {
    startGameDto: StartGameDto;
}

export interface GameControllerSubmitGuessRequest {
    id: string;
    guessDto: GuessDto;
}

export interface PlaylistControllerGetMyPlaylistsRequest {
    limit?: number;
    offset?: number;
    onlyPublic?: boolean;
    onlyUserOwned?: boolean;
}

export interface PlaylistControllerGetPlaylistByIdRequest {
    id: string;
}

export interface SearchControllerSearchTracksRequest {
    q: string;
}

export interface StreakControllerSubmitAnswerRequest {
    submitQuizAnswerDto: SubmitQuizAnswerDto;
}

/**
 * 
 */
export class ApiApi extends runtime.BaseAPI {

    /**
     * Create a streak quiz question (admin only)
     */
    async adminControllerCreateStreakQuestionRaw(requestParameters: AdminControllerCreateStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakQuestionDto>> {
        if (requestParameters['createStreakQuestionDto'] == null) {
            throw new runtime.RequiredError(
                'createStreakQuestionDto',
                'Required parameter "createStreakQuestionDto" was null or undefined when calling adminControllerCreateStreakQuestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/admin/streak-questions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStreakQuestionDtoToJSON(requestParameters['createStreakQuestionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakQuestionDtoFromJSON(jsonValue));
    }

    /**
     * Create a streak quiz question (admin only)
     */
    async adminControllerCreateStreakQuestion(requestParameters: AdminControllerCreateStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakQuestionDto> {
        const response = await this.adminControllerCreateStreakQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Soft-delete a streak quiz question (admin only)
     */
    async adminControllerDeleteStreakQuestionRaw(requestParameters: AdminControllerDeleteStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminControllerDeleteStreakQuestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/streak-questions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Soft-delete a streak quiz question (admin only)
     */
    async adminControllerDeleteStreakQuestion(requestParameters: AdminControllerDeleteStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adminControllerDeleteStreakQuestionRaw(requestParameters, initOverrides);
    }

    /**
     * List all streak quiz questions (admin only)
     */
    async adminControllerListStreakQuestionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StreakQuestionDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/admin/streak-questions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StreakQuestionDtoFromJSON));
    }

    /**
     * List all streak quiz questions (admin only)
     */
    async adminControllerListStreakQuestions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StreakQuestionDto>> {
        const response = await this.adminControllerListStreakQuestionsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Update a streak quiz question (admin only)
     */
    async adminControllerUpdateStreakQuestionRaw(requestParameters: AdminControllerUpdateStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakQuestionDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adminControllerUpdateStreakQuestion().'
            );
        }

        if (requestParameters['updateStreakQuestionDto'] == null) {
            throw new runtime.RequiredError(
                'updateStreakQuestionDto',
                'Required parameter "updateStreakQuestionDto" was null or undefined when calling adminControllerUpdateStreakQuestion().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/admin/streak-questions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateStreakQuestionDtoToJSON(requestParameters['updateStreakQuestionDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakQuestionDtoFromJSON(jsonValue));
    }

    /**
     * Update a streak quiz question (admin only)
     */
    async adminControllerUpdateStreakQuestion(requestParameters: AdminControllerUpdateStreakQuestionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakQuestionDto> {
        const response = await this.adminControllerUpdateStreakQuestionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Handle Spotify OAuth callback
     */
    async authControllerCallbackRaw(requestParameters: AuthControllerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling authControllerCallback().'
            );
        }

        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling authControllerCallback().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['error'] != null) {
            queryParameters['error'] = requestParameters['error'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Handle Spotify OAuth callback
     */
    async authControllerCallback(requestParameters: AuthControllerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Start Spotify OAuth flow
     */
    async authControllerLoginRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start Spotify OAuth flow
     */
    async authControllerLogin(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLoginRaw(initOverrides);
    }

    /**
     * Logout and clear session
     */
    async authControllerLogoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logout and clear session
     */
    async authControllerLogout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLogoutRaw(initOverrides);
    }

    /**
     * Get current authenticated user
     */
    async authControllerMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMeResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthMeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get current authenticated user
     */
    async authControllerMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMeResponseDto> {
        const response = await this.authControllerMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Use this when you have a Spotify access token but can\'t use OAuth flow. The token is validated by fetching your Spotify profile.
     * Dev-only: Login with a manually obtained Spotify token
     */
    async authControllerTokenLoginRaw(requestParameters: AuthControllerTokenLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['tokenLoginDto'] == null) {
            throw new runtime.RequiredError(
                'tokenLoginDto',
                'Required parameter "tokenLoginDto" was null or undefined when calling authControllerTokenLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/token-login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenLoginDtoToJSON(requestParameters['tokenLoginDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this when you have a Spotify access token but can\'t use OAuth flow. The token is validated by fetching your Spotify profile.
     * Dev-only: Login with a manually obtained Spotify token
     */
    async authControllerTokenLogin(requestParameters: AuthControllerTokenLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerTokenLoginRaw(requestParameters, initOverrides);
    }

    /**
     * Get current game state
     */
    async gameControllerGetGameStateRaw(requestParameters: GameControllerGetGameStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStateDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerGetGameState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStateDtoFromJSON(jsonValue));
    }

    /**
     * Get current game state
     */
    async gameControllerGetGameState(requestParameters: GameControllerGetGameStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStateDto> {
        const response = await this.gameControllerGetGameStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s game session history (paginated)
     */
    async gameControllerGetHistoryRaw(requestParameters: GameControllerGetHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameHistoryDto>> {
        const queryParameters: any = {};

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['from'] != null) {
            queryParameters['from'] = (requestParameters['from'] as any).toISOString();
        }

        if (requestParameters['to'] != null) {
            queryParameters['to'] = (requestParameters['to'] as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/history`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameHistoryDtoFromJSON(jsonValue));
    }

    /**
     * Get user\'s game session history (paginated)
     */
    async gameControllerGetHistory(requestParameters: GameControllerGetHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameHistoryDto> {
        const response = await this.gameControllerGetHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Whether the user has played today\'s daily
     */
    async gameControllerGetPlayedTodayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlayedTodayDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/daily/played-today`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlayedTodayDtoFromJSON(jsonValue));
    }

    /**
     * Whether the user has played today\'s daily
     */
    async gameControllerGetPlayedToday(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlayedTodayDto> {
        const response = await this.gameControllerGetPlayedTodayRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get shareable result for a game session
     */
    async gameControllerGetShareRaw(requestParameters: GameControllerGetShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ShareResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerGetShare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/share/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ShareResultDtoFromJSON(jsonValue));
    }

    /**
     * Get shareable result for a game session
     */
    async gameControllerGetShare(requestParameters: GameControllerGetShareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ShareResultDto> {
        const response = await this.gameControllerGetShareRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s daily stats
     */
    async gameControllerGetStatsRaw(requestParameters: GameControllerGetStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStatsDto>> {
        if (requestParameters['mode'] == null) {
            throw new runtime.RequiredError(
                'mode',
                'Required parameter "mode" was null or undefined when calling gameControllerGetStats().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['mode'] != null) {
            queryParameters['mode'] = requestParameters['mode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/stats`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStatsDtoFromJSON(jsonValue));
    }

    /**
     * Get user\'s daily stats
     */
    async gameControllerGetStats(requestParameters: GameControllerGetStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStatsDto> {
        const response = await this.gameControllerGetStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a new game from a playlist or daily
     */
    async gameControllerStartGameRaw(requestParameters: GameControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStateDto>> {
        if (requestParameters['startGameDto'] == null) {
            throw new runtime.RequiredError(
                'startGameDto',
                'Required parameter "startGameDto" was null or undefined when calling gameControllerStartGame().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/game/start`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartGameDtoToJSON(requestParameters['startGameDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStateDtoFromJSON(jsonValue));
    }

    /**
     * Start a new game from a playlist or daily
     */
    async gameControllerStartGame(requestParameters: GameControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStateDto> {
        const response = await this.gameControllerStartGameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit a guess for a specific session
     */
    async gameControllerSubmitGuessRaw(requestParameters: GameControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuessResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerSubmitGuess().'
            );
        }

        if (requestParameters['guessDto'] == null) {
            throw new runtime.RequiredError(
                'guessDto',
                'Required parameter "guessDto" was null or undefined when calling gameControllerSubmitGuess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/game/{id}/guess`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuessDtoToJSON(requestParameters['guessDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuessResultDtoFromJSON(jsonValue));
    }

    /**
     * Submit a guess for a specific session
     */
    async gameControllerSubmitGuess(requestParameters: GameControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuessResultDto> {
        const response = await this.gameControllerSubmitGuessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get current user\'s playlists
     */
    async playlistControllerGetMyPlaylistsRaw(requestParameters: PlaylistControllerGetMyPlaylistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistsResponseDto>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['onlyPublic'] != null) {
            queryParameters['onlyPublic'] = requestParameters['onlyPublic'];
        }

        if (requestParameters['onlyUserOwned'] != null) {
            queryParameters['onlyUserOwned'] = requestParameters['onlyUserOwned'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/playlists/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistsResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get current user\'s playlists
     */
    async playlistControllerGetMyPlaylists(requestParameters: PlaylistControllerGetMyPlaylistsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistsResponseDto> {
        const response = await this.playlistControllerGetMyPlaylistsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get playlist by ID
     */
    async playlistControllerGetPlaylistByIdRaw(requestParameters: PlaylistControllerGetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaylistDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling playlistControllerGetPlaylistById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/playlists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaylistDtoFromJSON(jsonValue));
    }

    /**
     * Get playlist by ID
     */
    async playlistControllerGetPlaylistById(requestParameters: PlaylistControllerGetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaylistDto> {
        const response = await this.playlistControllerGetPlaylistByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search Spotify tracks (for game guess options)
     */
    async searchControllerSearchTracksRaw(requestParameters: SearchControllerSearchTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TrackOptionDto>>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling searchControllerSearchTracks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/search/tracks`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TrackOptionDtoFromJSON));
    }

    /**
     * Search Spotify tracks (for game guess options)
     */
    async searchControllerSearchTracks(requestParameters: SearchControllerSearchTracksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TrackOptionDto>> {
        const response = await this.searchControllerSearchTracksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get the next unanswered quiz question
     */
    async streakControllerGetNextQuestionRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuizNextResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/streak/quiz/next`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuizNextResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get the next unanswered quiz question
     */
    async streakControllerGetNextQuestion(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuizNextResponseDto> {
        const response = await this.streakControllerGetNextQuestionRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get streak status including freeze info
     */
    async streakControllerGetStatusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakStatusDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/streak/status`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakStatusDtoFromJSON(jsonValue));
    }

    /**
     * Get streak status including freeze info
     */
    async streakControllerGetStatus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakStatusDto> {
        const response = await this.streakControllerGetStatusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Submit a quiz answer to earn a streak freeze
     */
    async streakControllerSubmitAnswerRaw(requestParameters: StreakControllerSubmitAnswerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QuizResultDto>> {
        if (requestParameters['submitQuizAnswerDto'] == null) {
            throw new runtime.RequiredError(
                'submitQuizAnswerDto',
                'Required parameter "submitQuizAnswerDto" was null or undefined when calling streakControllerSubmitAnswer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/streak/quiz/answer`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitQuizAnswerDtoToJSON(requestParameters['submitQuizAnswerDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QuizResultDtoFromJSON(jsonValue));
    }

    /**
     * Submit a quiz answer to earn a streak freeze
     */
    async streakControllerSubmitAnswer(requestParameters: StreakControllerSubmitAnswerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QuizResultDto> {
        const response = await this.streakControllerSubmitAnswerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Apply streak freezes to bridge a gap
     */
    async streakControllerUseFreezeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StreakStatusDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/streak/use-freeze`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StreakStatusDtoFromJSON(jsonValue));
    }

    /**
     * Apply streak freezes to bridge a gap
     */
    async streakControllerUseFreeze(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StreakStatusDto> {
        const response = await this.streakControllerUseFreezeRaw(initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GameControllerGetHistoryModeEnum = {
    Daily: 'DAILY',
    All: 'ALL'
} as const;
export type GameControllerGetHistoryModeEnum = typeof GameControllerGetHistoryModeEnum[keyof typeof GameControllerGetHistoryModeEnum];
/**
 * @export
 */
export const GameControllerGetHistoryStatusEnum = {
    Playing: 'PLAYING',
    Won: 'WON',
    Lost: 'LOST',
    Abandoned: 'ABANDONED'
} as const;
export type GameControllerGetHistoryStatusEnum = typeof GameControllerGetHistoryStatusEnum[keyof typeof GameControllerGetHistoryStatusEnum];
/**
 * @export
 */
export const GameControllerGetStatsModeEnum = {
    Daily: 'DAILY',
    All: 'ALL'
} as const;
export type GameControllerGetStatsModeEnum = typeof GameControllerGetStatsModeEnum[keyof typeof GameControllerGetStatsModeEnum];
