/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthMeResponseDto,
  TokenLoginDto,
} from '../models/index';
import {
    AuthMeResponseDtoFromJSON,
    AuthMeResponseDtoToJSON,
    TokenLoginDtoFromJSON,
    TokenLoginDtoToJSON,
} from '../models/index';

export interface AuthControllerCallbackRequest {
    code: string;
    state: string;
    error: string;
}

export interface AuthControllerTokenLoginRequest {
    tokenLoginDto: TokenLoginDto;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Handle Spotify OAuth callback
     */
    async authControllerCallbackRaw(requestParameters: AuthControllerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling authControllerCallback().'
            );
        }

        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling authControllerCallback().'
            );
        }

        if (requestParameters['error'] == null) {
            throw new runtime.RequiredError(
                'error',
                'Required parameter "error" was null or undefined when calling authControllerCallback().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['error'] != null) {
            queryParameters['error'] = requestParameters['error'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/callback`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Handle Spotify OAuth callback
     */
    async authControllerCallback(requestParameters: AuthControllerCallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerCallbackRaw(requestParameters, initOverrides);
    }

    /**
     * Start Spotify OAuth flow
     */
    async authControllerLoginRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start Spotify OAuth flow
     */
    async authControllerLogin(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLoginRaw(initOverrides);
    }

    /**
     * Logout and clear session
     */
    async authControllerLogoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logout and clear session
     */
    async authControllerLogout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerLogoutRaw(initOverrides);
    }

    /**
     * Get current authenticated user
     */
    async authControllerMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMeResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthMeResponseDtoFromJSON(jsonValue));
    }

    /**
     * Get current authenticated user
     */
    async authControllerMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMeResponseDto> {
        const response = await this.authControllerMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Use this when you have a Spotify access token but can\'t use OAuth flow. The token is validated by fetching your Spotify profile.
     * Dev-only: Login with a manually obtained Spotify token
     */
    async authControllerTokenLoginRaw(requestParameters: AuthControllerTokenLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['tokenLoginDto'] == null) {
            throw new runtime.RequiredError(
                'tokenLoginDto',
                'Required parameter "tokenLoginDto" was null or undefined when calling authControllerTokenLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/token-login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenLoginDtoToJSON(requestParameters['tokenLoginDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Use this when you have a Spotify access token but can\'t use OAuth flow. The token is validated by fetching your Spotify profile.
     * Dev-only: Login with a manually obtained Spotify token
     */
    async authControllerTokenLogin(requestParameters: AuthControllerTokenLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authControllerTokenLoginRaw(requestParameters, initOverrides);
    }

}
