/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DemoGuessResultDto,
  DemoPlaylistDto,
  DemoRoundDto,
  GuessDemoDto,
  StartDemoRoundDto,
} from '../models/index';
import {
    DemoGuessResultDtoFromJSON,
    DemoGuessResultDtoToJSON,
    DemoPlaylistDtoFromJSON,
    DemoPlaylistDtoToJSON,
    DemoRoundDtoFromJSON,
    DemoRoundDtoToJSON,
    GuessDemoDtoFromJSON,
    GuessDemoDtoToJSON,
    StartDemoRoundDtoFromJSON,
    StartDemoRoundDtoToJSON,
} from '../models/index';

export interface DemoControllerGuessRequest {
    roundId: string;
    guessDemoDto: GuessDemoDto;
}

export interface DemoControllerStartRoundRequest {
    startDemoRoundDto: StartDemoRoundDto;
}

/**
 * 
 */
export class DemoApi extends runtime.BaseAPI {

    /**
     * Playlists a demo round can be started from
     */
    async demoControllerGetPlaylistsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DemoPlaylistDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/demo/playlists`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DemoPlaylistDtoFromJSON));
    }

    /**
     * Playlists a demo round can be started from
     */
    async demoControllerGetPlaylists(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DemoPlaylistDto>> {
        const response = await this.demoControllerGetPlaylistsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Score a guess; reveals the answer when resolved
     */
    async demoControllerGuessRaw(requestParameters: DemoControllerGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DemoGuessResultDto>> {
        if (requestParameters['roundId'] == null) {
            throw new runtime.RequiredError(
                'roundId',
                'Required parameter "roundId" was null or undefined when calling demoControllerGuess().'
            );
        }

        if (requestParameters['guessDemoDto'] == null) {
            throw new runtime.RequiredError(
                'guessDemoDto',
                'Required parameter "guessDemoDto" was null or undefined when calling demoControllerGuess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/demo/rounds/{roundId}/guesses`;
        urlPath = urlPath.replace(`{${"roundId"}}`, encodeURIComponent(String(requestParameters['roundId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuessDemoDtoToJSON(requestParameters['guessDemoDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DemoGuessResultDtoFromJSON(jsonValue));
    }

    /**
     * Score a guess; reveals the answer when resolved
     */
    async demoControllerGuess(requestParameters: DemoControllerGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DemoGuessResultDto> {
        const response = await this.demoControllerGuessRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a round; the answer stays server-side
     */
    async demoControllerStartRoundRaw(requestParameters: DemoControllerStartRoundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DemoRoundDto>> {
        if (requestParameters['startDemoRoundDto'] == null) {
            throw new runtime.RequiredError(
                'startDemoRoundDto',
                'Required parameter "startDemoRoundDto" was null or undefined when calling demoControllerStartRound().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/demo/rounds`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartDemoRoundDtoToJSON(requestParameters['startDemoRoundDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DemoRoundDtoFromJSON(jsonValue));
    }

    /**
     * Start a round; the answer stays server-side
     */
    async demoControllerStartRound(requestParameters: DemoControllerStartRoundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DemoRoundDto> {
        const response = await this.demoControllerStartRoundRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
