/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GameStateDto,
  GuessDto,
  GuessResultDto,
  StartGameDto,
} from '../models/index';
import {
    GameStateDtoFromJSON,
    GameStateDtoToJSON,
    GuessDtoFromJSON,
    GuessDtoToJSON,
    GuessResultDtoFromJSON,
    GuessResultDtoToJSON,
    StartGameDtoFromJSON,
    StartGameDtoToJSON,
} from '../models/index';

export interface GameControllerGetGameStateRequest {
    id: string;
}

export interface GameControllerStartGameRequest {
    startGameDto: StartGameDto;
}

export interface GameControllerSubmitGuessRequest {
    id: string;
    guessDto: GuessDto;
}

/**
 * 
 */
export class GameApi extends runtime.BaseAPI {

    /**
     * Get current game state
     */
    async gameControllerGetGameStateRaw(requestParameters: GameControllerGetGameStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStateDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerGetGameState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/game/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStateDtoFromJSON(jsonValue));
    }

    /**
     * Get current game state
     */
    async gameControllerGetGameState(requestParameters: GameControllerGetGameStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStateDto> {
        const response = await this.gameControllerGetGameStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a new game from a playlist
     */
    async gameControllerStartGameRaw(requestParameters: GameControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GameStateDto>> {
        if (requestParameters['startGameDto'] == null) {
            throw new runtime.RequiredError(
                'startGameDto',
                'Required parameter "startGameDto" was null or undefined when calling gameControllerStartGame().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/game/start`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartGameDtoToJSON(requestParameters['startGameDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GameStateDtoFromJSON(jsonValue));
    }

    /**
     * Start a new game from a playlist
     */
    async gameControllerStartGame(requestParameters: GameControllerStartGameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GameStateDto> {
        const response = await this.gameControllerStartGameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit a guess for a specific session
     */
    async gameControllerSubmitGuessRaw(requestParameters: GameControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GuessResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gameControllerSubmitGuess().'
            );
        }

        if (requestParameters['guessDto'] == null) {
            throw new runtime.RequiredError(
                'guessDto',
                'Required parameter "guessDto" was null or undefined when calling gameControllerSubmitGuess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/game/{id}/guess`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GuessDtoToJSON(requestParameters['guessDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GuessResultDtoFromJSON(jsonValue));
    }

    /**
     * Submit a guess for a specific session
     */
    async gameControllerSubmitGuess(requestParameters: GameControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GuessResultDto> {
        const response = await this.gameControllerSubmitGuessRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
