/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GauntletGuessResultDto,
  GauntletLeaderboardDto,
  GauntletRunStateDto,
  GetLeaderboardDto,
  PersonalBestDto,
  StartRunDto,
  SubmitGauntletGuessDto,
} from '../models/index';
import {
    GauntletGuessResultDtoFromJSON,
    GauntletGuessResultDtoToJSON,
    GauntletLeaderboardDtoFromJSON,
    GauntletLeaderboardDtoToJSON,
    GauntletRunStateDtoFromJSON,
    GauntletRunStateDtoToJSON,
    GetLeaderboardDtoFromJSON,
    GetLeaderboardDtoToJSON,
    PersonalBestDtoFromJSON,
    PersonalBestDtoToJSON,
    StartRunDtoFromJSON,
    StartRunDtoToJSON,
    SubmitGauntletGuessDtoFromJSON,
    SubmitGauntletGuessDtoToJSON,
} from '../models/index';

export interface GauntletControllerEndRunRequest {
    id: string;
}

export interface GauntletControllerGetLeaderboardRequest {
    getLeaderboardDto: GetLeaderboardDto;
}

export interface GauntletControllerGetRunStateRequest {
    id: string;
}

export interface GauntletControllerStartRunRequest {
    startRunDto: StartRunDto;
}

export interface GauntletControllerSubmitGuessRequest {
    id: string;
    submitGauntletGuessDto: SubmitGauntletGuessDto;
}

/**
 * 
 */
export class GauntletApi extends runtime.BaseAPI {

    /**
     * Voluntarily end a gauntlet run (quit)
     */
    async gauntletControllerEndRunRaw(requestParameters: GauntletControllerEndRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletRunStateDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gauntletControllerEndRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gauntlet/{id}/end`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletRunStateDtoFromJSON(jsonValue));
    }

    /**
     * Voluntarily end a gauntlet run (quit)
     */
    async gauntletControllerEndRun(requestParameters: GauntletControllerEndRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletRunStateDto> {
        const response = await this.gauntletControllerEndRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get gauntlet leaderboard
     */
    async gauntletControllerGetLeaderboardRaw(requestParameters: GauntletControllerGetLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletLeaderboardDto>> {
        if (requestParameters['getLeaderboardDto'] == null) {
            throw new runtime.RequiredError(
                'getLeaderboardDto',
                'Required parameter "getLeaderboardDto" was null or undefined when calling gauntletControllerGetLeaderboard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/gauntlet/leaderboard`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
            body: GetLeaderboardDtoToJSON(requestParameters['getLeaderboardDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletLeaderboardDtoFromJSON(jsonValue));
    }

    /**
     * Get gauntlet leaderboard
     */
    async gauntletControllerGetLeaderboard(requestParameters: GauntletControllerGetLeaderboardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletLeaderboardDto> {
        const response = await this.gauntletControllerGetLeaderboardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get user\'s gauntlet personal best
     */
    async gauntletControllerGetPersonalBestRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PersonalBestDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gauntlet/personal-best`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PersonalBestDtoFromJSON(jsonValue));
    }

    /**
     * Get user\'s gauntlet personal best
     */
    async gauntletControllerGetPersonalBest(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PersonalBestDto> {
        const response = await this.gauntletControllerGetPersonalBestRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get current gauntlet run state
     */
    async gauntletControllerGetRunStateRaw(requestParameters: GauntletControllerGetRunStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletRunStateDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gauntletControllerGetRunState().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gauntlet/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletRunStateDtoFromJSON(jsonValue));
    }

    /**
     * Get current gauntlet run state
     */
    async gauntletControllerGetRunState(requestParameters: GauntletControllerGetRunStateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletRunStateDto> {
        const response = await this.gauntletControllerGetRunStateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start a new gauntlet run
     */
    async gauntletControllerStartRunRaw(requestParameters: GauntletControllerStartRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletRunStateDto>> {
        if (requestParameters['startRunDto'] == null) {
            throw new runtime.RequiredError(
                'startRunDto',
                'Required parameter "startRunDto" was null or undefined when calling gauntletControllerStartRun().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/gauntlet/start`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StartRunDtoToJSON(requestParameters['startRunDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletRunStateDtoFromJSON(jsonValue));
    }

    /**
     * Start a new gauntlet run
     */
    async gauntletControllerStartRun(requestParameters: GauntletControllerStartRunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletRunStateDto> {
        const response = await this.gauntletControllerStartRunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit a guess for the current gauntlet track
     */
    async gauntletControllerSubmitGuessRaw(requestParameters: GauntletControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GauntletGuessResultDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling gauntletControllerSubmitGuess().'
            );
        }

        if (requestParameters['submitGauntletGuessDto'] == null) {
            throw new runtime.RequiredError(
                'submitGauntletGuessDto',
                'Required parameter "submitGauntletGuessDto" was null or undefined when calling gauntletControllerSubmitGuess().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/gauntlet/{id}/guess`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubmitGauntletGuessDtoToJSON(requestParameters['submitGauntletGuessDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GauntletGuessResultDtoFromJSON(jsonValue));
    }

    /**
     * Submit a guess for the current gauntlet track
     */
    async gauntletControllerSubmitGuess(requestParameters: GauntletControllerSubmitGuessRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GauntletGuessResultDto> {
        const response = await this.gauntletControllerSubmitGuessRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
