/* tslint:disable */
/* eslint-disable */
/**
 * Unpaused Spotify API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface PlaylistsControllerGetMyPlaylistsRequest {
    limit?: number;
    offset?: number;
    includePrivate?: boolean;
    onlyUserOwned?: boolean;
}

export interface PlaylistsControllerGetPlaylistByIdRequest {
    id: string;
}

/**
 * 
 */
export class PlaylistsApi extends runtime.BaseAPI {

    /**
     * Get current user\'s playlists
     */
    async playlistsControllerGetMyPlaylistsRaw(requestParameters: PlaylistsControllerGetMyPlaylistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['includePrivate'] != null) {
            queryParameters['includePrivate'] = requestParameters['includePrivate'];
        }

        if (requestParameters['onlyUserOwned'] != null) {
            queryParameters['onlyUserOwned'] = requestParameters['onlyUserOwned'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/playlists/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get current user\'s playlists
     */
    async playlistsControllerGetMyPlaylists(requestParameters: PlaylistsControllerGetMyPlaylistsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.playlistsControllerGetMyPlaylistsRaw(requestParameters, initOverrides);
    }

    /**
     * Get playlist by ID
     */
    async playlistsControllerGetPlaylistByIdRaw(requestParameters: PlaylistsControllerGetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling playlistsControllerGetPlaylistById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/playlists/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get playlist by ID
     */
    async playlistsControllerGetPlaylistById(requestParameters: PlaylistsControllerGetPlaylistByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.playlistsControllerGetPlaylistByIdRaw(requestParameters, initOverrides);
    }

}
